### ISSUE TITLE
Null pointer while loading a new resource file in designer

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1072]
Original [issue 1073](https://code.google.com/p/codenameone/issues/detail?id=1073) created by codenameone on 2014-03-03T13:46:50.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>
Designer - tools.

<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

<b>What steps will reproduce the problem?</b>
1. When opening a resource file, null pointer exception is coming.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

The resource file should get opened.

<b>What version of the product are you using? On what operating system?</b>

Latest version of designer and cn1 plugin ver 2.0.5 on Mac OS(Mavericks) and Intellij Idea.

<b>Please provide any additional information below.</b>

Stack trace of running the designer from command line is given below:

2014-03-03 18:46:37.385:INFO:oejs.Server:jetty-8.0.y.z-SNAPSHOT
2014-03-03 18:46:37.438:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9000 STARTING
Mar 03, 2014 6:46:37 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using ResourceEditorApp
java.lang.NullPointerException
	at java.io.File.&lt;init&gt;(File.java:360)
	at com.codename1.designer.ResourceEditorView$LoadResourceFileAction.exectute(ResourceEditorView.java:4121)
	at com.codename1.ui.resource.util.BlockingAction.run(BlockingAction.java:88)
	at java.lang.Thread.run(Thread.java:744)

I have attached the resource file that is causing this issue. If you are able to open this resource file, then the issue could be something different, like I have another resource file with same name but on different dir and that was causing the null pointer exception. Hence I created a new resource file and gave it the same name as earlier file and saved it in different dir. However when I try to open this new resource file it is giving me the same null pointer exception.

**Comment by codenameone** [comment]
I think this was fixed a while back, if its still happening I'll reopen this.
