### ISSUE TITLE
Simulator wrongly casts a TextArea to a TextField

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1082]
Original [issue 1083](https://code.google.com/p/codenameone/issues/detail?id=1083) created by codenameone on 2014-03-15T23:09:53.000Z:

Simulator issue

Updated the plugin yesterday, but the app has been constructed with the designer a while ago. Not sure if this has an impact.

The weird part is that I could not really reproduce it, however I'm submitting the stack trace anyway because it may be a specific combination that triggered the event. It's probably a good idea to check which Text widget it is instead of assuming it's a TextArea.

Stack trace:
java.lang.ClassCastException: com.codename1.ui.TextArea cannot be cast to com.codename1.ui.TextField
    at com.codename1.impl.javase.JavaSEPort.editString(JavaSEPort.java:2630)
    at com.codename1.impl.CodenameOneImplementation.editStringImpl(CodenameOneImplementation.java:286)
    at com.codename1.ui.Display.editString(Display.java:1439)
    at com.codename1.ui.TextArea.keyReleased(TextArea.java:519)
    at com.codename1.ui.Component.keyRepeated(Component.java:1855)
    at com.codename1.ui.Form.keyRepeated(Form.java:1827)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1007)
    at com.codename1.ui.Display.invokeAndBlock(Display.java:1129)
    at com.codename1.ui.Display.invokeAndBlock(Display.java:1164)
    at com.codename1.impl.javase.JavaSEPort.editString(JavaSEPort.java:2790)
    at com.codename1.impl.CodenameOneImplementation.editStringImpl(CodenameOneImplementation.java:286)
    at com.codename1.ui.Display.editString(Display.java:1439)
    at com.codename1.ui.Display.editString(Display.java:1411)
    at com.codename1.ui.TextArea.editString(TextArea.java:548)
    at com.codename1.ui.TextArea.pointerReleased(TextArea.java:581)
    at com.codename1.ui.Form.pointerReleased(Form.java:2260)
    at com.codename1.ui.Component.pointerReleased(Component.java:2332)
    at com.codename1.ui.Display.handleEvent(Display.java:1892)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:994)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:925)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
