### ISSUE TITLE
Reading from dead socket

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1099]
Original [issue 1100](https://code.google.com/p/codenameone/issues/detail?id=1100) created by codenameone on 2014-04-08T05:57:45.000Z:

This is the same issue as issue 1099 but with code to reproduce it.  Run SocketTestServer on your computer and then call SocketTestClient.run() from inside Codename One.  You will get this:

java.lang.NegativeArraySizeException
    at com.codename1.impl.javase.JavaSEPort$SocketImpl.shrink(JavaSEPort.java:6432)
    at com.codename1.impl.javase.JavaSEPort$SocketImpl.readFromStream(JavaSEPort.java:6423)
    at com.codename1.impl.javase.JavaSEPort.readFromSocketStream(JavaSEPort.java:6552)
    at com.codename1.io.Socket$SocketInputStream.read(Socket.java:179)
    at com.codename1.io.Socket$SocketInputStream.read(Socket.java:221)
    at com.codename1.io.Socket$SocketInputStream.read(Socket.java:228)
    at test.SocketTestClient$1.connectionEstablished(SocketTestClient.java:25)
    at com.codename1.io.Socket$1.run(Socket.java:69)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

This was run with SVN r1802.

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
