### ISSUE TITLE
NullPointerException at om.codename1.plugin.intellij.JavaProcess.getJavaHome when creating a new project

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1208]
Original [issue 1209](https://code.google.com/p/codenameone/issues/detail?id=1209) created by codenameone on 2014-10-07T13:54:59.000Z:

<b>What steps will reproduce the problem?</b>
1. Install IntelliJ 13.1.5
2. Install latest Codenameone plugin for IntelliJ (2.1.0)
3. Create a new project

<b>What is the expected output? What do you see instead?</b>

A new project should be created

I get a nullpointer exception:

java.lang.NullPointerException
	at java.io.File.&lt;init&gt;(File.java:277)
	at com.codename1.plugin.intellij.JavaProcess.getJavaHome(JavaProcess.java:149)
	at com.codename1.plugin.intellij.ResourceFile.openResourceEditor(ResourceFile.java:43)
	at com.codename1.plugin.intellij.ResourceFile.create(ResourceFile.java:39)
	at com.codename1.plugin.intellij.module.NewCodenameOneProject.createTypeSpecificFiles(NewCodenameOneProject.java:89)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder.createProject(CodenameOneProjectBuilder.java:98)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder$1$1.run(CodenameOneProjectBuilder.java:71)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder$1.run(CodenameOneProjectBuilder.java:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$7.run(StartupManagerImpl.java:286)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:259)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$100(StartupManagerImpl.java:52)
	at com.intellij.ide.startup.impl.StartupManagerImpl$4.run(StartupManagerImpl.java:184)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:238)
	at com.intellij.openapi.project.DumbServiceImpl.access$500(DumbServiceImpl.java:53)
	at com.intellij.openapi.project.DumbServiceImpl$IndexUpdateRunnable$1$3.run(DumbServiceImpl.java:420)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by codenameone** [comment]
This was fixed a while back
