### ISSUE TITLE
provision of handling Imagedownloadservice exception by the developer

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1237]
Original [issue 1238](https://code.google.com/p/codenameone/issues/detail?id=1238) created by codenameone on 2014-12-12T10:20:29.000Z:

Issue: When using ImageDownloadService for downloading an Image, an exception is thrown by the system when the image is corrupt. 
java.lang.NullPointerException
    at com.codename1.ui.EncodedImage.getInternal(EncodedImage.java:327)
    at com.codename1.ui.EncodedImage.getInternalImpl(EncodedImage.java:302)
    at com.codename1.ui.EncodedImage.getWidth(EncodedImage.java:470)
    at com.codename1.io.services.ImageDownloadService.postResponse(ImageDownloadService.java:774)
    at com.codename1.io.ConnectionRequest$1.run(ConnectionRequest.java:448)
    at com.codename1.ui.Display.processSerialCalls(Display.java:1090)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1034)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

Adding a provision to handle the exception by the developer will be useful. Currently the exception is thrown on the UI and cannot be handle by the developer.

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
