### ISSUE TITLE
ArrayOutOfBoundException when ConnectionRequestion kill() is called

### ISSUE THREAD

**Issue by jackyy415** [codenameone/CodenameOne#1554]
Hi,
I have a custom error listener and added it to NetworkManager. It will kill the request after several retry. During my testing, ArrayIndexOutOfBoundsException is caught by my custom crash report. It is believe that it happens when kill() is called. This case happens randomly and no exact steps to reproduce it. 

The exception details is shown as below:

[EDT] 1:16:12,217 - Exception: java.lang.ArrayIndexOutOfBoundsException - length=1; index=1
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
   at com.codename1.io.NetworkManager.kill9(NetworkManager.java:637)
   at com.codename1.io.ConnectionRequest.kill(ConnectionRequest.java:918)
   at com.mycompany.myapp.util.MyNetworkErrorListener.actionPerformed(DefaultNetworkErrorListener.java:50)
   at com.codename1.ui.util.EventDispatcher.fireActionSync(EventDispatcher.java:444)
   at com.codename1.ui.util.EventDispatcher.access$100(EventDispatcher.java:41)
   at com.codename1.ui.util.EventDispatcher$CallbackClass.run(EventDispatcher.java:91)
   at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:95)
   at com.codename1.ui.Display.processSerialCalls(Display.java:1144)
   at com.codename1.ui.Display.edtLoopImpl(Display.java:1088)
   at com.codename1.ui.Display.invokeAndBlock(Display.java:1198)
   at com.codename1.ui.Display.invokeAndBlock(Display.java:1233)
   at userclasses.StateMachine.doWork(StateMachine.java:2397)
   at userclasses.StateMachine.onFormMain_ButtonDoWorkAction(StateMachine.java:1850)
   at generated.StateMachineBase.handleComponentAction(StateMachineBase.java:9166)
   at com.codename1.ui.util.UIBuilder$FormListener.actionPerformed(UIBuilder.java:2829)
   at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:338)
   at com.codename1.ui.Button.fireActionEvent(Button.java:395)
   at com.codename1.ui.Button.released(Button.java:426)
   at com.codename1.ui.Button.pointerReleased(Button.java:514)
   at com.codename1.ui.Form.pointerReleased(Form.java:2384)
   at com.codename1.ui.Form.pointerReleased(Form.java:2320)
   at com.codename1.ui.Component.pointerReleased(Component.java:2753)
   at com.codename1.ui.Display.handleEvent(Display.java:1971)
   at com.codename1.ui.Display.edtLoopImpl(Display.java:1060)
   at com.codename1.ui.Display.mainEDTLoop(Display.java:991)
   at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
   at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
   at java.lang.Thread.run(Thread.java:856)

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`STALE_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/STALE_REVIEW.md)).

Reporter says "happens randomly and no exact steps to reproduce it." The relevant code at [`NetworkManager.kill9`](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/io/NetworkManager.java#L577) now bounds-checks via `iter < threadCount`. Without a repro this can't be re-verified, and the symptomatic line numbers no longer match.
