### ISSUE TITLE
ArrayIndexOutOfBoundsException in Form.pointerDragged testing with the simulator

### ISSUE THREAD

**Issue by saeder** [codenameone/CodenameOne#1573]
I have not been able to reproduce it neither on the simulator, nor elsewhere. But it happened. Perhaps the code should be more defensive here:

```
java.lang.ArrayIndexOutOfBoundsException: 0
    at com.codename1.ui.Form.pointerDragged(Form.java:2190)
    at com.codename1.ui.Display.handleEvent(Display.java:2020)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1060)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:991)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by saeder** [comment]
The version used was 3.1

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`STALE_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/STALE_REVIEW.md)).

Reporter: "I have not been able to reproduce it neither on the simulator, nor elsewhere." [`Form.pointerDragged(int[],int[])`](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/Form.java#L3629) has been substantially rewritten since 2015; the line numbers in the stack trace no longer correspond. Untestable.
