### ISSUE TITLE
Shipping app crashing on Android 6 Marshmallow

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1605]
My app works fine on earlier versions of Android.

I am still trying to create a small test case for you but I thought I would describe the problem and include the Android trace in case anything jumps out at you.

I am creating a modal dialog and issue the form.show() method when it crashes, the show does not return.

Here is the trace from the Dalvik Debug Monitor:

=== Debug output===
11-10 12:11:54.648: D/NetlinkSocketObserver(627): NeighborEvent{elapsedMs=78694746, 192.168.1.1, [D850E659B450], RTM_NEWNEIGH, NUD_STALE}
11-10 12:11:56.269: I/System.out(5804): Menu: Database Chooser Selected
11-10 12:11:56.269: I/System.out(5804): databaseChooser: Entry
11-10 12:11:56.269: I/System.out(5804): databaseChooser: Create Chooser Form
11-10 12:11:56.271: I/System.out(5804): ChooserForm: Entry
11-10 12:11:56.275: D/audio_hw_primary(196): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-10 12:11:56.275: I/System.out(5804): databaseChooser: Show Chooser Form
11-10 12:11:56.304: I/Keyboard.Facilitator(3037): onFinishInput()
11-10 12:11:56.308: D/AudioFlinger(196): mixer(0xb41c0000) throttle end: throttle time(7)
11-10 12:11:56.310: D/AndroidRuntime(5804): Shutting down VM
11-10 12:11:56.313: E/AndroidRuntime(5804): FATAL EXCEPTION: main
11-10 12:11:56.313: E/AndroidRuntime(5804): Process: com.readerware.xware.audioware, PID: 5804
11-10 12:11:56.313: E/AndroidRuntime(5804): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.android.internal.view.menu.MenuBuilder.getVisibleItems()' on a null object reference
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:613)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1082)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuBuilder.getNonActionItems(MenuBuilder.java:1114)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuPopupHelper$MenuAdapter.getCount(MenuPopupHelper.java:373)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:821)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6179)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuPopupHelper$MenuAdapter.notifyDataSetChanged(MenuPopupHelper.java:427)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuPopupHelper.updateMenuView(MenuPopupHelper.java:288)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:257)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:976)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:999)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:601)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:939)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:271)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.view.Choreographer.doFrame(Choreographer.java:603)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.os.Handler.handleCallback(Handler.java:739)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.os.Handler.dispatchMessage(Handler.java:95)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.os.Looper.loop(Looper.java:148)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at java.lang.reflect.Method.invoke(Native Method)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-10 12:11:56.313: E/AndroidRuntime(5804):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-10 12:11:56.317: W/ActivityManager(627):   Force finishing activity com.readerware.xware.audioware/.AWMainStub
11-10 12:11:56.338: I/Keyboard.Facilitator(3037): onFinishInput()
11-10 12:11:56.430: I/OpenGLRenderer(627): Initialized EGL, version 1.4
11-10 12:11:56.462: I/art(627): Background partial concurrent mark sweep GC freed 17687(1205KB) AllocSpace objects, 13(260KB) LOS objects, 33% free, 21MB/31MB, paused 5.493ms total 117.309ms
11-10 12:11:56.885: W/ActivityManager(627): Activity pause timeout for ActivityRecord{4f327bd u0 com.readerware.xware.audioware/.AWMainStub t1250 f}
11-10 12:11:57.293: I/ActivityManager(627): Killing 1112:com.android.keychain/1000 (adj 15): empty #17
11-10 12:11:57.577: W/OpenGLRenderer(3152): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-10 12:11:57.577: W/OpenGLRenderer(3152): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
=== End Debug output===

**Comment by mwarnett** [comment]
I now have a sample app to reproduce the crash. In my shipping app this crashes every single time but in this test app it will sometimes work.

To reproduce run the app, display the menu and select the first menu item, Search. The app should crash. The debug output shows the same stack trace as above.

If it works hit the Cancel button. Here when I hit Cancel the dialog closes and the main form is enabled but the menu has gone. See issue 1602. In this case exit the app and run it again.


===Source code===
package com.readerware.xware.test;


import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.List;
import com.codename1.ui.layouts.GridBagConstraints;
import com.codename1.ui.layouts.GridBagLayout;
import com.codename1.ui.layouts.Insets;
import com.codename1.ui.list.DefaultListModel;
import com.codename1.ui.list.ListModel;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.TextArea;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class TWMain {

    private Form current;

    public void init(Object context) {
        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        MyForm form = new MyForm();

        form.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }


    private class MyForm    extends     Form
                            implements  ActionListener {
        public MyForm() {
            super("CodenameOne Test");
            getContentPane().setLayout(new BorderLayout());

            Command backCommand = new Command("Home", 1);
            setBackCommand(backCommand);

            Command searchCommand = new Command("Search", 2);
            addCommand(searchCommand, 0);

            Command command2 = new Command("Menu 2", 3);
            addCommand(command2, 1);

            Command command3 = new Command("Menu 3", 4);
            addCommand(command3, 2);

            Command command4 = new Command("Menu 4", 5);
            addCommand(command4, 3);

            Command command5 = new Command("Menu 5", 6);
            addCommand(command5, 4);

            addCommandListener(this);

            setLayout(new BorderLayout());
            setScrollable(false);

            ListModel listModel = new DefaultListModel();

            for (int i=0; i<100; i++) {
                listModel.addItem("Line " + (i + 1));
            }

            List list = new List();
            list.setScrollVisible(false);
            list.setModel(listModel);
            addComponent(BorderLayout.CENTER, list);
        }


        public void actionPerformed(ActionEvent actionEvent) {
            Command command = actionEvent.getCommand();

            if (command != null) {
                int cmd = command.getId();

                switch (cmd) {
                  case 1:
                    stop();
                    Display.getInstance().exitApplication();
                    return;

                  case 2:
                    ChooserForm chooserForm = new ChooserForm();
                    System.out.println("databaseChooser: Show Chooser Form");
                    chooserForm.show();

                    System.out.println("databaseChooser: Waiting for selection");
                    int choice = chooserForm.getSelection();
                    System.out.println("databaseChooser: Got:" + choice);
                    chooserForm.dispose();

                    if (choice == -1) {
                        return;
                    }
                    
                    return;

                  default:
                    return;
                }
            }
        }
    }


    private class ChooserForm   extends    Dialog
                                implements ActionListener {
        private Command                     _backCommand;

        private Button                      _connectButton;
        private Button                      _importButton;
        private Button                      _listButton;
        private Button                      _cancelButton;

        private int                         _selection;


        public ChooserForm() {
            super("Title");
            System.out.println("ChooserForm: Entry");
            setName("ChooserForm");
            setAutoDispose(false);

            _backCommand = new Command("List");
            setBackCommand(_backCommand);

            GridBagLayout gbl = new GridBagLayout();
            GridBagConstraints gbc = new GridBagConstraints();
            setLayout(gbl);

            TextArea intro = new TextArea("Testing...");
            intro.setRows(3);
            intro.setGrowByContent(false);
            intro.setScrollVisible(false);
            Style style = intro.getStyle();
            ///style.setFgColor(getDialogFgColor(style));
            Style selectedStyle = intro.getSelectedStyle();
            //selectedStyle.setFgColor(getDialogFgColor(style));
            selectedStyle.setBorder(null);
            selectedStyle.setBgColor(style.getBgColor());

            int y = 0;
            int x = 0;
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.1;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(10, 10, 0, 10);
            gbl.setConstraints(intro, gbc);
            addComponent(intro);

            _connectButton = new Button("Connect");
            _connectButton.addActionListener(this);

            y++;
            x = 0;
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(0, 20, 0, 20);
            gbl.setConstraints(_connectButton, gbc);
            addComponent(_connectButton);

            _importButton = new Button("Import");
            _importButton.addActionListener(this);

            y++;
            x = 0;
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(10, 20, 0, 20);
            gbl.setConstraints(_importButton, gbc);
            addComponent(_importButton);

            _listButton = new Button("List");
            _listButton.addActionListener(this);

            y++;
            x = 0;
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(10, 20, 0, 20);
            gbl.setConstraints(_listButton, gbc);
            addComponent(_listButton);

            _cancelButton = new Button("Cancel");
            _cancelButton.addActionListener(this);

            y++;
            x = 0;
            gbc.anchor        = GridBagConstraints.NORTHWEST;
            gbc.gridx         = x;
            gbc.gridy         = y;
            gbc.gridwidth     = GridBagConstraints.REMAINDER;
            gbc.gridheight    = 1;
            gbc.fill          = GridBagConstraints.HORIZONTAL;
            gbc.weightx       = 0.0;
            gbc.weighty       = 0.0;
            gbc.insets        = new Insets(10, 20, 15, 20);
            gbl.setConstraints(_cancelButton, gbc);
            addComponent(_cancelButton);

            _selection = -1;
        }


        public void actionCommand(Command command) {
            if (command == _backCommand) {
                dispose();
                return;
            }
        }


        public void actionPerformed(ActionEvent actionEvent) {
            Component source = (Component) actionEvent.getSource();

            if (source == _connectButton) {
                _selection = 1;
                dispose();
            }
            else if (source == _importButton) {
                _selection = 2;
                dispose();
            }
            else if (source == _listButton) {
                _selection = 3;
                dispose();
            }
            else if (source == _cancelButton) {
                dispose();
            }
        }


        public int getSelection() {
            return _selection;
        }
    }

}

**Comment by chen-fishbein** [comment]
Hi,
I have seen this happening, it appears to be an android bug.
I have no idea how to workaround this.
The stack doesn't coming from our code, not sure what we are doing that causes this.

I have opened a bug for them
https://github.com/android/platform_frameworks_base/issues/87

I suggest you to jump in and say "me too!" it will get their attention

**Comment by mwarnett** [comment]
I have been trying to workaround this issue because at the moment I am dead on Marshmallow.

My App has a system menu with 5 menu items that open a new form or dialog. 4 work, 1 consistently crashes after showing the new form.

The one that crashed is a modal dialog, I tried simplifying the dialog so that all I had was a Cancel button, still crashed.

I changed it to a Form, still crashed.

When I first mentioned the problem with the system menu on Android 6 Shai suggested using the Toolbar instead. To me it didn't feel as native so I stuck with the Android system menu. I tried the Toolbar again and now my app works. When the actionPerformed event comes from the Android menu, the form is displayed and then the app crashes. When the actionPerformed event comes from the Toolbar menu, it works.

So I do have a way around this now.

Thanks,

Martin

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`NEEDS_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/NEEDS_REVIEW.md)).

Android 6.0 (API 23, 2015) is far below modern Android min-SDK (typically 24+). No in-tree repro and the crash trace shows generic Dalvik output. Not actionable.
