### ISSUE TITLE
fatal error not fatal, and no chance to read it.

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1658]
In the process of bringing up a new window on an android build, I noticed one
of your fatal application errors pop-ups that appeared and disappeared in a 
fraction of a second.  I was able to capture it using a screen capture utility,
it said
  "an internal application error occurred:
   java.lang.NullPointerException:" Attempt to invoke virtual method ...."
  OK

The actual error was mine, and is not relevant to this bug report.  This complaint
is that this pop-up was intended to be a stop-the-world error, and probably intended
to be fatal, but in fact it disappeared in a fraction of a second, without the opportunity
to read it or click on the OK box.  And in fact, the application appeared to continue
normally and without error.

I eventually captured this stack trace which shows the environment
in which the error occurred.

[2016/01/28 20:21:16] log request from bridge.MasterPanel (192.168.0.2)
data=[Java cpu=32% Codename1 0The Android Projecthttp://www.android.com/50.0Linuxi6863.10.30-DuOS+] (EDT 21 threads)erro
r in EDT paint
error is : lib.ErrorX: glasspane is null LFrame[x=0 y=0 width=960 height=640, layout = NullLayout, scrollableX = false,
scrollableY = false, components = []] 960x640

*** CN1 log ****
[EDT] 0:2:55,53 - Exception: lib.ErrorX - glasspane is null LFrame[x=0 y=0 width=960 height=640, layout = NullLayout, sc
rollableX = false, scrollableY = false, components = []] 960x640
lib.ErrorX: glasspane is null LFrame[x=0 y=0 width=960 height=640, layout = NullLayout, scrollableX = false, scrollableY
 = false, components = []] 960x640
        at lib.G.Error(Unknown Source)
        at bridge.Frame.setLocalBounds(Unknown Source)
        at lib.NullLayout.layoutContainer(Unknown Source)
        at com.codename1.ui.Container.doLayout(Container.java:1387)
        at com.codename1.ui.Container.layoutContainer(Container.java:1379)
        at com.codename1.ui.Container.doLayout(Container.java:1392)
        at com.codename1.ui.Container.layoutContainer(Container.java:1379)
        at com.codename1.ui.Container.paint(Container.java:1278)
        at bridge.Component.paint(Unknown Source)
        at bridge.Container.paint(Unknown Source)
        at bridge.MasterPanel.paint(Unknown Source)
        at com.codename1.ui.Component.internalPaintImpl(Component.java:1296)
        at com.codename1.ui.Component.paintInternalImpl(Component.java:1270)
        at com.codename1.ui.Component.paintInternal(Component.java:1245)
        at com.codename1.ui.Container.paint(Container.java:1311)
        at com.codename1.ui.Component.internalPaintImpl(Component.java:1296)
        at com.codename1.ui.Component.paintInternalImpl(Component.java:1270)
        at com.codename1.ui.Component.paintInternal(Component.java:1245)
        at com.codename1.ui.Container.paint(Container.java:1311)
        at com.codename1.ui.Form.paint(Form.java:3056)
        at com.codename1.ui.Component.internalPaintImpl(Component.java:1296)
        at com.codename1.ui.Form.internalPaintImpl(Form.java:3066)
        at com.codename1.ui.Component.paintInternalImpl(Component.java:1270)
        at com.codename1.ui.Component.paintInternal(Component.java:1245)
        at com.codename1.ui.Component.paintInternal(Component.java:1213)
        at com.codename1.ui.Component.paintComponent(Component.java:1491)
        at com.codename1.ui.Component.paintComponent(Component.java:1442)
        at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:504)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1072)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:994)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:818)

*** End of CN1 log ****

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`STALE_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/STALE_REVIEW.md)).

2016 simulator transient-error popup. The simulator's error-display logic has been substantially rewritten; report is from "i6863.10.30-DuOS+" (a long-defunct emulator). No concrete repro, original environment is gone.
