### ISSUE TITLE
crash in "GeneralPath.contains"

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1726]
This just started happening in code that's not recently altered.  Also only seen in 
android builds, not in the simulator.

s)Error in Lobby main loop java.lang.ArrayStoreException: Incompatible types: src=float[], dst=double[]
error is : java.lang.ArrayStoreException: Incompatible types: src=float[], dst=double[]
[Thread-181] 0:0:0,0 - Exception: java.lang.ArrayStoreException - Incompatible types: src=float[], dst=double[]
java.lang.ArrayStoreException: Incompatible types: src=float[], dst=double[]
        at java.lang.System.arraycopy(Native Method)
        at com.codename1.ui.geom.GeneralPath$Iterator.currentSegment(GeneralPath.java:332)
        at com.codename1.ui.geom.GeneralPath$ShapeUtil.crossPath(GeneralPath.java:2303)
        at com.codename1.ui.geom.GeneralPath$ShapeUtil.crossShape(GeneralPath.java:2349)
        at com.codename1.ui.geom.GeneralPath.contains(GeneralPath.java:1484)
        at com.codename1.ui.geom.GeneralPath.contains(GeneralPath.java:1491)
        at bridge.Polygon.contains(Unknown Source)
        at online.common.lobbyCanvas.inPlayToken(Unknown Source)
        at online.common.lobbyCanvas.getHighlightedItem(Unknown Source)
        at online.common.lobbyCanvas.MouseMotion(Unknown Source)
        at online.common.MouseManager.performMouse(Unknown Source)
        at online.common.exCanvas.ViewerRun(Unknown Source)
        at online.common.lobbyCanvas.ViewerRun(Unknown Source)
        at online.common.commonPanel.runStep(Unknown Source)
        at online.common.commonLobby.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)

 "

**Comment by ddyer0** [comment]
I traced this down the rabbit hole in my app, and discovered that the culprit is likely at this point,
and that at that point, "pointIndex" is 0, so the type index is probably meaningless and the arraycopy
would not be copying anything.

        public int currentSegment(double[] coords) {
            if (isDone()) {
                // awt.4B=Iterator out of bounds
                throw new IndexOutOfBoundsException("Path done"); //$NON-NLS-1$
            }
            int type = p.types[typeIndex];
            int count = GeneralPath.pointShift[type];
            System.arraycopy(p.points, pointIndex, coords, 0, count);

A general comment about this code - the values of x,y (for "contains") seem to bounce frequently
between ints, floats, and doubles as you traverse from one part of the algorithm to another.
I don't see how this can possible be the right thing or reliable.
