### ISSUE TITLE
EDT Violations when using SpanLabel in InfiniteContainer

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#1789]
The below code leads to EDT violations as listed in the stack trace below the code:

``` java
     Form hi = new Form("Hi World");
        hi.setScrollable(false);
        InfiniteContainer cl = new InfiniteContainer() {
            @Override
            public Component[] fetchComponents(int index, int amount) {

                Component[] comps = new Component[amount];
                for (int i = 0, size = amount; i < size; i++) {
                    comps[i] = new SpanLabel("Very long text that is spanning multiple lines and which violates the EDT. Very long text that is spanning multiple lines and which violates the EDT");
                }
                return comps;
            }
        };
        hi.addComponent(cl);
        hi.show();
```

here's the stack trace:

```
EDT violation detected!
com.codename1.impl.javase.JavaSEPort$EDTViolation: EDT Violation Stack!
    at com.codename1.impl.javase.JavaSEPort.checkEDT(JavaSEPort.java:405)
    at com.codename1.impl.javase.JavaSEPort.isNativeInputSupported(JavaSEPort.java:2810)
    at com.codename1.ui.Display.isNativeInputSupported(Display.java:2431)
    at com.codename1.ui.TextArea.setText(TextArea.java:427)
    at com.codename1.ui.TextArea.<init>(TextArea.java:351)
    at com.codename1.ui.TextArea.<init>(TextArea.java:305)
    at com.codename1.components.SpanLabel.<init>(SpanLabel.java:70)
    at com.mycompany.myapp.MyApplication$1.fetchComponents(MyApplication.java:35)
    at com.codename1.ui.InfiniteContainer$2$1.run(InfiniteContainer.java:131)
    at com.codename1.ui.Display$1.run(Display.java:803)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by shyamsth** [comment]
is this solved ?:
I have replaced with TextArea and there is still the same problem , how can it be solved?

**Comment by codenameone** [comment]
Yes this was solved a while back
