### ISSUE TITLE
Android Physical Back button Different behavior than simulator

### ISSUE THREAD

**Issue by chadelofson** [codenameone/CodenameOne#1826]
I am involved in an app where the physical back button on android closes the app when we have a container in the south border of our layout.  When that container is open, we get the original Back Command and set a new one.  When we are done with that main container, we put the original back command on the form.

In the container, we have a button that brings up a different container.  This new container replaces the original container in the south border of our layout.  This new container will store the Back command of the previous container and create a new Back command.  In the new back command, we put the previous command back from the other container and invoke a callback.  The previous container is put back when we are done with this container.

In the simulator the workflow works accordingly:
1.  First Container in the South border comes up and stores back command with a new one.  The old one is stored for when we are done with the container.

2.  A button is hit and the new container replaces the container in step 1.  The back command is stored and replaced by a new back command.

When I hit the physical back button in step 1 it hides the container and returns to the main form.

When I go to step 2 and hit the back button, I expect it to return to the previous container.  In Android it goes back to the main form.  Then when I bring up the container in step 1 and hit the back button it exits the app.  In the simulator it goes back to the previous container as I expected it to.

**Comment by shannah** [comment]
I have found that, under certain conditions, the Android back command is fired twice for a single press of the back button.  I added a stack trace in MenuBar just before the command is executed to show where it is coming from.  The following two stack traces result from the same single back button press.

~~~~
Back command received in MenuBar.keyReleased Back true
07-07 08:25:29.435 23569-23600/ca.weblite.pander I/System.out: About to call actionPerformed on command Back
07-07 08:25:29.435 23569-23600/ca.weblite.pander W/System.err: java.lang.RuntimeException
07-07 08:25:29.435 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.MenuBar.keyReleased(MenuBar.java:1422)
07-07 08:25:29.435 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.SideMenuBar.keyReleased(SideMenuBar.java:682)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Form.keyReleased(Form.java:2161)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.handleEvent(Display.java:1975)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.edtLoopImpl(Display.java:1067)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.mainEDTLoop(Display.java:996)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
07-07 08:25:29.436 23569-23600/ca.weblite.pander W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-07 08:25:29.476 23569-23600/ca.weblite.pander I/System.out: Back command received in MenuBar.keyReleased Back true
07-07 08:25:29.476 23569-23600/ca.weblite.pander I/System.out: About to call actionPerformed on command Back
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err: java.lang.RuntimeException
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.MenuBar.keyReleased(MenuBar.java:1422)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.SideMenuBar.keyReleased(SideMenuBar.java:682)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Form.keyReleased(Form.java:2161)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.handleEvent(Display.java:1975)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.edtLoopImpl(Display.java:1067)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.invokeAndBlock(Display.java:1205)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.invokeAndBlock(Display.java:1243)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.AnimationManager.addAnimationAndBlock(AnimationManager.java:105)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Container.replaceComponents(Container.java:769)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Container.replaceAndWait(Container.java:661)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at ca.weblite.pander.views.RestaurantDetailsPanel.lambda$null$19(RestaurantDetailsPanel.java:271)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at ca.weblite.pander.views.RestaurantDetailsPanel.access$lambda$5(RestaurantDetailsPanel.java)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at ca.weblite.pander.views.RestaurantDetailsPanel$$Lambda$6.run(Unknown Source)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at ca.weblite.pander.views.UpdateWaitTimeDialog$1.actionPerformed(UpdateWaitTimeDialog.java:63)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.MenuBar.keyReleased(MenuBar.java:1423)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.SideMenuBar.keyReleased(SideMenuBar.java:682)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Form.keyReleased(Form.java:2161)
07-07 08:25:29.476 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.handleEvent(Display.java:1975)
07-07 08:25:29.477 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.edtLoopImpl(Display.java:1067)
07-07 08:25:29.477 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.Display.mainEDTLoop(Display.java:996)
07-07 08:25:29.477 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
07-07 08:25:29.483 23569-23600/ca.weblite.pander W/System.err:     at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
07-07 08:25:29.483 23569-23600/ca.weblite.pander W/System.err:     at java.lang.Thread.run(Thread.java:818)
~~~~

**Comment by shannah** [comment]
There appears to be a problem with the inputStackPointer when invokeAndBlock is called within handleEvent().

**Comment by chadelofson** [comment]
The phone that I am using is the HTC One.  I will see if I can find anything out.  I also have a Galaxy S4.   I will try the app on that one as well.

**Comment by shannah** [comment]
No need.  I see the issue.  The problem is (big surprise) with both the main view and the peer component view capturing the back button press and passing it to CN1.  It will require a fix in the Android port.

**Comment by chadelofson** [comment]
Ah ok, yeah it did the same thing in the S4.

**Comment by chadelofson** [comment]
Where is that located in the CN1 source?

**Comment by shannah** [comment]
Fixed.  https://github.com/codenameone/CodenameOne/commit/196a931167ccb70c40758d5460f994e547f3bd97

Will be on the build server for next update.
