### ISSUE TITLE
theme.res not found

### ISSUE THREAD

**Issue by thesourav123** [codenameone/CodenameOne#1894]
0
down vote
favorite
	

I am trying to create a Codenameone Application on IntelliJIDEA IDE. I have installed the codenameone plugin and created a CodeNameOne Application. When i run that application it gives an error java.io.IOException: /theme.res not found

Using:

IntelliJIDEA Version: IntellijIDEA 2016.2.4

JDK Version: jdk1.8

Here is the complete error log

Sep 19, 2016 10:44:21 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs  at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
java.io.IOException: /theme.res not found
at com.codename1.ui.util.Resources.open(Resources.java:736)
at com.codename1.ui.util.Resources.openLayered(Resources.java:700)
at com.codename1.ui.util.Resources.openLayered(Resources.java:664)
at com.codename1.ui.plaf.UIManager.initFirstTheme(UIManager.java:1534)
at com.mycompany.myapp.MyApplication.init(MyApplication.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.codename1.impl.javase.Executor$1$1.run(Executor.java:81)
at com.codename1.ui.Display.processSerialCalls(Display.java:1151)
at com.codename1.ui.Display.mainEDTLoop(Display.java:968)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.NullPointerException
at com.mycompany.myapp.MyApplication.start(MyApplication.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.codename1.impl.javase.Executor$1$1.run(Executor.java:106)
at com.codename1.ui.Display.processSerialCalls(Display.java:1151)
at com.codename1.ui.Display.mainEDTLoop(Display.java:968)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

Process finished with exit code 1

**Comment by codenameone** [comment]
This was triggered by picking the Android SDK instead of the Java SDK when creating the project.
