### ISSUE TITLE
GUIBuilder: Dragging onto other component makes it disappear

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1922]
Place Button in south + tabs in center of border layout container
Drag Container on top of button to occupy the south area.
Container is now in south area, button disappeared

**Comment by chen-fishbein** [comment]
What would you expect to happen in this situation?

**Comment by codenameone** [comment]
I would expect either the button to move to a new position or the container to appear some other place within the layout.  One thing I would never expect is a component disappearing...

I ran into this because I no longer have "enclose with" so I was trying to wrap a button I already added with a new Container. This proved to be pretty difficult...

**Comment by codenameone** [comment]
This now triggered a freeze in the GUI builder:

ant -f /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE -Dnb.internal.action.name=run run
init:
Deleting: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
CodenameOne.init:
CodenameOne.deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
Factory.init:
Factory.deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
Factory.compile:
Factory.jar:
CodenameOne.initEnv:
Init env executing with cn1env = true for ../../CodenameOne/GUIBuilder/src
CodenameOne.stamp:
Stamp executing with 20161024
Updating property file: /Users/shai/dev/cn1/CodenameOneDesigner/src/version.properties
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/src/version.properties
Updating property file: /Users/shai/dev/CodenameOne/NBPlugin/CodenameOnePlugin/src/version.properties
Updating property file: /Users/shai/dev/CodenameOne/BuildClient/src/version.properties
Compiling 6 source files to /Users/shai/dev/cn1/CodenameOne/build/classes
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: /Users/shai/dev/cn1/CodenameOne/src/com/codename1/processing/HashtableContent.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/shai/dev/cn1/CodenameOne/src/com/codename1/processing/HashtableContent.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
CodenameOne.compile:
Building jar: /Users/shai/dev/cn1/CodenameOne/dist/CodenameOne.jar
CodenameOne.jar:
No GUI Entries available
CodenameOneSettings.init:
CodenameOneSettings.deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
JavaSE.init:
JavaSE.deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
JavaSE.build-skins:
JavaSE.init-skins:
DEPRECATED - The copydir task is deprecated.  Use copy instead.
Copying 1 file to /Users/shai/dev/cn1/Ports/JavaSE/build/classes
Expanding: /Users/shai/dev/cn1-binaries/javase/sqlite-jdbc-3.7.15-M1.jar into /Users/shai/dev/cn1/Ports/JavaSE/build/classes
Expanding: /Users/shai/dev/cn1-binaries/javase/Filters.jar into /Users/shai/dev/cn1/Ports/JavaSE/build/classes
JavaSE.compile:
Building jar: /Users/shai/dev/cn1/Ports/JavaSE/dist/JavaSE.jar
To run this application from the command line without Ant, try:
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java -cp /Users/shai/dev/cn1-binaries/javase/sqlitejdbc-v056.jar:/Users/shai/dev/cn1/CodenameOne/dist/CodenameOne.jar:/Users/shai/dev/cn1-binaries/jfxrt.jar:/Users/shai/dev/cn1-binaries/javase/Filters.jar:/Users/shai/dev/cn1/Ports/JavaSE/dist/JavaSE.jar com.codename1.impl.javase.Simulator
JavaSE.jar:
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
CodenameOneSettings.compile:
Copying 1 file to /Users/shai/dev/CodenameOne/CodenameOneSettings/build
Not copying library /Users/shai/dev/CodenameOne/CodenameOneSettings/override , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/CodenameOneSettings/lib/impl/cls , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/CodenameOneSettings/lib/impl/stubs , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/CodenameOneSettings/native/internal_tmp , it's a directory.
Copy libraries to /Users/shai/dev/CodenameOne/CodenameOneSettings/dist/lib.
To run this application from the command line without Ant, try:
java -jar "/Users/shai/dev/CodenameOne/CodenameOneSettings/dist/CodenameOneSettings.jar"
CodenameOneSettings.jar:
No GUI Entries available
GUIBuilder.init:
GUIBuilder.deps-jar:
Updating property file: /Users/shai/dev/CodenameOne/GUIBuilder/GUIBuilderSE/build/built-jar.properties
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
Copying 1 file to /Users/shai/dev/CodenameOne/GUIBuilder/build/classes
GUIBuilder.compile:
Copying 1 file to /Users/shai/dev/CodenameOne/GUIBuilder/build
Not copying library /Users/shai/dev/CodenameOne/GUIBuilder/override , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/GUIBuilder/lib/impl/cls , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/GUIBuilder/lib/impl/stubs , it's a directory.
Not copying library /Users/shai/dev/CodenameOne/GUIBuilder/native/internal_tmp , it's a directory.
Copy libraries to /Users/shai/dev/CodenameOne/GUIBuilder/dist/lib.
Building jar: /Users/shai/dev/CodenameOne/GUIBuilder/dist/GUIBuilder.jar
To run this application from the command line without Ant, try:
java -jar "/Users/shai/dev/CodenameOne/GUIBuilder/dist/GUIBuilder.jar"
GUIBuilder.jar:
compile:
run:
Connector: file:/Users/shai/.guiBuilder/guibuilder.input
[invokeAndBlock1] 0:0:0,0 - Codename One revisions: b022db889f304ae2a2f08f33a2586c57a5cd59c6
2145

[invokeAndBlock1] 0:0:0,0 - Running: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java[/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java, -jar, /Users/shai/.codenameone/designer_1.jar, -mimg, /Users/shai/dev/PheonixUI/src/theme.res, hd, /Users/shai/dev/PheonixUI/psd/resources/label_round-selected.png]
[invokeAndBlock1] 0:0:15,471 - Process completed with: 0
[invokeAndBlock1] 0:6:27,663 - Running: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java[/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java, -jar, /Users/shai/.codenameone/designer_1.jar, -mimg, /Users/shai/dev/PheonixUI/src/theme.res, hd, /Users/shai/dev/PheonixUI/psd/resources/label_round-selected.png]
[invokeAndBlock1] 0:6:30,498 - Process completed with: 0
2016-10-24 13:42:39.483 java[36848:5343683] plugin com.adobe.accmac.ACCFinderSync invalidated
[invokeAndBlock1] 0:6:45,759 - Running: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java[/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java, -jar, /Users/shai/.codenameone/designer_1.jar, -mimg, /Users/shai/dev/PheonixUI/src/theme.res, hd, /Users/shai/dev/PheonixUI/psd/resources/label_round.png]
[invokeAndBlock1] 0:6:48,348 - Process completed with: 0
[AWT-EventQueue-0] 2:43:35,265 - Invalid undo operation for com.codename1.apps.guibuilder.DragContainer$3
After undo state: <?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="BoxLayout" boxLayoutAxis="Y"  title="InboxForm" name="InboxForm">
  <component type="Container" layout="BorderLayout" borderLayoutAbsoluteCenter="false"  name="Container_1">
    <component type="Label" text="" name="Label_1">
      <layoutConstraint value="West" />
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="Y"  name="Container_2">
      <layoutConstraint value="Center" />
      <component type="Label" text="Label" name="Label_4">
      </component>
      <component type="Label" text="Label" name="Label_3">
      </component>
      <component type="TextArea" text="TextArea" name="Text_Area_1">
      </component>
    </component>
  </component>
</component>


Actual stack state: <?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="BoxLayout" boxLayoutAxis="Y"  title="InboxForm" name="InboxForm">
  <component type="Container" layout="BorderLayout" borderLayoutAbsoluteCenter="false"  name="Container_1">
    <component type="Label" text="Label" name="Label_2">
      <layoutConstraint value="East" />
    </component>
    <component type="Label" text="" name="Label_1">
      <layoutConstraint value="West" />
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="Y"  name="Container_2">
      <layoutConstraint value="Center" />
      <component type="Label" text="Label" name="Label_4">
      </component>
      <component type="Label" text="Label" name="Label_3">
      </component>
      <component type="TextArea" text="TextArea" name="Text_Area_1">
      </component>
    </component>
  </component>
</component>

2016-10-24 16:26:36
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"TimerQueue" #117 daemon prio=5 os_prio=31 tid=0x00007fdc67272000 nid=0x86e3 waiting on condition [0x0000700001e79000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000078d3078a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
	at javax.swing.TimerQueue.run(TimerQueue.java:171)
	at java.lang.Thread.run(Thread.java:745)

"Thread-28" #113 daemon prio=5 os_prio=31 tid=0x00007fdc67a9e800 nid=0x8417 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Prism Font Disposer" #57 daemon prio=10 os_prio=31 tid=0x00007fdc6230e000 nid=0x1c107 in Object.wait() [0x00007000028a0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c1914358> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.sun.javafx.font.Disposer.run(Disposer.java:93)
	at java.lang.Thread.run(Thread.java:745)

"Watchdog-Timer-1" #33 daemon prio=5 os_prio=31 tid=0x00007fdc63ba0800 nid=0x1850f waiting on condition [0x0000700002494000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c000b240> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"AWT-EventQueue-0" #27 prio=6 os_prio=31 tid=0x00007fdc63a6b000 nid=0xec03 in Object.wait() [0x0000700001d73000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.codename1.impl.javase.JavaSEPort$73.run(JavaSEPort.java:7664)
	- locked <0x0000000776dda9f0> (a [Lcom.codename1.impl.javase.SEBrowserComponent;)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1222)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1242)
	at com.codename1.impl.javase.JavaSEPort.createBrowserComponent(JavaSEPort.java:7657)
	at com.codename1.ui.BrowserComponent.<init>(BrowserComponent.java:99)
	at com.codename1.components.WebBrowser.<init>(WebBrowser.java:81)
	at com.codename1.components.WebBrowser.<init>(WebBrowser.java:69)
	at com.codename1.apps.guibuilder.GUIBuilderForm.<init>(GUIBuilderForm.java:139)
	at com.codename1.apps.guibuilder.UndoableEditQueue.restoreOnSeriousFailure(UndoableEditQueue.java:117)
	at com.codename1.apps.guibuilder.UndoableEditQueue.undo(UndoableEditQueue.java:86)
	at com.codename1.apps.guibuilder.GUIBuilder.undo(GUIBuilder.java:129)
	at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$4.actionPerformed(GUIBuilderMain.java:319)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"Disposer" #26 daemon prio=10 os_prio=31 tid=0x00007fdc62a9e800 nid=0xea03 in Object.wait() [0x0000700001c73000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c00113c0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c00113c0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.sun.webkit.Disposer.run(Disposer.java:90)
	at java.lang.Thread.run(Thread.java:745)

"invokeAndBlock1" #24 prio=6 os_prio=31 tid=0x00007fdc62a68800 nid=0xe703 in Object.wait() [0x0000700001aed000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:132)
	- locked <0x00000006c0019408> (a java.lang.Object)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

"Thread-5" #23 daemon prio=5 os_prio=31 tid=0x00007fdc62a68000 nid=0xe503 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AWT-Shutdown" #22 prio=5 os_prio=31 tid=0x00007fdc622d2800 nid=0xde03 in Object.wait() [0x0000700001967000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	- locked <0x00000006c00116f0> (a java.lang.Object)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	at java.lang.Thread.run(Thread.java:745)

"Thread-4" #21 daemon prio=6 os_prio=31 tid=0x00007fdc622d1800 nid=0xdc07 waiting on condition [0x0000700001458000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0361cc0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:108)

"QuantumRenderer-0" #19 daemon prio=6 os_prio=31 tid=0x00007fdc638b7800 nid=0xa93f waiting on condition [0x00007000012d2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0011a68> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)

"DestroyJavaVM" #17 prio=5 os_prio=31 tid=0x00007fdc629de000 nid=0x1703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"EDT" #16 prio=6 os_prio=31 tid=0x00007fdc6317f000 nid=0xd817 in Object.wait() [0x0000700001864000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1313)
	- locked <0x0000000776d12818> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.codename1.impl.javase.JavaSEPort$C.blit(JavaSEPort.java:788)
	at com.codename1.impl.javase.JavaSEPort$C.blit(JavaSEPort.java:796)
	at com.codename1.impl.javase.JavaSEPort.flushGraphics(JavaSEPort.java:3760)
	at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:580)
	at com.codename1.impl.javase.JavaSEPort.paintDirty(JavaSEPort.java:1290)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1075)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:997)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

"Timer-0" #14 daemon prio=5 os_prio=31 tid=0x00007fdc629bf000 nid=0xd507 in Object.wait() [0x0000700001761000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x00000006c0011d10> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Java2D Disposer" #13 daemon prio=10 os_prio=31 tid=0x00007fdc63097000 nid=0xd303 in Object.wait() [0x000070000165e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0011ed8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:745)

"Java2D Queue Flusher" #12 daemon prio=10 os_prio=31 tid=0x00007fdc639b3800 nid=0xc407 in Object.wait() [0x000070000155b000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)
	- locked <0x00000006c0011f18> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)

"JavaFX Application Thread" #9 daemon prio=5 os_prio=31 tid=0x00007fdc6302d000 nid=0xa0b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007fdc63858000 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fdc6204a800 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fdc63849000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fdc63000000 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fdc62047000 nid=0x360f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fdc63006800 nid=0x3003 in Object.wait() [0x000070000092e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c00bc9c0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fdc62045000 nid=0x2e03 in Object.wait() [0x000070000082b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000006c00bcbd8> (a java.lang.ref.Reference$Lock)

"VM Thread" os_prio=31 tid=0x00007fdc6281d000 nid=0x2c03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fdc63800800 nid=0x2403 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fdc63801000 nid=0x2603 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fdc63808000 nid=0x2803 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fdc63809000 nid=0x2a03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fdc62045800 nid=0x4b03 waiting on condition 

JNI global references: 6080

Heap
 PSYoungGen      total 544768K, used 240028K [0x000000076ab00000, 0x000000078e080000, 0x00000007c0000000)
  eden space 530944K, 44% used [0x000000076ab00000,0x0000000779315c18,0x000000078b180000)
  from space 13824K, 17% used [0x000000078d300000,0x000000078d551750,0x000000078e080000)
  to   space 24064K, 0% used [0x000000078b180000,0x000000078b180000,0x000000078c900000)
 ParOldGen       total 118784K, used 40988K [0x00000006c0000000, 0x00000006c7400000, 0x000000076ab00000)
  object space 118784K, 34% used [0x00000006c0000000,0x00000006c2807280,0x00000006c7400000)
 Metaspace       used 34013K, capacity 35018K, committed 35328K, reserved 1079296K
  class space    used 4314K, capacity 4539K, committed 4608K, reserved 1048576K

**Comment by codenameone** [comment]
FYI I didn't create a browser component but it seems related to changes recently made related to it. I specifically disabled the browser component in the GUI builder due to some complexities related to threads in the past...

**Comment by chen-fishbein** [comment]
It seems like the undo and redo were on the swing EDT and weren't dispatched to the CN1 EDT which causes some issues and a deadlock with the browser component.
I have a fix for the freeze issue, leaving this open since this issue is about something else.
