### ISSUE TITLE
Material icons created with prior GUI builder versions no longer run

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1950]
````
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.codename1.build.client.GenerateGuiSources.addImageProperty(GenerateGuiSources.java:846)
	at com.codename1.build.client.GenerateGuiSources.updateProperties(GenerateGuiSources.java:477)
	at com.codename1.build.client.GenerateGuiSources.constructComponentsHierarchy(GenerateGuiSources.java:426)
	at com.codename1.build.client.GenerateGuiSources.constructComponentsHierarchy(GenerateGuiSources.java:421)
	at com.codename1.build.client.GenerateGuiSources.constructComponentsHierarchy(GenerateGuiSources.java:421)
	at com.codename1.build.client.GenerateGuiSources.generateGuiSource(GenerateGuiSources.java:298)
	at com.codename1.build.client.GenerateGuiSources.generateGuiSource(GenerateGuiSources.java:231)
	at com.codename1.build.client.GenerateGuiSources.execute(GenerateGuiSources.java:202)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
````

This can be seen with the Phoenix demo source. I'm assigning this higher priority as I'd like to integrate Phoenix and other demos into the IDE and this is the one blocker.

**Comment by codenameone** [comment]
This also blocks opening some forms in the builder for the same reason: 

````
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.codename1.apps.guibuilder.GuiPersister.getImage(GuiPersister.java:112)
[EDT] 0:0:0,1 - Codename One revisions: 5740951e2f5640e32a60c5bf3d85dfa02237928b
2188

	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:140)
[EDT] 0:0:0,3 - Gui Builder Exception in version 1.17
[EDT] 0:0:0,3 - OS mac
[EDT] 0:0:0,3 - Error java.lang.NumberFormatException: For input string: ""
[EDT] 0:0:0,4 - Null current form!!!
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
[EDT] 0:0:0,4 - Exception: java.lang.NumberFormatException - For input string: ""
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
	at com.codename1.apps.guibuilder.GuiPersister.load(GuiPersister.java:80)
	at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:71)
	at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
	at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.codename1.apps.guibuilder.GuiPersister.getImage(GuiPersister.java:112)
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:140)
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
	at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:221)
	at com.codename1.apps.guibuilder.GuiPersister.load(GuiPersister.java:80)
	at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:71)
	at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
	at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
````

**Comment by codenameone** [comment]
@chen-fishbein I'll try to fix this myself as I'd like the release to be today.

**Comment by codenameone** [comment]
This is fixed in SVN
