### ISSUE TITLE
Debugger in IntelliJ doesn't work

### ISSUE THREAD

**Issue by SwingGuy1024** [codenameone/CodenameOne#1983]
When I try to launch the debugger in IntelliJ, nothing happens. It generates an exception with a message of null and this stack trace:

`java.lang.UnsupportedOperationException
	at com.codename1.plugin.intellij.run.CodenameOneRunConfiguration.isAlternativeJrePathEnabled(CodenameOneRunConfiguration.java:246)
	at com.intellij.debugger.impl.AlternativeJreClassFinder.getAlternativeJre(AlternativeJreClassFinder.java:75)
	at com.intellij.debugger.DefaultDebugEnvironment.getAlternativeJre(DefaultDebugEnvironment.java:97)
	at com.intellij.debugger.impl.DebuggerSession.<init>(DebuggerSession.java:222)
	at com.intellij.debugger.impl.DebuggerSession.create(DebuggerSession.java:201)
	at com.intellij.debugger.impl.DebuggerManagerImpl.attachVirtualMachine(DebuggerManagerImpl.java:224)
	at com.intellij.debugger.impl.GenericDebuggerRunner.attachVirtualMachine(GenericDebuggerRunner.java:113)
	at com.intellij.debugger.impl.GenericDebuggerRunner.attachVirtualMachine(GenericDebuggerRunner.java:103)
	at com.intellij.debugger.impl.GenericDebuggerRunner.createContentDescriptor(GenericDebuggerRunner.java:84)
	at com.intellij.debugger.impl.GenericDebuggerRunner.doExecute(GenericDebuggerRunner.java:61)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:381)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:76)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by codenameone** [comment]
Not sure why you are seeing this as it works for me during debugging so something in the configuration must be different.

Regardless I see something that could be a problem and we'll fix it for the next update of the plugin

**Comment by codenameone** [comment]
Already fixed in plugin SVN
