### ISSUE TITLE
UWP Desktop build network error

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2056]
My app connects to a computer on a local network to retrieve data. I use a ConnectionRequest with a URL like "http://192.168.1.105:9002/Query?REQ=PING". This works fine on Android, iOS, the simulator and even on a Windows Mobile phone using the UWP mobile app.

However on the UWP desktop app I cannot connect. I get the following exception:

> 

[EDT] 0:0:0,15 - Codename One revisions: f5f70630a46eced2d7416801e17d7e121224affd
2341

[EDT] 0:0:0,70 - Log.getUniqueDeviceId()->6004190561435648
[EDT] 0:0:0,77 - RWMain - init
[EDT] 0:0:0,117 - RW - Books 3.54
[EDT] 0:0:0,122 - RWMain - start
[EDT] 0:0:0,127 - Platform=win
[EDT] 0:0:0,131 - _osVer=3.54
[EDT] 0:0:0,136 - osMajVer=3
[EDT] 0:0:0,237 - Database open failure: RWareDB.rw3 not found
[Thread-1] 0:0:7,622 - Connection to 192.168.1.105...
[Thread-1] 0:0:7,626 - SENT: PING
[Network Thread] 0:0:7,821 - Exception: java.io.IOException - An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at UWPApp.IKVMReflectionHelper.getCurrentStackTrace()
   at java.lang.ThrowableHelper.getCurrentStackTrace()
   at java.lang.Throwable..ctor(String message)
   at java.lang.Exception..ctor(String message)
   at java.io.IOException..ctor(String message)
   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()
   at com.codename1.impl.CodenameOneThread.run()
   at com.codename1.impl.SilverlightImplementation.CodenameOneUWPThread.run()
   at java.lang.Thread.threadProc2()
   at java.lang.Thread.threadProc()
   at java.lang.Thread.1.Invoke()
   at com.codename1.impl.NativeThreadImpl.<>c__DisplayClass6_0.<init>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Originating from:
Message=An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()[EDT] 0:0:9,382 - Database open failure: RWareDB.rw3 not found
-2] 0:0:25,33 - SENT: PING
[Network Thread] 0:0:25,46 - Exception: java.io.IOException - An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at UWPApp.IKVMReflectionHelper.getCurrentStackTrace()
   at java.lang.ThrowableHelper.getCurrentStackTrace()
   at java.lang.Throwable..ctor(String message)
   at java.lang.Exception..ctor(String message)
   at java.io.IOException..ctor(String message)
   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()
   at com.codename1.impl.CodenameOneThread.run()
   at com.codename1.impl.SilverlightImplementation.CodenameOneUWPThread.run()
   at java.lang.Thread.threadProc2()
   at java.lang.Thread.threadProc()
   at java.lang.Thread.1.Invoke()
   at com.codename1.impl.NativeThreadImpl.<>c__DisplayClass6_0.<init>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Originating from:
Message=An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()[EDT] 0:0:28,581 - Database open failure: RWareDB.rw3 not found
,315 - RWMain - stop
[EDT] 0:3:26,352 - Exiting...
[EDT] 0:3:26,367 - Exiting...

**Comment by shannah** [comment]
In your case, is the UWP desktop app running on the same computer as the Simulator.  I.e. Same computer running simulator works, but fails in UWP build?

**Comment by mwarnett** [comment]
No.

I am testing on a Microsoft Surface Book. I don't have my development environment installed on this machine, no Netbeans, no plugin.

**Comment by shannah** [comment]
Can you connect to that URL from a web browser running on that Surface book?  (I'm trying to rule out network issues to the machine itself).

**Comment by mwarnett** [comment]
Yes I can, I can connect and get a response in my browser.

My standard desktop client is a Java/Swing app. I can also run that on the Microsoft Surface Books and it connects to the same server.

**Comment by shannah** [comment]
A few things that would help me out:

1. Is the "Database open failure: RWareDB.rw3 not found" error important?  (Do you get that on the other platforms that work)?
2. Catch the connection error and try to find out more information about the response.  E.g. response code.
3. Post the response you get in simulator (using the network monitor).

**Comment by mwarnett** [comment]
The database open error is normal. What is happening in this scenario is that the database was not found. The user then connects to the server to retrieve the database. Here is the log from the simulator:

[EDT] 0:0:0,0 - Codename One revisions: f5f70630a46eced2d7416801e17d7e121224affd
2341

[EDT] 0:0:0,5 - Log.getUniqueDeviceId()->15713299
[EDT] 0:0:0,8 - RWMain - init
[EDT] 0:0:0,258 - RW - Books 3.54
[EDT] 0:0:0,269 - RWMain - start
[EDT] 0:0:0,278 - Platform=win
[EDT] 0:0:0,278 - _osVer=7
[EDT] 0:0:0,278 - osMajVer=7
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[EDT] 0:0:0,439 - Database open failure: RWareDB.rw3 not found
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[EDT] 0:0:0,439 - Database open failure: RWareDB.rw3 not found
[Thread-5] 0:0:19,81 - Connection to 192.168.1.105...
[Thread-5] 0:0:19,106 - SENT: PING
[Thread-5] 0:0:19,210 - RECEIVED: OK
[Thread-5] 0:0:19,219 - SENT: QDBNAME=rw
[Thread-5] 0:0:19,249 - RECEIVED: Books.rw3.data
[Thread-5] 0:0:19,273 - SENT: QDBDATE
[Thread-5] 0:0:19,303 - RECEIVED: 2017-03-16
[Thread-5] 0:0:19,303 - SENT: QDEVRES=6
[Thread-5] 0:0:19,333 - RECEIVED: 128
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[Thread-5] 0:0:19,333 - SENT: GETUCOL
[Thread-5] 0:0:19,371 - RECEIVED: User 1, User 2, User 3, User 4, User 5, User 6, User 7, User 8, User 9, User 10
[Thread-5] 0:0:19,375 - SENT: GETDB
[Thread-5] 0:0:19,435 - RECEIVED: OK=2559
[Thread-5] 0:0:19,435 - SENT: GETROW
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[Thread-5] 0:0:19,823 - SENT: GETROWS
[Thread-5] 0:0:20,604 - SENT: GETROWS
[Thread-5] 0:0:21,355 - SENT: GETROWS
[Thread-5] 0:0:21,617 - SENT: GETROWS
[Thread-5] 0:0:21,865 - SENT: GETROWS
[Thread-5] 0:0:22,116 - SENT: GETROWS
[Thread-5] 0:0:22,575 - SENT: GETROWS
[Thread-5] 0:0:22,982 - SENT: GETROWS
[Thread-5] 0:0:23,400 - SENT: GETROWS
[Thread-5] 0:0:23,909 - SENT: GETROWS
[Thread-5] 0:0:24,292 - SENT: GETROWS
[Thread-5] 0:0:24,921 - SENT: GETROWS
[Thread-5] 0:0:25,679 - SENT: GETROWS
[Thread-5] 0:0:26,91 - SENT: GETROWS
[Thread-5] 0:0:26,727 - SENT: GETROWS
[Thread-5] 0:0:27,79 - SENT: GETROWS
[Thread-5] 0:0:27,634 - SENT: GETROWS
[Thread-5] 0:0:28,73 - SENT: GETROWS
[Thread-5] 0:0:28,353 - SENT: GETROWS
[Thread-5] 0:0:28,724 - SENT: GETROWS
[Thread-5] 0:0:29,158 - SENT: GETROWS
[Thread-5] 0:0:29,526 - SENT: GETROWS
[Thread-5] 0:0:29,975 - SENT: GETROWS
[Thread-5] 0:0:30,425 - SENT: GETROWS
[Thread-5] 0:0:30,905 - SENT: GETROWS
[Thread-5] 0:0:31,368 - SENT: GETROWS
[Thread-5] 0:0:32,210 - SENT: GETROWS
[Thread-5] 0:0:32,595 - SENT: GETROWS
[Thread-5] 0:0:32,941 - SENT: GETROWS
[Thread-5] 0:0:33,401 - SENT: GETROWS
[Thread-5] 0:0:33,839 - SENT: GETROWS
[Thread-5] 0:0:34,252 - SENT: GETROWS
[Thread-5] 0:0:34,748 - SENT: GETROWS
[Thread-5] 0:0:35,33 - SENT: GETROWS
[Thread-5] 0:0:35,303 - SENT: GETROWS
[Thread-5] 0:0:36,114 - SENT: GETROWS
[Thread-5] 0:0:36,594 - SENT: GETROWS
[Thread-5] 0:0:36,867 - SENT: GETROWS
[Thread-5] 0:0:37,240 - SENT: GETROWS
[Thread-5] 0:0:37,697 - SENT: GETROWS
[Thread-5] 0:0:38,16 - SENT: GETROWS
[Thread-5] 0:0:38,531 - SENT: GETROWS
[Thread-5] 0:0:39,103 - SENT: GETROWS
[Thread-5] 0:0:39,437 - SENT: GETROWS
[Thread-5] 0:0:39,722 - SENT: GETROWS
[Thread-5] 0:0:39,991 - SENT: GETROWS
[Thread-5] 0:0:40,283 - SENT: GETROWS
[Thread-5] 0:0:40,531 - SENT: GETROWS
[Thread-5] 0:0:40,764 - SENT: GETROWS
[Thread-5] 0:0:41,49 - SENT: GETROWS
[Thread-5] 0:0:41,360 - SENT: GETROWS
[Thread-5] 0:0:41,664 - SENT: GETROWS
[Thread-5] 0:0:41,973 - SENT: GETROWS
[Thread-5] 0:0:42,231 - SENT: GETROWS
[Thread-5] 0:0:42,543 - SENT: GETROWS
[Thread-5] 0:0:42,815 - SENT: GETROWS
[Thread-5] 0:0:43,91 - SENT: GETROWS
[Thread-5] 0:0:43,380 - SENT: GETROWS
[Thread-5] 0:0:43,696 - SENT: GETROWS
[Thread-5] 0:0:43,983 - SENT: GETROWS
[Thread-5] 0:0:44,267 - SENT: GETROWS
[Thread-5] 0:0:44,579 - SENT: GETROWS
[Thread-5] 0:0:44,874 - SENT: GETROWS
[Thread-5] 0:0:45,151 - SENT: GETROWS
[Thread-5] 0:0:45,419 - SENT: GETROWS
[Thread-5] 0:0:45,670 - SENT: GETROWS
[Thread-5] 0:0:46,289 - SENT: GETROWS
[Thread-5] 0:0:46,523 - SENT: GETROWS
[Thread-5] 0:0:46,746 - SENT: GETROWS
[Thread-5] 0:0:46,981 - SENT: GETROWS
[Thread-5] 0:0:47,248 - SENT: GETROWS
[Thread-5] 0:0:47,457 - SENT: GETROWS
[Thread-5] 0:0:47,717 - SENT: GETROWS
[Thread-5] 0:0:47,948 - SENT: GETROWS
[Thread-5] 0:0:48,531 - SENT: GETROWS
[Thread-5] 0:0:48,794 - SENT: GETROWS
[Thread-5] 0:0:49,40 - SENT: GETROWS
[Thread-5] 0:0:49,222 - SENT: GETROWS
[Thread-5] 0:0:49,501 - SENT: GETROWS
[Thread-5] 0:0:49,699 - SENT: GETROWS
[Thread-5] 0:0:49,925 - SENT: GETROWS
[Thread-5] 0:0:50,186 - SENT: GETROWS
[Thread-5] 0:0:50,402 - SENT: GETROWS
[Thread-5] 0:0:50,575 - SENT: GETROWS
[Thread-5] 0:0:50,854 - SENT: GETROWS
[Thread-5] 0:0:51,103 - SENT: GETROWS
[Thread-5] 0:0:51,329 - SENT: GETROWS
[Thread-5] 0:0:51,556 - SENT: GETROWS
[Thread-5] 0:0:51,779 - SENT: GETROWS
[Thread-5] 0:0:51,969 - SENT: GETROWS
[Thread-5] 0:0:52,210 - SENT: GETROWS
[Thread-5] 0:0:52,468 - SENT: GETROWS
[Thread-5] 0:0:52,703 - SENT: GETROWS
[Thread-5] 0:0:52,988 - SENT: GETROWS
[Thread-5] 0:0:53,279 - SENT: GETROWS
[Thread-5] 0:0:53,563 - SENT: GETROWS
[Thread-5] 0:0:53,854 - SENT: GETROWS
[Thread-5] 0:0:54,130 - SENT: GETROWS
[Thread-5] 0:0:54,347 - SENT: GETROWS
[Thread-5] 0:0:54,558 - SENT: GETROWS
[Thread-5] 0:0:54,814 - SENT: GETROWS
[Thread-5] 0:0:55,37 - SENT: GETROWS
[Thread-5] 0:0:55,242 - SENT: GETROWS
[Thread-5] 0:0:55,452 - SENT: GETROWS
[Thread-5] 0:0:55,661 - SENT: GETROWS
[Thread-5] 0:0:55,985 - SENT: GETROWS
[Thread-5] 0:0:56,234 - SENT: GETROWS
[Thread-5] 0:0:56,463 - SENT: GETROWS
[Thread-5] 0:0:56,685 - SENT: GETROWS
[Thread-5] 0:0:56,908 - SENT: GETROWS
[Thread-5] 0:0:57,187 - SENT: GETROWS
[Thread-5] 0:0:57,400 - SENT: GETROWS
[Thread-5] 0:0:57,661 - SENT: GETROWS
[Thread-5] 0:0:57,884 - SENT: GETROWS
[Thread-5] 0:0:58,154 - SENT: GETROWS
[Thread-5] 0:0:58,436 - SENT: GETROWS
[Thread-5] 0:0:58,685 - SENT: GETROWS
[Thread-5] 0:0:58,968 - SENT: GETROWS
[Thread-5] 0:0:59,179 - SENT: GETROWS
[Thread-5] 0:0:59,407 - SENT: GETROWS
[Thread-5] 0:0:59,633 - SENT: GETROWS
[Thread-5] 0:0:59,820 - SENT: GETROWS
[Thread-5] 0:1:0,71 - SENT: GETROWS
[Thread-5] 0:1:0,287 - SENT: GETROWS
[Thread-5] 0:1:0,499 - SENT: GETROWS
[Thread-5] 0:1:0,690 - SENT: GETROWS
[Thread-5] 0:1:0,898 - SENT: GETROWS
[Thread-5] 0:1:1,92 - SENT: GETROWS
[Thread-5] 0:1:1,329 - SENT: GETROWS
[Thread-5] 0:1:1,591 - SENT: GETROWS
[Thread-5] 0:1:1,837 - SENT: GETROWS
[Thread-5] 0:1:2,75 - SENT: GETROWS
[Thread-5] 0:1:2,295 - SENT: GETROWS
[Thread-5] 0:1:2,534 - SENT: GETROWS
[Thread-5] 0:1:2,783 - SENT: GETROWS
[Thread-5] 0:1:2,984 - SENT: GETROWS
[Thread-5] 0:1:3,216 - SENT: GETROWS
[Thread-5] 0:1:3,491 - SENT: GETROWS
[Thread-5] 0:1:3,922 - SENT: GETROWS
[Thread-5] 0:1:4,224 - SENT: GETROWS
[Thread-5] 0:1:4,473 - SENT: GETROWS
[Thread-5] 0:1:4,731 - SENT: GETROWS
[Thread-5] 0:1:4,976 - SENT: GETROWS
[Thread-5] 0:1:5,192 - SENT: GETROWS
[Thread-5] 0:1:5,504 - SENT: GETROWS
[Thread-5] 0:1:5,794 - SENT: GETROWS
[Thread-5] 0:1:6,36 - SENT: GETROWS
[Thread-5] 0:1:6,287 - SENT: GETROWS
[Thread-5] 0:1:6,560 - SENT: GETROWS
[Thread-5] 0:1:6,755 - SENT: GETROWS
[Thread-5] 0:1:6,961 - SENT: GETROWS
[Thread-5] 0:1:7,156 - SENT: GETROWS
[Thread-5] 0:1:7,371 - SENT: GETROWS
[Thread-5] 0:1:7,626 - SENT: GETROWS
[Thread-5] 0:1:7,986 - SENT: GETROWS
[Thread-5] 0:1:8,297 - SENT: GETROWS
[Thread-5] 0:1:8,566 - SENT: GETROWS
[Thread-5] 0:1:8,801 - SENT: GETROWS
[Thread-5] 0:1:9,50 - SENT: GETROWS
[Thread-5] 0:1:9,275 - SENT: GETROWS
[Thread-5] 0:1:9,492 - SENT: GETROWS
[Thread-5] 0:1:9,775 - SENT: GETROWS
[Thread-5] 0:1:9,980 - SENT: GETROWS
[Thread-5] 0:1:10,222 - SENT: GETROWS
[Thread-5] 0:1:10,322 - SENT: DONE
[Thread-5] 0:1:10,352 - RECEIVED: OK
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[EDT] 0:1:13,184 - Loading database Books.rw3
**** Database.exists() is not supported in the Javascript port.  If you plan to deploy to Javascript, you should avoid this method. *****
[Thread-6] 0:1:13,192 - Loading database...
[EDT] 0:1:13,241 - Queueing image load for ID=1057
[Thread-7] 0:1:13,243 - Loading image for 1057
[EDT] 0:1:13,247 - Queueing image load for ID=1282
[EDT] 0:1:13,248 - Queueing image load for ID=945
[EDT] 0:1:13,248 - Queueing image load for ID=1126
[EDT] 0:1:13,248 - Queueing image load for ID=987
[EDT] 0:1:13,253 - Queueing image load for ID=1236
[EDT] 0:1:13,254 - Queueing image load for ID=1189
[Thread-7] 0:1:13,270 - Loaded image for 1057
[Thread-7] 0:1:13,270 - Loading image for 1282
[Thread-7] 0:1:13,280 - Loaded image for 1282
[Thread-7] 0:1:13,281 - Loading image for 945
[Thread-7] 0:1:13,290 - Loaded image for 945
[Thread-7] 0:1:13,290 - Loading image for 1126
[Thread-7] 0:1:13,299 - Loaded image for 1126
[Thread-7] 0:1:13,299 - Loading image for 987
[Thread-7] 0:1:13,302 - Loaded image for 987
[Thread-7] 0:1:13,302 - Loading image for 1236
[Thread-7] 0:1:13,306 - Loaded image for 1236
[Thread-7] 0:1:13,306 - Loading image for 1189
[Thread-7] 0:1:13,313 - Loaded image for 1189
[Thread-6] 0:1:13,459 - Loaded database.
[Thread-6] 0:1:13,459 - Database ready


Here are the Network Monitor screen shots for the first request which is the one failing on the device.

![basic](https://cloud.githubusercontent.com/assets/14006739/24017612/ec80b72c-0a4d-11e7-825b-a2a9ab0dc537.png)
![request](https://cloud.githubusercontent.com/assets/14006739/24017621/f4a8a2f2-0a4d-11e7-8544-d7857d9f2563.png)
![response](https://cloud.githubusercontent.com/assets/14006739/24017630/fafd2ee8-0a4d-11e7-8b0f-f7d526079965.png)


This is the code I am using to make the connection. I will add more debugging info and post the results shortly.

        protected String sendCommandAndWait(String command) {

            try {
                NetworkManager networkManager = NetworkManager.getInstance();
                ConnectionRequest connectionRequest = new ConnectionRequest();
                connectionRequest.setUrl("http://" + _host + ":" + _port + "/Query?REQ=" + command);
                connectionRequest.setPost(false);
                connectionRequest.setContentType("text/html");
                connectionRequest.setPriority(ConnectionRequest.PRIORITY_HIGH);
                connectionRequest.setTimeout(10000);
                connectionRequest.setFailSilently(true);

                MLog.debug("SENT: " + command);
                networkManager.setTimeout(10000);
                networkManager.addToQueueAndWait(connectionRequest);
                //MLog.debug("DATATYPE=" + connectionRequest.getContentType());
                //MLog.debug("DATA=" + new String(connectionRequest.getResponseData()));

                byte[] buffer = connectionRequest.getResponseData();

                if (buffer == null) {
                    return null;
                }

                String response = new String(buffer);
                MLog.debug("RECEIVED: " + response);

                return response;
            }
            catch (Exception ioException) {
                ioException.printStackTrace();
            }

            return null;
        }

**Comment by shannah** [comment]
What is the response code on the surface book for that request?  You should be able to add an error listener to the network manager to get that.

**Comment by shannah** [comment]
Also, if you have access on the server-side, can you verify if the request is being received at all by the server?

**Comment by mwarnett** [comment]
I am not having any luck getting more information on this error.

I tried running in the simulator with an invalid IP address which yielded a SocketTimeoutException. However there was no exception thrown control was returned after the networkManager.addToQueueAndWait(_connectionRequest); The connectionRequest return code was 0 and the buffer null. The error listener was never called.

It seems to be the same story on the device. The error listener was never called, there was no exception caught.

Here is the latest log from the device:

[EDT] 0:0:1,576 - Codename One revisions: f5f70630a46eced2d7416801e17d7e121224affd
2341

[EDT] 0:0:1,593 - Log.getUniqueDeviceId()->6483465995550720
[EDT] 0:0:1,608 - RWMain - init
[EDT] 0:0:1,655 - RW - Books 3.54
[EDT] 0:0:1,662 - RWMain - start
[EDT] 0:0:1,670 - Platform=win
[EDT] 0:0:1,677 - _osVer=3.54
[EDT] 0:0:1,683 - osMajVer=3
[EDT] 0:0:1,798 - Database open failure: RWareDB.rw3 not found
[Thread-1] 0:0:31,79 - Connection to 192.168.1.105...
[Thread-1] 0:0:31,87 - SENT: PING
[Network Thread] 0:0:31,152 - Exception: java.io.IOException - An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established


   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at UWPApp.IKVMReflectionHelper.getCurrentStackTrace()
   at java.lang.ThrowableHelper.getCurrentStackTrace()
   at java.lang.Throwable..ctor(String message)
   at java.lang.Exception..ctor(String message)
   at java.io.IOException..ctor(String message)
   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()
   at com.codename1.impl.CodenameOneThread.run()
   at com.codename1.impl.SilverlightImplementation.CodenameOneUWPThread.run()
   at java.lang.Thread.threadProc2()
   at java.lang.Thread.threadProc()
   at java.lang.Thread.1.Invoke()
   at com.codename1.impl.NativeThreadImpl.<>c__DisplayClass6_0.<init>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Originating from:
Message=An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()[Thread-1] 0:0:31,188 - CR RC=0
[EDT] 0:0:35,360 - Database open failure: RWareDB.rw3 not found

**Comment by shannah** [comment]
Try overriding the handleException() and handleErrorResponseCode() methods in your connection request to catch information there.

I'm not interested in the result of an invalid IP address in the simulator.  I want to see what is happening on the UWP device that is failing on that URL.  I would like to know what the response code is that is returned from the server.

I would also like to know (if possible) if the server actually receives the request at all.  Not sure if you have that kind of access at the server.

**Comment by mwarnett** [comment]
I have verified that the app is NOT connecting to the server. I put a breakpoint in the server and verified that it was being hit by running the app on a phone. When I run the app on the surface book the breakpoint is not hit and the connection fails. Working on debugging.

**Comment by mwarnett** [comment]
Still no luck with debugging info.

Here is the code:

            try {
                NetworkManager networkManager = NetworkManager.getInstance();
                ConnectionRequest connectionRequest = new MyConnectionRequest();
                connectionRequest.setUrl("http://" + _host + ":" + _port + "/Query?REQ=" + command);
                connectionRequest.setPost(false);
                connectionRequest.setContentType("text/html");
                connectionRequest.setPriority(ConnectionRequest.PRIORITY_HIGH);
                connectionRequest.setTimeout(10000);
                connectionRequest.setFailSilently(true);

                MLog.debug("SENT: " + command);
                networkManager.setTimeout(10000);
                networkManager.addToQueueAndWait(connectionRequest);
                MLog.debug("BACK FROM: " + command);
                MLog.debug("RC=" + connectionRequest.getResponseCode());
                //MLog.debug("DATATYPE=" + connectionRequest.getContentType());
                //MLog.debug("DATA=" + new String(connectionRequest.getResponseData()));

                byte[] buffer = connectionRequest.getResponseData();

                if (buffer == null) {
                    return null;
                }

                String response = new String(buffer);
                MLog.debug("RECEIVED: " + response);

                return response;
            }
            catch (Exception ioException) {
                MLog.debug("Exception caught");
                ioException.printStackTrace();
            }

    private class MyConnectionRequest extends ConnectionRequest {

        protected void  handleErrorResponseCode(int code, String message) {
            MLog.debug("handleErrorResponseCode, C=" + code);
            MLog.debug("handleErrorResponseCode, M=" + message);
            super.handleErrorResponseCode(code, message);
        }


        protected void  handleException(Exception exception) {
            MLog.debug("handleException");
            MLog.debug(exception);
            super.handleException(exception);
        }

    }

The command simply returns as if everything worked. I am catch exceptions but nothing is ever thrown, my connectioRequest verrides are never called. Someone is printing the stack trace but it is not me

Latest log:



[EDT] 0:0:2,924 - Codename One revisions: 737916f0577bc20fe03deb4496211581b256bb4b
2342

[EDT] 0:0:2,944 - Log.getUniqueDeviceId()->6140958795366400
[EDT] 0:0:2,968 - RWMain - init
[EDT] 0:0:3,24 - RW - Books 3.54
[EDT] 0:0:3,34 - RWMain - start
[EDT] 0:0:3,47 - Platform=win
[EDT] 0:0:3,56 - _osVer=3.54
[EDT] 0:0:3,64 - osMajVer=3
[EDT] 0:0:3,212 - Database open failure: RWareDB.rw3 not found
[Thread-1] 0:0:27,96 - Connection to 192.168.1.105...
[Thread-1] 0:0:27,103 - SENT: PING
[Network Thread] 0:0:27,155 - Exception: java.io.IOException - An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established


   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at UWPApp.IKVMReflectionHelper.getCurrentStackTrace()
   at java.lang.ThrowableHelper.getCurrentStackTrace()
   at java.lang.Throwable..ctor(String message)
   at java.lang.Exception..ctor(String message)
   at java.io.IOException..ctor(String message)
   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()
   at com.codename1.impl.CodenameOneThread.run()
   at com.codename1.impl.SilverlightImplementation.CodenameOneUWPThread.run()
   at java.lang.Thread.threadProc2()
   at java.lang.Thread.threadProc()
   at java.lang.Thread.1.Invoke()
   at com.codename1.impl.NativeThreadImpl.<>c__DisplayClass6_0.<init>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Originating from:
Message=An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

   at com.codename1.impl.NetworkOperation.get_response()
   at com.codename1.impl.SilverlightImplementation.getResponseCode(Object n1)
   at com.codename1.io.ConnectionRequest.performOperation()
   at com.codename1.io.NetworkManager.NetworkThread.run()[Thread-1] 0:0:27,185 - BACK FROM: PING
[Thread-1] 0:0:27,190 - RC=0
[EDT] 0:0:30,741 - Database open failure: RWareDB.rw3 not found

**Comment by shannah** [comment]
I think I know what may be happening.  I was just looking at the [capabilities page](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations) for UWP and noticed that the `internetClient` capability doesn't allow local network access:

> The internetClient capability indicates that apps can receive incoming data from the Internet. Cannot act as a server. No local network access.
> The internetClientServer capability indicates that apps can receive incoming data from the Internet. Can act as a server. No local network access.

The build server is set up by default to include the `internetClient` capability.  But not the `privateNetworkClientServer` capability, which is described thusly:

> The privateNetworkClientServer capability provides inbound and outbound access to home and work networks through the firewall. This capability is typically used for games that communicate across the local area network (LAN), and for apps that share data across a variety of local devices. If your app specifies musicLibrary, picturesLibrary, or videosLibrary, you don't need to use this capability to access the corresponding library in a Home Group. On Windows, this capability does not provide access to the Internet.

Try adding the `privateNetworkClientServer` capability by adding the following build hint:

`uwp.capabilities=privateNetworkClientServer`

NOTE: If you need to add multiple capabilities, you can separate them with commas in that same build hint.

**Comment by mwarnett** [comment]
It definitely sounds like I need that. Unfortunately it did not make any difference, same log as before.

I checked the size of the last two builds they were the same. Is there any way I can check that this made it into the build

**Comment by shannah** [comment]
Select the "Include source" option, and check the appxmanifest file and take a look at the `<Capabilities>..</Capabilities> `section.

**Comment by mwarnett** [comment]
Didn't make it, I have:
<Capabilities><Capability Name="internetClient"/><uap:Capability Name="picturesLibrary"/><uap:Capability Name="videosLibrary"/><uap:Capability Name="removableStorage"/><uap:Capability Name="musicLibrary"/></Capabilities>

If this is required wouldn't I also need it for the phone version? That works fine.
![image1](https://cloud.githubusercontent.com/assets/14006739/24061362/6a4c2ab2-0b14-11e7-8fc0-f0f207b7513b.png)

**Comment by shannah** [comment]
Sorry.  Looks like the build hint is actually `windows.capabilities`.  I was looking at the wrong thing.

**Comment by mwarnett** [comment]
That did it!

Thank you
