### ISSUE TITLE
UWP Field Crash

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2074]
Since releasing my UWP apps I have received a steady stream of exception reports, two different exceptions but very similiar. I include the unique device ID in the log and they are not all from the same user. Unfortunately nobody has contacted me about this so I have no idea how the problem is affecting them or the device they are using. I have tested on a Lumia phone and a Surface Book, I have not been able to reproduce the problem here.

I am showing a dialog when this problem occurs:

`

[EDT] 0:0:0,0 - Codename One revisions: f5f70630a46eced2d7416801e17d7e121224affd
2341

[EDT] 0:0:0,32 - Log.getUniqueDeviceId()->5916413220093952
[EDT] 0:0:0,63 - VWMain - init
[EDT] 0:0:0,94 - RW - Video 3.54
[EDT] 0:0:0,110 - VWMain - start
[EDT] 0:0:0,141 - Platform=win
[EDT] 0:0:0,172 - _osVer=3.54
[EDT] 0:0:0,188 - osMajVer=3
[EDT] 0:0:0,250 - Database open failure: VWareDB.vw3 not found
[EDT] 0:1:38,99 - Exception: cli.System.ArgumentException - Arg_ArgumentException
   at UWPApp!<BaseAddress>+0x75ac92
   at UWPApp!<BaseAddress>+0x8b341b
   at UWPApp!<BaseAddress>+0x8b330b
   at Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(Graphics.Canvas.ICanvasResourceCreator resourceCreator, String textString, Graphics.Canvas.Text.CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)
   at com.codename1.impl.WindowsGraphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.impl.WindowsMutableGraphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.impl.SilverlightImplementation.drawString(Object graphics, String str, Int32 x, Int32 y)
   at com.codename1.impl.CodenameOneImplementation.drawString(Object nativeGraphics, Object nativeFont, String str, Int32 x, Int32 y, Int32 textDecoration, Int32 fontHeight)
   at com.codename1.impl.CodenameOneImplementation.drawString(Object nativeGraphics, Object nativeFont, String str, Int32 x, Int32 y, Int32 textDecoration)
   at com.codename1.ui.Graphics.drawString(String str, Int32 x, Int32 y, Int32 textDecoration)
   at com.codename1.ui.Graphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.ui.FontImage.drawImage(codename1.ui.Graphics g, Object nativeGraphics, Int32 x, Int32 y)
   at com.codename1.ui.Graphics.drawImage(codename1.ui.Image img, Int32 x, Int32 y)
   at com.codename1.ui.FontImage.toImage()
   at com.codename1.components.InfiniteProgress.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredH()
   at com.codename1.ui.layouts.FlowLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.layouts.GridBagLayout.initCompSides(codename1.ui.layouts.GridBagLayout.ParentInfo info)
   at com.codename1.ui.layouts.GridBagLayout.validate(codename1.ui.Container parent, codename1.ui.layouts.GridBagLayout.ParentInfo info)
   at com.codename1.ui.layouts.GridBagLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.Component.calcScrollSize()
   at com.codename1.ui.Component.getScrollDimension()
   at com.codename1.ui.Container.isScrollableY()
   at com.codename1.ui.Component.isScrollable()
   at com.codename1.ui.Form.isScrollable()
   at com.codename1.ui.Container.getScrollableParent()
   at com.codename1.ui.Container.getLayoutHeight()
   at com.codename1.ui.layouts.BorderLayout.layoutContainer(codename1.ui.Container target)
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.revalidate()
   at com.codename1.ui.Dialog.showPackedImpl(String position, Boolean modal, Boolean stretch)
   at com.codename1.ui.Dialog.showPacked(String position, Boolean modal)
   at com.codename1.ui.Dialog.showImpl(Boolean reverse)
   at com.codename1.ui.Dialog.show()
   at com.readerware.xware.XWMain.connectToDatabase()
   at com.readerware.xware.XWMain.databaseChooser(Boolean startUp)
   at com.readerware.xware.XWMain.actionPerformed(codename1.ui.events.ActionEvent actionEvent)
   at com.codename1.ui.util.EventDispatcher.fireActionSync(codename1.ui.events.ActionListener[] array, codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.util.EventDispatcher.fireActionEvent(codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.Form.actionCommandImplNoRecurseComponent(codename1.ui.Command cmd, codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.Button.fireActionEvent(Int32 x, Int32 y)
   at com.codename1.ui.Button.released(Int32 x, Int32 y)
   at com.codename1.ui.Button.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Form.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Form.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Component.pointerReleased(Int32[] x, Int32[] y)
   at com.codename1.ui.Display.handleEvent(Int32 offset)
   at com.codename1.ui.Display.edtLoopImpl()
   at com.codename1.ui.Display.mainEDTLoop()[EDT] 0:1:38,178 - Exception in RW - Video version 3.54
[EDT] 0:1:38,193 - OS win
[EDT] 0:1:38,209 - Error cli.System.ArgumentException: Arg_ArgumentException
[EDT] 0:1:38,209 - Current Form ListResultsForm
[EDT] 0:1:38,224 - Exception: cli.System.ArgumentException - Arg_ArgumentException
   at UWPApp!<BaseAddress>+0x75ac92
   at UWPApp!<BaseAddress>+0x8b341b
   at UWPApp!<BaseAddress>+0x8b330b
   at Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(Graphics.Canvas.ICanvasResourceCreator resourceCreator, String textString, Graphics.Canvas.Text.CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)
   at com.codename1.impl.WindowsGraphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.impl.WindowsMutableGraphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.impl.SilverlightImplementation.drawString(Object graphics, String str, Int32 x, Int32 y)
   at com.codename1.impl.CodenameOneImplementation.drawString(Object nativeGraphics, Object nativeFont, String str, Int32 x, Int32 y, Int32 textDecoration, Int32 fontHeight)
   at com.codename1.impl.CodenameOneImplementation.drawString(Object nativeGraphics, Object nativeFont, String str, Int32 x, Int32 y, Int32 textDecoration)
   at com.codename1.ui.Graphics.drawString(String str, Int32 x, Int32 y, Int32 textDecoration)
   at com.codename1.ui.Graphics.drawString(String str, Int32 x, Int32 y)
   at com.codename1.ui.FontImage.drawImage(codename1.ui.Graphics g, Object nativeGraphics, Int32 x, Int32 y)
   at com.codename1.ui.Graphics.drawImage(codename1.ui.Image img, Int32 x, Int32 y)
   at com.codename1.ui.FontImage.toImage()
   at com.codename1.components.InfiniteProgress.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredH()
   at com.codename1.ui.layouts.FlowLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.layouts.GridBagLayout.initCompSides(codename1.ui.layouts.GridBagLayout.ParentInfo info)
   at com.codename1.ui.layouts.GridBagLayout.validate(codename1.ui.Container parent, codename1.ui.layouts.GridBagLayout.ParentInfo info)
   at com.codename1.ui.layouts.GridBagLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.Component.calcScrollSize()
   at com.codename1.ui.Component.getScrollDimension()
   at com.codename1.ui.Container.isScrollableY()
   at com.codename1.ui.Component.isScrollable()
   at com.codename1.ui.Form.isScrollable()
   at com.codename1.ui.Container.getScrollableParent()
   at com.codename1.ui.Container.getLayoutHeight()
   at com.codename1.ui.layouts.BorderLayout.layoutContainer(codename1.ui.Container target)
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.revalidate()
   at com.codename1.ui.Dialog.showPackedImpl(String position, Boolean modal, Boolean stretch)
   at com.codename1.ui.Dialog.showPacked(String position, Boolean modal)
   at com.codename1.ui.Dialog.showImpl(Boolean reverse)
   at com.codename1.ui.Dialog.show()
   at com.readerware.xware.XWMain.connectToDatabase()
   at com.readerware.xware.XWMain.databaseChooser(Boolean startUp)
   at com.readerware.xware.XWMain.actionPerformed(codename1.ui.events.ActionEvent actionEvent)
   at com.codename1.ui.util.EventDispatcher.fireActionSync(codename1.ui.events.ActionListener[] array, codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.util.EventDispatcher.fireActionEvent(codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.Form.actionCommandImplNoRecurseComponent(codename1.ui.Command cmd, codename1.ui.events.ActionEvent ev)
   at com.codename1.ui.Button.fireActionEvent(Int32 x, Int32 y)
   at com.codename1.ui.Button.released(Int32 x, Int32 y)
   at com.codename1.ui.Button.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Form.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Form.pointerReleased(Int32 x, Int32 y)
   at com.codename1.ui.Component.pointerReleased(Int32[] x, Int32[] y)
   at com.codename1.ui.Display.handleEvent(Int32 offset)
   at com.codename1.ui.Display.edtLoopImpl()
   at com.codename1.ui.Display.mainEDTLoop()

`
The second exception happens on an addCommand

`

[EDT] 0:0:0,156 - Codename One revisions: f5f70630a46eced2d7416801e17d7e121224affd
2341

[EDT] 0:0:3,682 - Log.getUniqueDeviceId()->4523457011515392
[EDT] 0:0:3,767 - VWMain - init
[EDT] 0:0:4,410 - RW - Video 3.54
[EDT] 0:0:4,457 - VWMain - start
[EDT] 0:0:4,504 - Platform=win
[EDT] 0:0:4,583 - _osVer=3.54
[EDT] 0:0:4,630 - osMajVer=3
[EDT] 0:0:4,904 - Exception: cli.System.ArgumentException - The parameter is incorrect.

The control does not currently have a CanvasDevice associated with it. Ensure that resources are created from a CreateResources or Draw event handler.
   at UWPApp!<BaseAddress>+0x92a71c
   at UWPApp!<BaseAddress>+0xaf51c4
   at UWPApp!<BaseAddress>+0xd19a25
   at Microsoft.Graphics.Canvas.CanvasBitmap.LoadAsync(Graphics.Canvas.ICanvasResourceCreator resourceCreator, Storage.Streams.IRandomAccessStream stream)
   at com.codename1.impl.SilverlightImplementation.createImage(Byte[] bytes, Int32 offset, Int32 len)
   at com.codename1.ui.Image.createImage(Byte[] bytes, Int32 offset, Int32 len)
   at com.codename1.ui.EncodedImage.getInternal()
   at com.codename1.ui.EncodedImage.getInternalImpl()
   at com.codename1.ui.EncodedImage.getWidth()
   at com.codename1.ui.plaf.DefaultLookAndFeel.getPreferredSize(codename1.ui.Label l, codename1.ui.Image[] icons, codename1.ui.Image stateImage)
   at com.codename1.ui.plaf.DefaultLookAndFeel.getButtonPreferredSize(codename1.ui.Button b)
   at com.codename1.ui.Button.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredW()
   at com.codename1.ui.layouts.GridLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.MenuBar.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredH()
   at com.codename1.ui.layouts.BorderLayout.positionTopBottom(codename1.ui.Component target, codename1.ui.Component c, Int32 right, Int32 left, Int32 targetHeight)
   at com.codename1.ui.layouts.BorderLayout.layoutContainer(codename1.ui.Container target)
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.revalidate()
   at com.codename1.ui.MenuBar.addCommand(codename1.ui.Command cmd, Int32 index)
   at com.codename1.ui.Form.addCommand(codename1.ui.Command cmd, Int32 offset)
   at com.readerware.xware.ListResultsForm.commonConstruction()
   at com.readerware.xware.ListResultsForm..ctor(readerware.xware.XWMain xwMain, Boolean mainForm)
   at com.readerware.xware.XWMain.start()
   at com.readerware.xware.videoware.VWMain.start()
   at UWPApp.StartClass.run()
   at com.codename1.ui.Display.processSerialCalls()
   at com.codename1.ui.Display.mainEDTLoop()[EDT] 0:0:8,696 - Exception in RW - Video version 3.54
[EDT] 0:0:8,727 - OS win
[EDT] 0:0:8,758 - Error cli.System.ArgumentException: The parameter is incorrect.

The control does not currently have a CanvasDevice associated with it. Ensure that resources are created from a CreateResources or Draw event handler.
[EDT] 0:0:8,781 - Before the first form!
[EDT] 0:0:8,796 - Exception: cli.System.ArgumentException - The parameter is incorrect.

The control does not currently have a CanvasDevice associated with it. Ensure that resources are created from a CreateResources or Draw event handler.
   at UWPApp!<BaseAddress>+0x92a71c
   at UWPApp!<BaseAddress>+0xaf51c4
   at UWPApp!<BaseAddress>+0xd19a25
   at Microsoft.Graphics.Canvas.CanvasBitmap.LoadAsync(Graphics.Canvas.ICanvasResourceCreator resourceCreator, Storage.Streams.IRandomAccessStream stream)
   at com.codename1.impl.SilverlightImplementation.createImage(Byte[] bytes, Int32 offset, Int32 len)
   at com.codename1.ui.Image.createImage(Byte[] bytes, Int32 offset, Int32 len)
   at com.codename1.ui.EncodedImage.getInternal()
   at com.codename1.ui.EncodedImage.getInternalImpl()
   at com.codename1.ui.EncodedImage.getWidth()
   at com.codename1.ui.plaf.DefaultLookAndFeel.getPreferredSize(codename1.ui.Label l, codename1.ui.Image[] icons, codename1.ui.Image stateImage)
   at com.codename1.ui.plaf.DefaultLookAndFeel.getButtonPreferredSize(codename1.ui.Button b)
   at com.codename1.ui.Button.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredW()
   at com.codename1.ui.layouts.GridLayout.getPreferredSize(codename1.ui.Container parent)
   at com.codename1.ui.Container.calcPreferredSize()
   at com.codename1.ui.MenuBar.calcPreferredSize()
   at com.codename1.ui.Component.preferredSizeImpl()
   at com.codename1.ui.Component.preferredSize()
   at com.codename1.ui.Component.getPreferredSize()
   at com.codename1.ui.Component.getPreferredH()
   at com.codename1.ui.layouts.BorderLayout.positionTopBottom(codename1.ui.Component target, codename1.ui.Component c, Int32 right, Int32 left, Int32 targetHeight)
   at com.codename1.ui.layouts.BorderLayout.layoutContainer(codename1.ui.Container target)
   at com.codename1.ui.Container.doLayout()
   at com.codename1.ui.Container.layoutContainer()
   at com.codename1.ui.Container.revalidate()
   at com.codename1.ui.MenuBar.addCommand(codename1.ui.Command cmd, Int32 index)
   at com.codename1.ui.Form.addCommand(codename1.ui.Command cmd, Int32 offset)
   at com.readerware.xware.ListResultsForm.commonConstruction()
   at com.readerware.xware.ListResultsForm..ctor(readerware.xware.XWMain xwMain, Boolean mainForm)
   at com.readerware.xware.XWMain.start()
   at com.readerware.xware.videoware.VWMain.start()
   at UWPApp.StartClass.run()
   at com.codename1.ui.Display.processSerialCalls()
   at com.codename1.ui.Display.mainEDTLoop()

`

**Comment by shannah** [comment]
Notes to self:  

We need to handle the event where Win2D loses the device, or doesn't have the device yet.  It is possible that just running these ops on the main thread will fix it -- but need to do some research first as that may be unrelated and impact performance negatively.

https://blogs.msdn.microsoft.com/win2d/2014/12/01/handling-lost-devices-in-win2d/

https://blogs.msdn.microsoft.com/win2d/2014/12/02/resource-creation-in-win2d/

https://blogs.msdn.microsoft.com/win2d/2015/01/29/loading-win2d-resources-from-outside-the-createresources-event/

**Comment by shannah** [comment]
Pushing this to 3.8 as I'm not making headway on it.  I need to find a way to reproduce the condition so that I can begin to tackle the problem.  One strategy suggested is to enable/disable the display driver in device manager.  While this does produce problems with the app - screen goes to black - it doesn't match this issue exactly.

**Comment by shannah** [comment]
Pushing this to 3.9.  Without a way to reproduce this, it will likely involve a non-trivial amount of time to address this issue.

**Comment by shannah** [comment]
Still unable to reproduce this issue.  But believe it probably exists.  Pushing to 6.0.  Hopefully a way to reproduce it will be presented at some point.
