### ISSUE TITLE
Working directory not set properly in Eclipse plugin

### ISSUE THREAD

**Issue by cosmicdan** [codenameone/CodenameOne#2082]
First time trying Codename One, not off to a great start at all.

Using the latest everything - a fresh install of Eclipse Neon.3 and Codename One installed from the Marketplace. I've been following the guide/manual (the web version, not PDF version in case it's not updated) but this is a pretty serious problem.

I create a new application and create a new GUI named 'Home' via the normal method as described in the manual. All works well. I open the GUI Editor, add a checkbox, press "Save" and close. The following info appears in the console (I have run Eclipse with -consoleLog parameter):

```
[EDT] 0:0:0,1 - Trying to load the Codename One GUI builder file: file:/E:/Dan/EclipseWorkspace/Cn1HelloWorld/res/guibuilder/com/cosmicdan/cn1helloworld/ui/Home.gui
[EDT] 0:0:0,1 - Successfully loaded the form XML: <?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="FlowLayout" title="Home" name="Home"></component>
[EDT] 0:0:0,15 - createComponent for element: <component name='Home' type='Form' layout='FlowLayout' title='Home'>
</component>

Exception in thread "Thread-9" java.lang.NullPointerException
  at codenameoneplugin.EclipseGUIBuilderConnector.generateSources(EclipseGUIBuilderConnector.java:132)
  at codenameoneplugin.AbstractGuiBuilderConnector$1.run(AbstractGuiBuilderConnector.java:83)
```

Trying to open the GUI Builder again creates a java process that remains stuck (I need to manually terminate it via Task Manager) and this info is added to the console:

```
org.eclipse.jdt.internal.core.CompilationUnit
Cn1HelloWorld
Executing: C:\Program Files\Java\jdk1.8.0_112\jre\bin\java -jar C:\Users\CosmicDan\.codenameone/guibuilder_1.jar -buildVersion 20170110
Process return code is 0
 update20160729
Executing: C:\Program Files\Java\jdk1.8.0_112\jre\bin\java -Xmx1024m -jar C:\Users\CosmicDan\.codenameone/guibuilder_1.jar Connector: file:/C:/Users/CosmicDan/.guiBuilder/guibuilder.input
[EDT] 0:0:0,1 - Codename One revisions: 3dc2fe6c4df57ff264ea094d13e0275639b78086
2293

[EDT] 0:0:0,1 - Trying to load the Codename One GUI builder file: file:/E:/Dan/EclipseWorkspace/Cn1HelloWorld/res/guibuilder/com/cosmicdan/cn1helloworld/ui/Home.gui
[EDT] 0:0:0,1 - Successfully loaded the form XML: <?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="FlowLayout" flowLayoutFillRows="false" flowLayoutAlign="1" flowLayoutValign="0" title="Home" name="Home">
  <component type="CheckBox" text="CheckBox" name="Check_Box_1">
  </component>
</component>

[EDT] 0:0:0,11 - createComponent for element: <component flowlayoutvalign='0' name='Home' flowlayoutfillrows='false' type='Form' layout='FlowLayout' flowlayoutalign='1' title='Home'>
 <component name='Check_Box_1' type='CheckBox' text='CheckBox'>
 </component>
</component>

[EDT] 0:0:0,24 - createComponent for element: <component name='Check_Box_1' type='CheckBox' text='CheckBox'>
</component>

[EDT] 0:0:0,25 - Exception: java.io.FileNotFoundException - E:\eclipse\Cn1HelloWorld\src\com\cosmicdan\cn1helloworld\ui\Home.java (The system cannot find the path specified)
java.io.FileNotFoundException: E:\eclipse\Cn1HelloWorld\src\com\cosmicdan\cn1helloworld\ui\Home.java (The system cannot find the path specified)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at java.io.FileInputStream.<init>(FileInputStream.java:93)
  at com.codename1.impl.javase.JavaSEPort.openFileInputStream(JavaSEPort.java:6588)
  at com.codename1.io.FileSystemStorage.openInputStream(FileSystemStorage.java:284)
  at com.codename1.apps.guibuilder.connector.DesktopConnector.hasMethodSignature(DesktopConnector.java:163)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:177)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:230)
  at com.codename1.apps.guibuilder.GuiPersister.load(GuiPersister.java:82)
  at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:71)
  at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
  at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
  at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
  at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
  at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
  at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.NullPointerException
  at com.codename1.apps.guibuilder.connector.DesktopConnector.hasMethodSignature(DesktopConnector.java:171)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:177)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:230)
  at com.codename1.apps.guibuilder.GuiPersister.load(GuiPersister.java:82)
  at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:71)
  at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
  at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
  at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
  at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
  at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
  at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[EDT] 0:0:0,27 - Gui Builder Exception in version 1.21
[EDT] 0:0:0,27 - OS win
[EDT] 0:0:0,27 - Error java.lang.NullPointerException
[EDT] 0:0:0,27 - Null current form!!!
[EDT] 0:0:0,27 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
  at com.codename1.apps.guibuilder.connector.DesktopConnector.hasMethodSignature(DesktopConnector.java:171)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:177)
  at com.codename1.apps.guibuilder.GuiPersister.createComponent(GuiPersister.java:230)
  at com.codename1.apps.guibuilder.GuiPersister.load(GuiPersister.java:82)
  at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:71)
  at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
  at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
  at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
  at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
  at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
  at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

I have to assume that the inability to re-open the GUI is due to the first error like it's crashing out before saving data properly (and for whatever reason the GUI Builder is using a path relative to its own program folder instead of my workspace folder). I can't seem to find any source code for the Eclipse plugin though so I have no idea why this NPE is occurring. Are the plugins even open source?

**Comment by cosmicdan** [comment]
Ah, I realized it was probably a bug with the working directory so I started my eclipse.exe from the workspace directory - and everything seems to be working now.

Clearly, this is a bug in the plugin that needs to be addressed, but this workaround is good enough until a proper fix can be made.

**Comment by codenameone** [comment]
Thanks, this was a bit tricky to track down. I added some logging too in case the fix fails. 
This will be a part of the next plugin update which we should do some time in mid/late June

**Comment by codenameone** [comment]
It seems this might still be an issue https://stackoverflow.com/questions/45695210/codename-one-uwp-sumbission-fail

**Comment by codenameone** [comment]
I just committed another attempt at fixing this that should be available in the next plugin update
