### ISSUE TITLE
GUIBuilder Can't launch when project directory name has encoded characters

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2083]
````
Apr 07, 2017 9:12:51 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Connector: file:/C:/Users/username-in-local-characters/.guiBuilder/guibuilder.input
[EDT] 0:0:0,1 - Codename One revisions: 3dc2fe6c4df57ff264ea094d13e0275639b78086
2293

[EDT] 0:0:0,2 - Trying to load the Codename One GUI builder file: איתי%20חן/Documents/NetBeansProjects/NewGuiTest/res/guibuilder/com/mycompany/myapp/GuiComponent.gui
[EDT] 0:0:0,3 - Exception: java.lang.IllegalArgumentException - URI is not absolute
java.lang.IllegalArgumentException: URI is not absolute
at java.io.File.<init>(Unknown Source)
at com.codename1.impl.javase.JavaSEPort.unfile(JavaSEPort.java:6502)
at com.codename1.impl.javase.JavaSEPort.openFileInputStream(JavaSEPort.java:6588)
at com.codename1.io.FileSystemStorage.openInputStream(FileSystemStorage.java:284)
at com.codename1.apps.guibuilder.connector.DesktopConnector.loadForm(DesktopConnector.java:113)
at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:69)
at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
at com.codename1.impl.javase.JavaSEPort.unfile(JavaSEPort.java:6506)
at com.codename1.impl.javase.JavaSEPort.openFileInputStream(JavaSEPort.java:6588)
at com.codename1.io.FileSystemStorage.openInputStream(FileSystemStorage.java:284)
at com.codename1.apps.guibuilder.connector.DesktopConnector.loadForm(DesktopConnector.java:113)
at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:69)
at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
at java.io.File.<init>(Unknown Source)
at com.codename1.impl.javase.JavaSEPort.unfile(JavaSEPort.java:6502)
... 10 more
[EDT] 0:0:0,21 - Gui Builder Exception in version 1.21
[EDT] 0:0:0,21 - OS win
[EDT] 0:0:0,21 - Error java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
[EDT] 0:0:0,22 - Null current form!!!
[EDT] 0:0:0,24 - Exception: java.lang.RuntimeException - java.lang.IllegalArgumentException: URI is not absolute
java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
at com.codename1.impl.javase.JavaSEPort.unfile(JavaSEPort.java:6506)
at com.codename1.impl.javase.JavaSEPort.openFileInputStream(JavaSEPort.java:6588)
at com.codename1.io.FileSystemStorage.openInputStream(FileSystemStorage.java:284)
at com.codename1.apps.guibuilder.connector.DesktopConnector.loadForm(DesktopConnector.java:113)
at com.codename1.apps.guibuilder.GUIBuilder.connected(GUIBuilder.java:69)
at com.codename1.apps.guibuilder.GUIBuilder.start(GUIBuilder.java:102)
at com.codename1.apps.guibuilder.desktop.GUIBuilderMain$11.run(GUIBuilderMain.java:427)
at com.codename1.ui.Display.processSerialCalls(Display.java:1152)
at com.codename1.ui.Display.mainEDTLoop(Display.java:969)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
at java.io.File.<init>(Unknown Source)
at com.codename1.impl.javase.JavaSEPort.unfile(JavaSEPort.java:6502)
... 10 more
````

**Comment by shannah** [comment]
Fixed for Netbeans plugin.  SVN rev. 2357

**Comment by shannah** [comment]
Fixed for Eclipse plugin.  SVN rev. 2358.  **NOT TESTED YET**

**Comment by shannah** [comment]
Fixed for IntelliJ pugin.  SVN rev. 2359
