### ISSUE TITLE
NPE when opening SideMenuBar

### ISSUE THREAD

**Issue by tikiwade** [codenameone/CodenameOne#2096]
I am getting a NullPointerException when the SideMenuBar is opened. Note that everything seems to be working as I would expect.

java.lang.NullPointerException
[EDT] 0:0:0,0 - Exception: java.lang.NullPointerException - null
	at com.codename1.ui.SideMenuBar$MenuTransition.initTransition(SideMenuBar.java:1571)
	at com.codename1.ui.Display.initTransition(Display.java:1428)
	at com.codename1.ui.Display.setCurrent(Display.java:1381)
	at com.codename1.ui.Form.show(Form.java:1655)
	at com.codename1.ui.Form.show(Form.java:1633)
	at com.codename1.ui.SideMenuBar.openMenu(SideMenuBar.java:723)
	at com.codename1.ui.SideMenuBar.openMenu(SideMenuBar.java:708)
	at com.codename1.ui.SideMenuBar$6.actionPerformed(SideMenuBar.java:850)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
	at com.codename1.ui.Button.fireActionEvent(Button.java:435)
	at com.codename1.ui.Button.released(Button.java:467)
	at com.codename1.ui.Button.pointerReleased(Button.java:566)
	at com.codename1.ui.Form.pointerReleased(Form.java:2614)
	at com.codename1.ui.Form.pointerReleased(Form.java:2578)
	at com.codename1.ui.Component.pointerReleased(Component.java:3266)
	at com.codename1.ui.Display.handleEvent(Display.java:2025)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1070)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:999)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

I am seeing this in the console output, using simulator with Samsung S7

**Comment by shannah** [comment]
Fixed https://github.com/codenameone/CodenameOne/commit/0cf055ffae2fd49957fbe7732d64ea7df5d2fa70

This will be included in next update.

You can workaround this issue by enabling the side menu shadow (by setting the `sideMenuShadowBool` theme constant to "true".
