### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: main Process: ... java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2116]
I've got a problem when running an android build on device. There is a weird case when it comes to installing a newer build on an android device. I'm getting an error while the app is starting, only if I install an apk, which was built today, as an initial installation. The app does not ask the user for certain permissions anymore. But if I use earlier builds, this does not happen. Even though if I install newer builds on top of installations of older builds. The error is as follows:

```
05-19 15:49:47.745 31340-31340/org.igmg.mainapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.igmg.mainapp, PID: 31340
Theme: themes:{}
java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION
at com.google.maps.api.android.lib6.impl.az.c(:com.google.android.gms.DynamiteModulesB:50297)
at com.google.android.gms.maps.internal.l.onTransact(:com.google.android.gms.DynamiteModulesB:274)
at android.os.Binder.transact(Binder.java:387)
at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.setMyLocationEnabled(Unknown Source)
at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(Unknown Source)
at com.codename1.googlemaps.InternalNativeMapsImpl$14.onMapReady(InternalNativeMapsImpl.java:345)
at com.google.android.gms.maps.MapView$zza$1.zza(Unknown Source)
at com.google.android.gms.maps.internal.zzl$zza.onTransact(Unknown Source)
at android.os.Binder.transact(Binder.java:387)
at com.google.android.gms.maps.internal.bw.a(:com.google.android.gms.DynamiteModulesB:82)
at com.google.maps.api.android.lib6.impl.bf.run(:com.google.android.gms.DynamiteModulesB:1805)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kutoman** [comment]
the error vanishes and the app runs if I grant permissions manually over the App settings..

**Comment by codenameone** [comment]
Another workaround is to use the location API somewhere in your code. This is something we should handle in the code, probably didn't run into it because no one used maps without using location.

**Comment by kutoman** [comment]
actually the location api is used (`LocationManager.getLocationManager().setLocationListener(this);`) that's why I got confused since the older builds didn't cause this problem.

**Comment by kutoman** [comment]
when I do an extra call to the location API just when the App gets started, it works as you said. The other API calls seem to be too late

**Comment by codenameone** [comment]
I'm guessing the issue isn't in the XML permissions but in the Android 6 permission request
