### ISSUE TITLE
Changing skins or running tests fails if the database is used.

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2175]
If you change skins the database ends up open twice or something and you get the following error. This also happens if you run tests from the TestRecorder.

[EDT] 0:0:0,236 - Exception: java.lang.UnsatisfiedLinkError - org.sqlite.NativeDB._open(Ljava/lang/String;I)V
java.lang.UnsatisfiedLinkError: org.sqlite.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.NativeDB._open(Native Method)
Rendering frame took too long 652 milliseconds
	at org.sqlite.DB.open(DB.java:157)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:184)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:105)
	at org.sqlite.JDBC.createConnection(JDBC.java:113)
	at org.sqlite.JDBC.connect(JDBC.java:87)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.codename1.impl.javase.JavaSEPort.openOrCreateDB(JavaSEPort.java:8146)
	at com.codename1.ui.Display.openOrCreate(Display.java:3665)
	at com.codename1.db.Database.openOrCreate(Database.java:59)

**Comment by codenameone** [comment]
I made a fix for this a while back and thought it failed. Trying again this seems to work now with the latest update.
