### ISSUE TITLE
crash in display main loop (android)

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2179]
error is : java.util.ConcurrentModificationException
[EDT] 0:0:0,0 - Exception: java.util.ConcurrentModificationException - null
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.codename1.impl.android.AndroidAsyncView.flushGraphics(AndroidAsyncView.java:380)
	at com.codename1.impl.android.AndroidImplementation.flushGraphics(AndroidImplementation.java:1172)
	at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:615)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:979)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:901)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:818)

google suggests:
https://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr

**Comment by codenameone** [comment]
This happens due to an edt violation in your code

**Comment by ddyer0** [comment]
I suspect you dismissed this on general principles, without any investigation.  Here's the line
that apparently caused the crash, in AndroidAsyncView

`        
        for (AsyncOp o : renderingOperations) {
            o.prepare();
        }
`

This is way, way below anything I ever touch explicitly, and I'm pretty sure that all of 
my drawing is done in the edt thread.  This was a one-time event, so I'm not overly
concerned.

**Comment by ddyer0** [comment]
I looked over my log archives and found two more instances of this, so it's rare, not
a singleton.  Also, one occurrence was while loading the initial splash screen, before
any of the complicated threading is ever reached; which lends weight to the idea that
this is an inherent problem, not induced by user-level edt violations.
