### ISSUE TITLE
StackOverflowError at com.codename1.ui.Form.longPointerPress(Form.java:1605)

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#230]
Original [issue 230](https://code.google.com/p/codenameone/issues/detail?id=230) created by codenameone on 2012-06-26T16:03:11.000Z:

<b>What steps will reproduce the problem?</b>
1. Long Pointer Press in map added with GUI Designer

<b>What is the expected output? What do you see instead?</b>
I expect that nothing happens when i do a long pointer press on the mapcomponent but instead there is a StackOverflowError in Form.java

<b>What version of the product are you using? On what operating system?</b>
latest cn1, windows 7

<b>Please provide any additional information below.</b>
this is the error message:
java.lang.StackOverflowError
	at com.codename1.ui.Component.contains(Component.java:1493)
	at com.codename1.ui.Form.longPointerPress(Form.java:1605)
	at com.codename1.ui.Form.longPointerPress(Form.java:1607)
followed by 
	at com.codename1.ui.Form.longPointerPress(Form.java:1607) 
for like 1000 times

**Comment by codenameone** [comment]
This was fixed a while back
