### ISSUE TITLE
ios.multitasking=true is ignored

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2396]
According to this post I can use `ios.multitasking=true` to avoid the screenshots generation:
https://www.codenameone.com/blog/version-4-1-launch-screen-storyboards.html

It doesn't work, I get the following build server error:

```

Executing: /usr/local/bin/pod --version Process return code is 0
Pods version: 1.4.0

User-level: 11000
Request Args: 
-----------------
j2me.nativeThemeConst=0
ios.multitasking=true
java.version=8
ios.project_type=ios
win.ver=8
ios.dsym=false
ios.prerendered_icon=false
ios.testFlight=false
rim.obfuscation=false
ios.statusbar_hidden=false
ios.application_exits=false
ios.includePush=true
ios.buildType=debug
ios.interface_orientation=UIInterfaceOrientationPortrait:UIInterfaceOrientationPortraitUpsideDown:UIInterfaceOrientationLandscapeLeft:UIInterfaceOrientationLandscapeRight
ios.newStorageLocation=true
android.release=true
android.debug=false
-------------------
OS Version: 10.13.2
Executing: /Applications/Xcode9.2.app/Contents/Developer/usr/bin/xcodebuild -version Process return code is 0
Result is Xcode 9.2
Build version 9C40b

Xcode version line matching pattern: Xcode 9.2
Executing: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -Dretrolambda.inputDir=/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes -Dretrolambda.classpath=/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes:/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/temp2570376523349763.jar -Dretrolambda.outputDir=/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes_retrolamda -Dretrolambda.bytecodeVersion=49 -Dretrolambda.defaultMethods=true -jar /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/temp6068612132762786746.jar Retrolambda 2.5.1
00:00  INFO: Bytecode version: 49 (Java 5)
00:00  INFO: Default methods:  true
00:00  INFO: Input directory:  /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes
00:00  INFO: Output directory: /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes_retrolamda
00:00  INFO: Classpath:        [/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes, /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/temp2570376523349763.jar]
00:00  INFO: Included files:   all
00:00  INFO: Agent enabled:    false
00:00  INFO: Saving lambda class: cool/teammate/registration/Registrazione$$Lambda$1
00:00  INFO: Saving lambda class: cool/teammate/registration/Registrazione$$Lambda$3
Process return code is 0
Executing: javac -classpath /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes -d /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/stub/RegistrazioneStub.java Note: /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/stub/RegistrazioneStub.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Process return code is 0
Executing: javac -classpath /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/classes -d /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/seVer /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/stub/RegistrazioneStub.java Note: /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/stub/RegistrazioneStub.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Process return code is 0
[EDT] 0:0:0,3 - Codename One revisions: 5a1634df155fbd87595ea15ed16375f4a61d982a

[EDT] 0:0:0,7 - The device language is: EN
[EDT] 0:0:0,7 - The file /lang-EN doesn't exist. I'm trying to load the Italian property file
[EDT] 0:0:0,8 - The Italian property file is successfully loaded
[EDT] 0:0:0,8 - I loaded the IT language for the GUI!
[EDT] 0:0:0,53 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
	at com.codename1.impl.javase.JavaSEPort.createBrowserComponent(JavaSEPort.java:9237)
	at com.codename1.ui.BrowserComponent.<init>(BrowserComponent.java:343)
	at cool.teammate.registration.Registrazione.start(Registrazione.java:86)
	at cool.teammate.registration.RegistrazioneStub.run(RegistrazioneStub.java:32)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1129)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:924)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[EDT] 0:0:0,56 - Exception in Registrazione version 1.0
[EDT] 0:0:0,56 - OS ios
[EDT] 0:0:0,56 - Error java.lang.NullPointerException
[EDT] 0:0:0,56 - Before the first form!
[EDT] 0:0:0,56 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
	at com.codename1.impl.javase.JavaSEPort.createBrowserComponent(JavaSEPort.java:9237)
	at com.codename1.ui.BrowserComponent.<init>(BrowserComponent.java:343)
	at cool.teammate.registration.Registrazione.start(Registrazione.java:86)
	at cool.teammate.registration.RegistrazioneStub.run(RegistrazioneStub.java:32)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1129)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:924)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Timeout reached.  Destroying process
Process timed out
Failed to generate device screenshot! /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build3037897170290822800xxx/res/Default.png
```

The following code is the main class, I guess that the problem is the `BrowserComponent`:

```
package xyz;

import com.codename1.components.SpanLabel;
import com.codename1.io.JSONParser;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Button;
import com.codename1.ui.Font;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.util.regex.StringReader;
import cool.teammate.registration.forms.Contract;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Registrazione {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        // Localization
        try {
            // Start localization
            Localization.localize();
        } catch (Exception ex) {
            Log.p("Localization ERROR");
            Log.e(ex);
            Log.sendLogAsync();
        }

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Prototipo della registrazione", BoxLayout.y());

        // Toolbar
        Image teammateToolbar = theme.getImage("TeammateLogo-raster.png");
        Label teammateToolbarTitle = new Label(teammateToolbar.scaledHeight(Display.getInstance().convertToPixels(5)));
        teammateToolbarTitle.getStyle().setAlignment(Label.CENTER);
        hi.getToolbar().setTitleComponent(teammateToolbarTitle);

        // Preload the BrowserComponent
        BrowserComponent browser = new BrowserComponent();
        browser.setURL("https://www.iubenda.com/privacy-policy/82866469");
        browser.setVisible(false);
        
        // Intro text
        SpanLabel introText = new SpanLabel("Prototipo della registrazione di Teammate");
        Button button = new Button("Avanti");
        button.addActionListener(l -> {
            Contract contractForm = new Contract();
            browser.remove();
            contractForm.show(browser);
        });
        hi.add(FlowLayout.encloseCenter(introText)).add(button).add(browser);
        hi.show();

        /*
        // Loads json data
        Map categoriesMap = jsonFileToMap("categories.json");
        Map sportsMap = jsonFileToMap("sports.json");
        Map sportRulesMap = jsonFileToMap("sportRules.json");
        
        // Prints the Maps
        printMap(categoriesMap);
        printMap(sportsMap);
        printMap(sportRulesMap);
         */
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

    /**
     * Loads a json file placed in /src into a new Map
     *
     * @param filename the given json file name (without any path or slash)
     * @return the generated Map or null in case of errors
     */
    public Map<String, Object> jsonFileToMap(String filename) {
        JSONParser json = new JSONParser();
        try (Reader r = new InputStreamReader(Display.getInstance().getResourceAsStream(getClass(), "/" + filename), "UTF-8")) {
            return (json.parseJSON(r));
        } catch (IOException err) {
            Log.p("Error loading " + filename);
            Log.e(err);
            return null;
        }
    }

    /**
     * Prints a Map generated by JSONParser from a json. Each keys of the Map
     * have to be a String, each value of the Map can be another Map or a List.
     *
     * @param map
     */
    private void printMap(Object obj) {
        printMap(obj, "");
    }

    private void printMap(Object obj, String number) {
        String counting = "";
        if (number.length() > 0) {
            counting = number + ".";
        }
        if (obj instanceof Map) {
            Map<String, Object> map = (Map<String, Object>) obj;
            //Log.p("Map size: " + map.size());
            int count = 0;
            for (String item : map.keySet()) {
                count++;
                String counter = counting + count;
                Log.p("item " + counter + ": " + item);
                Object value = map.get(item);
                printMap(value, counter);
            }
        } else if (obj instanceof List) {
            List list = (List) obj;
            //Log.p("List size: " + list.size());
            int count = 0;
            for (Object item : list) {
                count++;
                String counter = counting + count;
                if (item instanceof String) {
                    Log.p("item " + counter + ": " + (String) item);
                } else {
                    printMap(item, counter);
                }
            }
        }
    }

}

```

**Comment by shannah** [comment]
`ios.multitasking=true` will cause the launch screen storyboard to be used instead of the screenshots, however, currently screenshots are still generated - and they are still rendered for a brief moment after the launch storyboard is finished, and before the UI finishes loading.  The images are also still used for older versions of iOS that don't support the storyboard launch screens.

If you want to *not* generate the images, you can additionally use the `ios.fastbuild=true` hint.
