### ISSUE TITLE
[BUG] Camera on Android 4.3 can not save file

### ISSUE THREAD

**Issue by jpaul51** [codenameone/CodenameOne#2449]
Taking a picture with the camera will produce the following errors (adb logcat):

```
E/DatabaseUtils(17752): java.lang.SecurityException: Permission Denial: writing android.support.v4.content.FileProvider uri content://com.mypackage.camerodemo.provider/intent_files/CameraTest/IMG_20180612_171710.jpg from pid=17677, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(17752):         at android.content.ContentProvider$Transport.enforceWritePermissionInner(ContentProvider.java:445)
E/DatabaseUtils(17752):         at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:382)
E/DatabaseUtils(17752):         at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:302)
E/DatabaseUtils(17752):         at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:273)
E/DatabaseUtils(17752):         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:252)
E/DatabaseUtils(17752):         at android.os.Binder.execTransact(Binder.java:397)
E/DatabaseUtils(17752):         at dalvik.system.NativeStart.run(Native Method)
W/dalvikvm(17677): threadid=1: thread exiting with uncaught exception (group=0x415b2898)
E/AndroidRuntime(17677): FATAL EXCEPTION: main
E/AndroidRuntime(17677): java.lang.SecurityException: Permission Denial: writing android.support.v4.content.FileProvider uri content://com.mypackage.camerodemo.provider/intent_files/CameraTest/IMG_20180612_171710.jpg from pid=17677, uid=1000 requires the provider be exported, or grantUriPermission()
E/AndroidRuntime(17677):        at android.os.Parcel.readException(Parcel.java:1431)
E/AndroidRuntime(17677):        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
E/AndroidRuntime(17677):        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
E/AndroidRuntime(17677):        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:577)
E/AndroidRuntime(17677):        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:673)
E/AndroidRuntime(17677):        at android.content.ContentResolver.openOutputStream(ContentResolver.java:537)
E/AndroidRuntime(17677):        at android.content.ContentResolver.openOutputStream(ContentResolver.java:513)
E/AndroidRuntime(17677):        at com.android.camera.PhotoModule.onCaptureDone(PhotoModule.java:1549)
E/AndroidRuntime(17677):        at com.android.camera.PhotoUI$4.onClick(PhotoUI.java:242)
E/AndroidRuntime(17677):        at android.view.View.performClick(View.java:4240)
E/AndroidRuntime(17677):        at android.view.View$PerformClick.run(View.java:17721)
E/AndroidRuntime(17677):        at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime(17677):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(17677):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(17677):        at android.app.ActivityThread.main(ActivityThread.java:5136)
E/AndroidRuntime(17677):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17677):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(17677):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(17677):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(17677):        at dalvik.system.NativeStart.main(Native Method)

```
Here is the code I am using:
```


   Form hi = new Form("CameraTest", new BorderLayout());
        Label picture = new Label("", "Container");
        hi.add(BorderLayout.CENTER, picture);
        hi.getUnselectedStyle().setBgColor(0xff0000);
        hi.getUnselectedStyle().setBgTransparency(255);
        Style s = UIManager.getInstance().getComponentStyle("TitleCommand");
        Image camera = FontImage.createMaterial(FontImage.MATERIAL_CAMERA, s);
        hi.getToolbar().addCommandToRightBar("", camera, (ev) -> {

            int width = Display.getInstance().getDisplayWidth();

            Capture.capturePhoto(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    String source = (String) evt.getSource();

                    try {
                        Image capturedImage = Image.createImage(source);
                        
                        
                        picture.setIcon(capturedImage);
                        hi.revalidate();

                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            });


        });
        hi.show();
```
I do not know since when I have this problem. I first thought it had something to do with the API update but I tried with the following build hints and I still have the errors.
```
android.buildToolsVersion=23
android.targetSDKVersion=23
```
This only occurs with  Android 4.3

**Comment by shannah** [comment]
Fixed.  Will be included in next server update on Friday.
