### ISSUE TITLE
RFE: add skin for Javascript port

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2493]
At the moment the desktop.skin uses the Android theme, while the Javascript port of the Codename One apps uses the iOS7 skin by default.

I'm working to do an app that target the Javascript, so I can feel more convenient to have a skin the uses the same defaults of the Javascript builds.

Thanks.

**Comment by codenameone** [comment]
This was really a bug where no skin was applied. It should now use the iOS skin everywhere.

**Comment by jsfan3** [comment]
Thank you. I merged your commit in my fork of Codename One, I recompiled my project that uses the Codename One project as compile library and the JavaSE port as runtime library, I resetted the skins... but nothing is changed. What does I have to do to implement your fix in my machine?

**Comment by codenameone** [comment]
Is the iOS7 skin in the JavaSE port's src directory?

**Comment by jsfan3** [comment]
In CodenameOne\Ports\JavaSE\src there are:

- iOS7Theme.res
- iPhoneX.skin
- winTheme.res

and other files...

**Comment by codenameone** [comment]
I just tried reproducing this in the kitchen sink and it seems to use the iOS theme no matter what I do. Notice the lower case buttons which indicate it's iOS:

<img width="912" alt="screen shot 2018-08-07 at 10 32 44" src="https://user-images.githubusercontent.com/2353641/43761706-85e8ba60-9a2e-11e8-8e01-fc5557684885.png">

**Comment by jsfan3** [comment]
I can execute the KitchenSink with the default libraries (showing the old desktop.skin), but I cannot execute the KitchenSink with my just updated fork of Codename One, because a java.lang.NullPointerException. This is the log:

```
ant -f C:\\Users\\Francesco\\Documents\\NetBeansProjects\\KitchenSink -Dnb.internal.action.name=run run
No GUI Entries available
init:
Deleting: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\build\built-jar.properties
CodenameOne.init:
CodenameOne.deps-jar:
Updating property file: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\build\built-jar.properties
Factory.init:
Factory.deps-jar:
Updating property file: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\build\built-jar.properties
Factory.compile:
Factory.jar:
CodenameOne.initEnv:
Init env executing with cn1env = ${cn1env} for ../../CodenameOne/GUIBuilder/src
CodenameOne.stamp:
Compiling 6 source files to C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\CodenameOne\build\classes
Note: C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\CodenameOne\src\com\codename1\processing\HashtableContent.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\CodenameOne\src\com\codename1\processing\HashtableContent.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
CodenameOne.compile:
Building jar: C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\CodenameOne\dist\CodenameOne.jar
CodenameOne.jar:
JavaSE.init:
JavaSE.deps-jar:
Updating property file: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\build\built-jar.properties
JavaSE.build-skins:
JavaSE.init-skins:
DEPRECATED - The copydir task is deprecated.  Use copy instead.
Copying 1 file to C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\Ports\JavaSE\build\classes
Expanding: C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javase\sqlite-jdbc-3.7.15-M1.jar into C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\Ports\JavaSE\build\classes
Expanding: C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javase\Filters.jar into C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\Ports\JavaSE\build\classes
JavaSE.compile:
Building jar: C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\Ports\JavaSE\dist\JavaSE.jar
To run this application from the command line without Ant, try:
C:\Program Files\Java\jdk1.8.0_152\jre/bin/java -cp C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\CodenameOne\dist\CodenameOne.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javase\sqlite-jdbc-3.7.15-M1.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javase\Filters.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.base.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.controls.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.swing.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.web.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.media.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.graphics.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib\javafx.fxml.jar;C:\Users\Francesco\Documents\NetBeansProjects\cn1-binaries\javafx\lib;C:\Users\Francesco\Documents\NetBeansProjects\CodenameOne\Ports\JavaSE\dist\JavaSE.jar com.codename1.impl.javase.Simulator
JavaSE.jar:
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
compile:
run:
Found theme.css file.  Watching for changes...
CSS> Input: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\css\theme.css
CSS> Output: C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\src\theme.res
CSS> Acquiring lock on CSS checksums file C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\.cn1_css_checksums...
CSS> Lock obtained
CSS> C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\src\theme.res has been modified since it was last compiled.  Making copy at C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\css\.backups\theme.res.1533635024398.bak
CSS> Releasing lock
CSS> CSS file successfully compiled.  C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\src\theme.res
CSS> Watching file C:\Users\Francesco\Documents\NetBeansProjects\KitchenSink\css\theme.css for changes...
ago 07, 2018 11:43:42 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
CSS> ago 07, 2018 11:43:44 AM java.util.prefs.WindowsPreferences <init>
CSS> AVVERTENZA: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[EDT] 0:0:3,172 - Codename One revisions: 24916e0d70fcd4f7e5bd7af05d39e500807b5b90

[EDT] 0:0:3,194 - Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
	at com.codename1.demos.kitchen.KitchenSink.lambda$null$6(KitchenSink.java:182)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1129)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1073)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:961)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
BUILD SUCCESSFUL (total time: 13 seconds)
```

**Comment by codenameone** [comment]
I broke the kitchen sink when I played with the CSS support in it. I committed a fix for it.
