### ISSUE TITLE
[BUG] IndexOutOfBoundsException thrown by UiBinding.BoundTableModel.addRow

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2505]
The expect behavior of the following test case is that the `UiBinding.BoundTableModel.addRow` method will add a row to the table and implicity add the new `PropertyBusinessObject` to the `List<PropertyBusinessObject>` binded to the table. Instead it throws an `IndexOutOfBoundsException`.

I report the log and the code.

Code:
```
package ...;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.properties.IntProperty;
import com.codename1.properties.Property;
import com.codename1.properties.PropertyBusinessObject;
import com.codename1.properties.PropertyIndex;
import com.codename1.properties.UiBinding;
import com.codename1.ui.Component;
import com.codename1.ui.table.Table;
import com.codename1.ui.table.TableLayout;
import com.codename1.ui.table.TableModel;
import java.util.ArrayList;
import java.util.List;

/**
 * TestCase for Table binded to a List<PropertyBusinessObject>
 *
 */
public class TestCase {

    private Form current;
    private Resources theme;

    private static List<PropertyBusinessObject> listToShow = null;
    private static myPropertyBusinessObject prototype = new myPropertyBusinessObject();

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Test Case", BoxLayout.y());

        if (listToShow == null) {
            listToShow = getSportType();
        }

        UiBinding.BoundTableModel model = new UiBinding.BoundTableModel(listToShow, prototype);
        model.setColumnOrder(prototype.col1, prototype.col3, prototype.col4, prototype.col5, prototype.col2);
        model.setEditable(prototype.col1, false);
        model.setEditable(prototype.col3, true);
        model.setEditable(prototype.col2, false);
        model.setEditable(prototype.col4, true);
        model.setEditable(prototype.col5, true);
        Table table = new Table(model);

        hi.add(table);
        
        myPropertyBusinessObject row3 = new myPropertyBusinessObject();
        row3.col1.set(0);
        row3.col2.set(0);
        row3.col3.set("0");
        row3.col4.set("0");
        row3.col5.set("0");
        model.addRow(3, row3);
        // model.removeRow(1);

        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

    /**
     * Returns sample data for this test case
     *
     * @return
     */
    private List<PropertyBusinessObject> getSportType() {
        List<PropertyBusinessObject> list = new ArrayList<>();
        myPropertyBusinessObject row1 = new myPropertyBusinessObject();
        myPropertyBusinessObject row2 = new myPropertyBusinessObject();
        row1.col1.set(0);
        row1.col2.set(0);
        row1.col3.set("0");
        row1.col4.set("0");
        row1.col5.set("0");
        row2.col1.set(0);
        row2.col2.set(0);
        row2.col3.set("0");
        row2.col4.set("0");
        row2.col5.set("0");
        list.add(row1);
        list.add(row2);
        return list;
    }

}

class myPropertyBusinessObject implements PropertyBusinessObject {

    public final IntProperty<myPropertyBusinessObject> col1 = new IntProperty<>("col1");
    public final IntProperty<myPropertyBusinessObject> col2 = new IntProperty<>("col2");
    public final Property<String, myPropertyBusinessObject> col3 = new Property<>("col3");
    public final Property<String, myPropertyBusinessObject> col4 = new Property<>("col4");
    public final Property<String, myPropertyBusinessObject> col5 = new Property<>("col5");

    private PropertyIndex idx = new PropertyIndex(this, "SportTypeDAO",
            col1, col2, col3, col4, col5);

    @Override
    public PropertyIndex getPropertyIndex() {
        return idx;
    }

    public myPropertyBusinessObject() {
    }

}

```

Log:
```
ant -f C:\\Users\\Francesco\\Documents\\NetBeansProjects\\TestCaseAddRow -Dnb.internal.action.name=run run
No GUI Entries available
init:
Deleting: C:\Users\Francesco\Documents\NetBeansProjects\TestCaseAddRow\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Francesco\Documents\NetBeansProjects\TestCaseAddRow\build\built-jar.properties
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
compile:
run:
ago 14, 2018 11:43:21 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:665)
	at java.util.ArrayList.add(ArrayList.java:477)
	at com.codename1.properties.UiBinding$BoundTableModel.addRow(UiBinding.java:869)
	at net.informaticalibera.apps.test.TestCase.start(TestCase.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:140)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1129)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:924)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Java Result: 1
```

**Comment by codenameone** [comment]
It's not row 3. It's row 2 as we start at 0.

**Comment by jsfan3** [comment]
You're right, thanks. However with `model.addRow(2, row3);` the row is not added to the table...

**Comment by codenameone** [comment]
Does it appear if you rotate the device back/forth? 
If so it might just be a refresh regression in the table.

**Comment by jsfan3** [comment]
No, if in the Simulator I click on "Simulate -> Rotate" two times or more, nothing is changed, the third row is not shown.

**Comment by codenameone** [comment]
OK, I'm working on the test case for this as part of the docs so I'll test both cases for add/remove

**Comment by jsfan3** [comment]
I have another info that maybe can help you in understanding this issue. I've just noted that adding:
```
table.sort(2, true);
table.setSortSupported(true);
```
the third row appears after clicking on a column header.

**Comment by codenameone** [comment]
I just wrote a test case that works great for table editing with add/remove of contacts. It might be one of the things I changed that isn't yet in your code. 
This is the test code I used: https://github.com/codenameone/PropertiesTableBindingDemo
