### ISSUE TITLE
[BUG] java.lang.ArrayIndexOutOfBoundsException in PropertiesTableBindingDemo

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2509]
Hi Shai,
I've read your blog post:
https://www.codenameone.com/blog/table-property-mapping.html

In the post you missed the link to download the code:
https://github.com/codenameone/PropertiesTableBindingDemo

However, a code fix is need. The problem is not in the PropertiesTableBindingDemo itself, but in the way you implemented the adding of a row when the table model is sortable.

To reproduce the issue, please add to your PropertiesTableBindingDemo, in the main class, these rows:
```
t.setSortSupported(true);
t.sort(0, true);
```
after `Table t = new Table(tb);`

After this change, it's impossible to add a new row. The problem is the array `private int[] sorted;` of the class `SortableTableModel`. I didn't tested the removing row, maybe you can test it after the fix. this is the log:
```
[EDT] 0:0:3,797 - Exception: java.lang.ArrayIndexOutOfBoundsException - 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at com.codename1.ui.table.SortableTableModel.getValueAt(SortableTableModel.java:119)
	at com.codename1.ui.table.Table$Listener.dataChanged(Table.java:964)
	at com.codename1.ui.util.EventDispatcher.fireDataChangeEvent(EventDispatcher.java:187)
	at com.codename1.properties.UiBinding$BoundTableModel.addRow(UiBinding.java:880)
	at com.codename1.properties.table.binding.demo.PropertiesTableDemo.lambda$start$1(PropertiesTableDemo.java:99)
	at com.codename1.ui.Command$1.actionPerformed(Command.java:332)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
	at com.codename1.ui.Button.fireActionEvent(Button.java:562)
	at com.codename1.ui.Button.released(Button.java:604)
	at com.codename1.ui.Button.pointerReleased(Button.java:708)
	at com.codename1.ui.Form.pointerReleased(Form.java:3319)
	at com.codename1.ui.Form.pointerReleased(Form.java:3280)
	at com.codename1.ui.Component.pointerReleased(Component.java:4288)
	at com.codename1.ui.Display.handleEvent(Display.java:2065)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1043)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:961)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[EDT] 0:0:7,493 - Exception: java.lang.ArrayIndexOutOfBoundsException - 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at com.codename1.ui.table.SortableTableModel.getValueAt(SortableTableModel.java:119)
	at com.codename1.ui.table.Table.updateModel(Table.java:228)
	at com.codename1.ui.table.Table.initComponent(Table.java:572)
	at com.codename1.ui.Component.initComponentImpl(Component.java:5557)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1108)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1113)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1113)
	at com.codename1.ui.Form.initComponentImpl(Form.java:1972)
	at com.codename1.ui.Display.setCurrent(Display.java:1313)
	at com.codename1.ui.Form.disposeImpl(Form.java:2208)
	at com.codename1.ui.Form.dispose(Form.java:2177)
	at com.codename1.ui.Dialog.dispose(Dialog.java:1446)
	at com.codename1.ui.Dialog.actionCommand(Dialog.java:1484)
	at com.codename1.ui.Form.actionCommandImplNoRecurseComponent(Form.java:1900)
	at com.codename1.ui.Button.fireActionEvent(Button.java:566)
	at com.codename1.ui.Button.released(Button.java:604)
	at com.codename1.ui.Button.pointerReleased(Button.java:708)
	at com.codename1.ui.Form.pointerReleased(Form.java:3259)
	at com.codename1.ui.Dialog.pointerReleased(Dialog.java:1724)
	at com.codename1.ui.Component.pointerReleased(Component.java:4288)
	at com.codename1.ui.Display.handleEvent(Display.java:2065)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1043)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1186)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1223)
	at com.codename1.ui.Form.showModal(Form.java:2132)
	at com.codename1.ui.Dialog.showModal(Dialog.java:1091)
	at com.codename1.ui.Dialog.show(Dialog.java:553)
	at com.codename1.ui.Dialog.showPackedImpl(Dialog.java:1395)
	at com.codename1.ui.Dialog.showPacked(Dialog.java:1303)
	at com.codename1.ui.Dialog.showImpl(Dialog.java:1047)
	at com.codename1.ui.Dialog.show(Dialog.java:1025)
	at com.codename1.ui.Dialog.show(Dialog.java:981)
	at com.codename1.ui.Dialog.show(Dialog.java:764)
	at com.codename1.ui.Dialog.show(Dialog.java:717)
	at com.codename1.ui.Dialog.show(Dialog.java:682)
	at com.codename1.ui.Dialog.show(Dialog.java:623)
	at com.codename1.ui.Dialog.show(Dialog.java:778)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:974)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.ArrayIndexOutOfBoundsException: 3
	at com.codename1.ui.table.SortableTableModel.getValueAt(SortableTableModel.java:119)
	at com.codename1.ui.table.Table.updateModel(Table.java:228)
	at com.codename1.ui.table.Table.initComponent(Table.java:572)
	at com.codename1.ui.Component.initComponentImpl(Component.java:5557)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1108)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1113)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1113)
	at com.codename1.ui.Form.initComponentImpl(Form.java:1972)
	at com.codename1.ui.Display.setCurrent(Display.java:1313)
	at com.codename1.ui.Form.disposeImpl(Form.java:2208)
	at com.codename1.ui.Form.dispose(Form.java:2177)
	at com.codename1.ui.Dialog.dispose(Dialog.java:1446)
	at com.codename1.ui.Dialog.actionCommand(Dialog.java:1484)
	at com.codename1.ui.Form.actionCommandImplNoRecurseComponent(Form.java:1900)
	at com.codename1.ui.Button.fireActionEvent(Button.java:566)
	at com.codename1.ui.Button.released(Button.java:604)
	at com.codename1.ui.Button.pointerReleased(Button.java:708)
	at com.codename1.ui.Form.pointerReleased(Form.java:3259)
	at com.codename1.ui.Dialog.pointerReleased(Dialog.java:1724)
	at com.codename1.ui.Component.pointerReleased(Component.java:4288)
	at com.codename1.ui.Display.handleEvent(Display.java:2065)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1043)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1186)
	at com.codename1.ui.Display.invokeAndBlock(Display.java:1223)
	at com.codename1.ui.Form.showModal(Form.java:2132)
	at com.codename1.ui.Dialog.showModal(Dialog.java:1091)
	at com.codename1.ui.Dialog.show(Dialog.java:553)
	at com.codename1.ui.Dialog.showPackedImpl(Dialog.java:1395)
	at com.codename1.ui.Dialog.showPacked(Dialog.java:1303)
	at com.codename1.ui.Dialog.showImpl(Dialog.java:1047)
	at com.codename1.ui.Dialog.show(Dialog.java:1025)
	at com.codename1.ui.Dialog.show(Dialog.java:981)
	at com.codename1.ui.Dialog.show(Dialog.java:764)
	at com.codename1.ui.Dialog.show(Dialog.java:717)
	at com.codename1.ui.Dialog.show(Dialog.java:682)
	at com.codename1.ui.Dialog.show(Dialog.java:623)
	at com.codename1.ui.Dialog.show(Dialog.java:778)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:974)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by codenameone** [comment]
There is a link in the sentence `You can check out the full project here.`. This turned out to be a bug in sort which was always there. Fixed some other issues too along the way with null appearing in fields etc.

**Comment by jsfan3** [comment]
Thank you! I'm going to try the fixed code ;)
