### ISSUE TITLE
[BUG] Simulator NullPointerException with the last sources

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2512]
After I changed the skin from iPadAir2 to the default iPhone, the simulator stopped to work. I have compiled against the Codename One sources.

As temporary workaround, I started again to use the JavaSE.jar of the current libraries instead of the one compiled by me with the current sources... however I don't know what are the downsides of this solution.

This is the error:

```
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
java.lang.NullPointerException
	at com.codename1.impl.javase.JavaSEPort.initializeCoordinates(JavaSEPort.java:1922)
	at com.codename1.impl.javase.JavaSEPort.loadSkinFile(JavaSEPort.java:2115)
	at com.codename1.impl.javase.JavaSEPort.loadSkinFile(JavaSEPort.java:3761)
	at com.codename1.impl.javase.JavaSEPort.init(JavaSEPort.java:3944)
	at com.codename1.impl.CodenameOneImplementation.initImpl(CodenameOneImplementation.java:169)
	at com.codename1.ui.Display.init(Display.java:478)
	at com.codename1.impl.javase.Executor$1.run(Executor.java:129)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Rendering frame took too long 704 milliseconds
Rendering frame took too long 311 milliseconds
Rendering frame took too long 308 milliseconds
```

**Comment by codenameone** [comment]
It looks like your source is one commit behind.
This happens when the skin file you were using couldn't be loaded. Did you delete your skin file? Did you remove the skin files from the JavaSE/src directory?

**Comment by jsfan3** [comment]
No, I didn't removed anything, in the `JavaSE/src` there is `iPhoneX.skin`.
I've seen that your submited a new commit few minutes ago, I'm going to recompile against them.

**Comment by jsfan3** [comment]
After the compiling with the last commit, the log indicates that it fails to load the skin, however the "iPhoneX.skin" in present in JavaSE/src. It's a file of 299.272 byte

```
Failed loading the skin file: /iPhoneX.skin
java.lang.NullPointerException
	at com.codename1.impl.javase.JavaSEPort.initializeCoordinates(JavaSEPort.java:1923)
	at com.codename1.impl.javase.JavaSEPort.loadSkinFile(JavaSEPort.java:2116)
	at com.codename1.impl.javase.JavaSEPort.loadSkinFile(JavaSEPort.java:3762)
	at com.codename1.impl.javase.JavaSEPort.init(JavaSEPort.java:3946)
	at com.codename1.impl.CodenameOneImplementation.initImpl(CodenameOneImplementation.java:169)
	at com.codename1.ui.Display.init(Display.java:478)
	at com.codename1.impl.javase.Executor$1.run(Executor.java:129)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
CSS> Opening JavaFX Webview to render some CSS styles
CSS> Web browser is available
[EDT] 0:0:0,165 - Codename One revisions: 84ba971c1c012f0885e484007295d439199b6da4

[EDT] 0:0:0,231 - Decoded String: http://localhost:8080
[EDT] 0:0:0,541 - I'm going to add all the persistent buttons to the side menu...
[EDT] 0:0:0,562 - Added the button Entra con FreeOTP to the side menu
CSS> Releasing lock
CSS> CSS file successfully compiled.  C:\Users\Francesco\Documents\NetBeansProjects\AppBackend\src\theme.res
CSS> Watching file C:\Users\Francesco\Documents\NetBeansProjects\AppBackend\css\theme.css for changes...
[EDT] 0:0:6,282 - cool.teammate.apps.backend.forms.Form01Login Form shown correctly
BUILD SUCCESSFUL (total time: 26 seconds)
```

**Comment by jsfan3** [comment]
The skin file in zip you linked has different size from the one in the sources. I'm going to recompile with the file you gave me.

**Comment by jsfan3** [comment]
Good news: now the Simulator started to work again!!! ;-) So my skin file was corrupted... it's strange, can you check if it's sane or corrupted in the GitHub repository?

**Comment by codenameone** [comment]
It isn't in git. You build it as part of the build process.

**Comment by jsfan3** [comment]
Currently if I use the Codename One and JavaSE projects as libraries in my Netbeans projects, an invalid iPhone.skin is produced (of 299,3kb instead of 336,8kb). The error is:
`Failed loading the skin file: /iPhoneX.skin`
