### ISSUE TITLE
[BUG] Last sources broke the Rest API

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2513]
Until few hours ago the following code worked perfectly:

```
Response<String> response = Rest.post(url)
                    .jsonContent()
                    .body(userDAO)
                    .getAsString();
```

Instead with the last sources of half hour ago, I get:

```
Exception: java.lang.NoSuchMethodError - com.codename1.io.rest.RequestBuilder.body(Lcom/codename1/properties/PropertyBusinessObject;)Lcom/codename1/io/rest/RequestBuilder;
java.lang.NoSuchMethodError: com.codename1.io.rest.RequestBuilder.body(Lcom/codename1/properties/PropertyBusinessObject;)Lcom/codename1/io/rest/RequestBuilder;
	at cool.teammate.apps.backend.server.ServerAPI_Impl.is2Fenabled(ServerAPI_Impl.java:116)
	at cool.teammate.apps.backend.forms.Form01Login.lambda$fillForm$1(Form01Login.java:70)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
	at com.codename1.ui.Button.fireActionEvent(Button.java:570)
	at com.codename1.ui.Button.released(Button.java:604)
	at com.codename1.ui.Button.pointerReleased(Button.java:708)
	at com.codename1.ui.Form.pointerReleased(Form.java:3259)
	at com.codename1.ui.Component.pointerReleased(Component.java:4288)
	at com.codename1.ui.Display.handleEvent(Display.java:2065)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1043)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:961)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
BUILD SUCCESSFUL (total time: 1 minute 20 seconds)
```

I don't know if it's releated to problems with the Simulator, as described here:
https://github.com/codenameone/CodenameOne/issues/2512

**Comment by codenameone** [comment]
The method is there and matches the signature so I suggest doing a clean build. Also verify that you don't still have the old jars in the classpath.

**Comment by jsfan3** [comment]
Solved: it was a problem of the Simulator. After solving the https://github.com/codenameone/CodenameOne/issues/2512, now the Rest API started to work again :)
