### ISSUE TITLE
Error in simulator when loading file from FileSystemStorage in BrowserComponent

### ISSUE THREAD

**Issue by meseriegh** [codenameone/CodenameOne#2605]
I have a **test.html** file under the **./cn1** folder whose content is:  `<html><button>click me</button></html>`. I want to display it using the following code:
`String filepath = FileSystemStorage.getInstance().getAppHomePath() + "test.html";`
`Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));`
`BrowserComponent html = new BrowserComponent();`
`html.setURL(filepath);`
`hi.addComponent(BorderLayout.CENTER, html);`
`hi.show();`
When I run it in simulator I get the following error:
java.lang.Throwable: File not found
	at javafx.scene.web.WebEngine$LoadWorker.describeError(WebEngine.java:1436)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1375)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.network.URLLoader.twkDidFail(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFail(URLLoader.java:862)
	at com.sun.webkit.network.URLLoader.lambda$didFail$97(URLLoader.java:845)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by codenameone** [comment]
I suggest asking in the discussion forum or stackoverlow. App home isn't in the root of the .codenameone directory and depends on the name of the app. It's unclear what you are trying to accomplish ultimately, I'm guessing you would be better served by the HTML hierarchy feature: https://www.codenameone.com/blog/html-hierarchy-release-plan-teavm.html
