### ISSUE TITLE
Gui builder editing not reflected on the respective java classes

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2613]
My saved states from the gui builder are not reflected on the respective java class. I've checked guibuilder.input, the paths are valid. There are also no errors printed when I run it over command line. I've recently initialized the codename one based project on IntelliJ IDEA. It's the first time I'm using the (new) gui builder tool.

**Comment by codenameone** [comment]
I don't understand this issue at all. Please include screeshots and a reference to the states that aren't updated.

**Comment by kutoman** [comment]
it's still not working. I suppose my client is up to date since my client got updated?

my version:

```
#
#Fri Nov 23 09:00:53 CET 2018
CodenameOne_SRCzip=48
CodenameOneJar=48
CodeNameOneBuildClientJar=13
CLDC11Jar=17
JavaSEJar=48
```

from the log file:

```
2018-11-23 08:56:19,497 [ 355784]   INFO - .intellij.ResourceEditorHelper - Designer is up to date 
2018-11-23 08:56:19,497 [ 355784]   INFO - e1.plugin.intellij.JavaProcess - Executing: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -jar /Users/SoftwareDev/.codenameone/guibuilder.jar  
2018-11-23 08:56:45,188 [ 381475]  ERROR - .impl.MessageBusConnectionImpl - null 
java.lang.NullPointerException
	at javax.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:130)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:266)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:250)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:460)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at com.codename1.build.client.GenerateGuiSources.generateGuiSource(GenerateGuiSources.java:237)
```

**Comment by shannah** [comment]
This looks like the same problem that I fixed yesterday.  Should be fixed in the next update today.

**Comment by codenameone** [comment]
This is with today's build... I think properties might be the only option.

**Comment by shannah** [comment]
That stack trace doesn't correspond with the latest changes in git.  Line 237 is `StringBuilder result = new StringBuilder();`

**Comment by codenameone** [comment]
Do we need to update the plugin too for this change to take effect?

**Comment by shannah** [comment]
We need to update the CodenameOneBuildClient.jar to solve this particular issue.
If there are other places that use JAXB, then I'll need to apply the same fix there too.

**Comment by shannah** [comment]
Did you build the CodeNameOneBuildClient project with the new dependencies?  Eg activation.jar.  These are in cn1-binaries.  I updated the project properties with these dependency changes.

**Comment by codenameone** [comment]
No. I just updated the binaries. Cleaned and built.
The problem continues even if I recompile the IDE plugin.

**Comment by shannah** [comment]
Maybe there’s something different about the way IntelliJ runs generate sources than netbeans.  I’ll look into this Monday.

**Comment by kutoman** [comment]
I suppose it's not fixed yet? When will it be fixed probably?

**Comment by codenameone** [comment]
Thanks for the reminder, this got buried a bit. We'll try to address this for this weekend.

**Comment by codenameone** [comment]
We pushed out version 5.4 of the plugin which should hopefully fix that.

**Comment by kutoman** [comment]
yes it is thanks!
