### ISSUE TITLE
Simulator fails, reading cookies for http request

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2616]
Encountering this when doing a http request. Result is that the request hangs forever because the
error bypasses the catch somewhere above it. In this case, the class being instantiated is Codename1.io.Cookie, and perhaps the underlying cause is some fallout from project jigsaw.

In any case, the catch clause didn't expect java.lang.IllegalAccessError, so it should be
added to the list of caught conditions.  I suggest this might be fixed less conservatively,
by making the catch clause Throwable rather than an explicit list of expected errors.

codename1.io.Util.java line 702 becomes:

        } catch (Throwable ex1) {
            Log.e(ex1);
            throw new IOException(ex1.getClass().getName() + ": " + ex1.getMessage());

Launcher start Fri Nov 23 11:22:53 PST 2018
java.lang.IllegalAccessError: class sun.reflect.GeneratedConstructorAccessor8 cannot access its superclass sun.reflect.ConstructorAccessorImpl
at sun.misc.Unsafe.defineClass(Native Method)
at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
at java.security.AccessController.doPrivileged(Native Method)
at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at java.lang.Class.newInstance(Class.java:442)
at com.codename1.io.Util.readObject(Util.java:690)
at com.codename1.io.Util.readObject(Util.java:660)
at com.codename1.io.Util.readObject(Util.java:660)
at com.codename1.io.Storage.readObject(Storage.java:261)
at com.codename1.impl.CodenameOneImplementation.getCookiesForURL(CodenameOneImplementation.java:4411)
at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:633)
at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by codenameone** [comment]
This exception is printed for debug purposes only. This should work but your request won't include a cookie it might need.

**Comment by codenameone** [comment]
What's `stillwaiting`?

**Comment by ddyer0** [comment]
i misremembered, its finishedWaiting in addtoqueueandwait

**Comment by ddyer0** [comment]
it does.  and many bad things ensue if there are uncaught errors that bypass this catch clause.
You can simulate it by putting a throw new exception in readObject

**Comment by codenameone** [comment]
This exception is caught

**Comment by ddyer0** [comment]
There are two similarly named exceptions, IllegalAccessError and IllegalAccessException, only one
is currently caught.
