### ISSUE TITLE
[BUG] RequestBuilder.onError actionListener is not invoked when there is a network error

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2637]
Reference: https://stackoverflow.com/questions/53610620/handle-network-thread-exceptions-in-codename-one

Test case:
```
Form hi = new Form("Hi World", BoxLayout.y());
        Button test = new Button("Test");
        test.addActionListener(e -> {
            Rest.get("https://www.codenameone.com/").
                    onError(ee -> {
                        Log.p("Connection error");
                    }).
                    fetchAsBytes(call -> {
                        Log.p("Connection ok");
                    });
        });
        hi.add(test);
        hi.show();
```

Log with wi-fi connected (tested in the Simulator):
```
[EDT] 0:0:2,434 - Codename One revisions: 39f7379dc42589c10a45315244d0013a904bfb87

[EDT] 0:0:2,434 - Connection ok
```

Log with wi-fi disconnected (tested in the Simulator) - Note that `Log.p("Connection error");` is not executed, so the onError actionListener is not executed:
```
[Network Thread] 0:0:6,301 - Codename One revisions: 39f7379dc42589c10a45315244d0013a904bfb87

[Network Thread] 0:0:6,302 - Exception: java.net.UnknownHostException - www.codenameone.com
java.net.UnknownHostException: www.codenameone.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.codename1.impl.javase.JavaSEPort.getResponseCode(JavaSEPort.java:8060)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:702)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

Please also note that the first line of the log ("Codename One revisions"), is printed by the EDT on the first case and by the Network Thread on the second case: I don't know if it's important, however it seems strange.

**Comment by codenameone** [comment]
Is this still happening?
I just verified that this works for me with the current build.
