### ISSUE TITLE
Certificate wizard error log

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2648]
````
22-Dec-2018 02:25:31.027 INFO [Thread-545] com.codename1.services.certwizard.CLIClient$2.run jRuby Home is /home/codenameone/jruby-9.1.10.0
22-Dec-2018 02:25:44.060 INFO [Thread-545] com.codename1.services.certwizard.CLIClient$2.run Two Factor Authentication for account 'pablo.gracia@gbwealthm.com' is enabled
22-Dec-2018 02:25:44.061 INFO [Thread-545] com.codename1.services.certwizard.CLIClient$2.run If you're running this in a non-interactive session (e.g. server or CI)
22-Dec-2018 02:25:44.061 INFO [Thread-545] com.codename1.services.certwizard.CLIClient$2.run check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
22-Dec-2018 02:26:30.651 INFO [Timer-277] com.codename1.services.certwizard.CLIClient$4.run null
22-Dec-2018 02:26:30.664 SEVERE [Thread-546] com.codename1.services.certwizard.CLIClient$3.run null
 java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at com.codename1.services.certwizard.CLIClient$3.run(CLIClient.java:281)

22-Dec-2018 02:26:30.782 INFO [Thread-545] com.codename1.services.certwizard.CLIClient$2.run Please enter the 6 digit code: 
22-Dec-2018 02:26:30.782 SEVERE [Thread-545] com.codename1.services.certwizard.CLIClient$2.run null
 java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:325)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at com.codename1.services.certwizard.CLIClient$2.run(CLIClient.java:264)

22-Dec-2018 02:26:30.782 SEVERE [http-nio-8443-exec-337] com.codename1.services.certwizard.CLIClient.callCLI ddef2ef1-3f3d-403b-a17e-166345426b37: Something bad happend. Exit code: 143
22-Dec-2018 02:27:24.063 WARNING [http-nio-8443-exec-304] com.codename1.services.certwizard.AuthWebSocketServer.onError Websocket error
 java.io.IOException: Unable to unwrap data, invalid status [CLOSED]
	at org.apache.tomcat.util.net.SecureNioChannel.read(SecureNioChannel.java:474)
	at org.apache.coyote.http11.upgrade.NioServletInputStream.fillReadBuffer(NioServletInputStream.java:136)
	at org.apache.coyote.http11.upgrade.NioServletInputStream.doRead(NioServletInputStream.java:80)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.read(AbstractServletInputStream.java:124)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:51)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:203)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:198)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:96)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:663)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by codenameone** [comment]
@shannah if I recall correctly this happened when there were two devices associated with the Apple account

**Comment by liannacasper** [comment]
We replaced the certificate wizard
