### ISSUE TITLE
[BUG] Network Error listener doesn't work

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2649]
The following issue is very similar to: https://github.com/codenameone/CodenameOne/issues/2637

The Network Error listener doesn't work, that means that in the following test case the `Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);` is not executed when the app is offline (tested in the Simulator).

I hope for a solution for both bugs, because at the moment I cannot handle any network error.

Test case:
```
package com.mycompany.myapp;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.NetworkManager;
import com.codename1.io.rest.Response;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.rest.Rest;
import com.codename1.ui.Button;
import com.codename1.util.OnComplete;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        NetworkManager.getInstance().addErrorListener(err -> {
            err.consume();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        Button test = new Button("Test");
        test.addActionListener(e -> {
            Rest.get("https://www.codenameone.com/").fetchAsBytes((Response<byte[]> v) -> {});
        });
        hi.add(test);
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
```

Log when offline:
```
ant -f /home/francesco/NetBeansProjects/TestConnection -Dnb.internal.action.name=run run
Generating GUI sources foo
No GUI Entries available
init:
Deleting: /home/francesco/NetBeansProjects/TestConnection/build/built-jar.properties
deps-jar:
Updating property file: /home/francesco/NetBeansProjects/TestConnection/build/built-jar.properties
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
Compiling 1 source file to /home/francesco/NetBeansProjects/TestConnection/build/tmp
Compiling 1 source file to /home/francesco/NetBeansProjects/TestConnection/build/classes
compile:
run:
Retina Scale: 1.0
[Network Thread] 0:0:4,719 - Codename One revisions: 8b451ecb7bfbe60baf91006441e7d7d9c46afe09

[Network Thread] 0:0:4,721 - Exception: java.net.UnknownHostException - www.codenameone.com
java.net.UnknownHostException: www.codenameone.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.codename1.impl.javase.JavaSEPort.getResponseCode(JavaSEPort.java:8060)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:702)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
BUILD SUCCESSFUL (total time: 11 seconds)
```

**Comment by codenameone** [comment]
FYI we don't have a release this week due to the holiday but should have one next week
