### ISSUE TITLE
RequestBuilder onError not called anymore since today

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2668]
All my requests are built with `RequestBuilder`s. Previously when there was any error (no connection, responses with code 304 etc), the callback passed through `RequestBuilder.onError` was called but this is not the case anymore. 

This might be related to #2637, which is almost a month old, but I hadn't these issues until today.

**Comment by codenameone** [comment]
If it's connected to something it's connected to #2649 was this something that started failing after the fix for #2649 ?
Do you have a test case?

**Comment by kutoman** [comment]
by recent further investigation I managed to fix it by changing the order of onError and fetch method calls.
I privously had this and it somehow didn't cause the issue mentioned here:

```
requestBuilder.acceptJson().fetchAsJsonMap(....);
requestBuilder.onErrorCodeJSON(.....);
requestBuilder.onError(.....);
```


By changing the order it has got fixed. And yes it makes more sense to keep it this way I know:

```
requestBuilder.onErrorCodeJSON(.....)
.onError(.....)
.acceptJson().fetchAsJsonMap(....);
```

**Comment by kutoman** [comment]
this is my test case:

                RequestBuilder rb = Rest.get("https://www.codenameone.com/faq.html");

                rb.onErrorCodeJSON((Response<Map> errorData) -> {
                    System.err.println("error code json");
                });
                rb.onError(ev -> {
                    System.err.println("error");
                });

                rb.acceptJson().fetchAsJsonMap(resp -> {

                    System.out.println("ok");

                });

Note: when I remove the `onErrorCodeJSON` callback, then 304 responses don't get caught by the built request but `java.io.IOException: Unreachable`s are caught by `onError` callbacks. Whereas when I add a `onErrorCodeJSON` callback then 304 responses are caught but thrown `java.io.IOException: Unreachable`s aren't caught by `onError` callbacks.

**Comment by codenameone** [comment]
OK, in that case we should throw an exception. If you invoke such methods after a fetch/get operation they should throw an exception.

**Comment by kutoman** [comment]
the order was one issue, but there is also another one I've mentioned in my comment. I had to edit my comment due to this. You might have only seen my previous comment through the email notification.

**Comment by codenameone** [comment]
You need to use both `onError` & `onErrorCode*` since these are two separate types of errors.

**Comment by kutoman** [comment]
@codenameone I think you missed the point. `java.io.IOException: Unreachable` errors aren't caught that way. This didn't happen for a while:

```
java.io.IOException: Unreachable
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:7913)
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:7961)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:623)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

it's just printed out in the console. The `RequestBuilder`  never gets notified!

**Comment by codenameone** [comment]
````java
        Form hi = new Form("Hi World", BoxLayout.y());
        Button test = new Button("Test");
        test.addActionListener(e -> {
            Rest.get("https://www.domainthatdoesntexistatall.com/").
                    onError(ee -> {
                        ee.consume();
                        Log.p("Connection error");
                    }).
                    fetchAsBytes(call -> {
                        Log.p("Connection ok");
                    });
        });
        hi.add(test);
        hi.show();
````

**Comment by kutoman** [comment]
@codenameone  exactly. But when you try this, none of the Log calls will happen:

        Form hi = new Form("Hi World", BoxLayout.y());
        Button test = new Button("Test");
        test.addActionListener(e -> {
            Rest.get("https://google.com/")
                    .onErrorCodeJSON((Response<Map> errorData) -> {
                        Log.p("Connection error: " + errorData.getResponseErrorMessage());
                    })
                    .onError(ee -> {
                        ee.consume();
                        Log.p("Connection error: " + ee.getError());
                    }).acceptJson().fetchAsJsonMap(resp -> {
                        Log.p("Connection ok");
                    });
        });
        hi.add(test);
        hi.show();

**Comment by codenameone** [comment]
I just tried it with wifi turned off and it worked.

**Comment by kutoman** [comment]
that's weird.. this is what is printed out in the console. None of the "Connection error" calls:
```

java.net.UnknownHostException: www.domainthatdoesntexistatall.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.codename1.impl.javase.JavaSEPort.getResponseCode(JavaSEPort.java:8274)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:702)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by kutoman** [comment]
or likewise on a missing wifi connection:

```
java.io.IOException: Unreachable
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:7913)
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:7961)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:623)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by kutoman** [comment]
@codenameone sorry for raising the issue again. I just want to be sure that we tested the same sample. You tried my sample where both `onErrorCodeJSON` and `onError` are set up, right? Since the sample you shared doesn't contain both error handlers I'm wondering. I'm trying to find out why the behavior is different between us..

**Comment by codenameone** [comment]
I was already looking into that. It's indeed the source of the issue. It's fixed now

**Comment by kutoman** [comment]
nice
