### ISSUE TITLE
error on android: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2676]
It's related to #2358, which happens quite often but not on every android device. 

This is the stack trace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:860)
	at com.codename1.impl.android.d.a(AndroidImplementation.java:2089)
	at com.codename1.x.w.a(Image.java:1021)
	at com.codename1.x.w.a_(Image.java:967)
	at com.codename1.x.w.c(Image.java:932)
	at com.codename1.impl.android.d$16.a(AndroidImplementation.java:7736)
	at com.codename1.x.r.b(EncodedImage.java:627)
	at com.codename1.x.r.c(EncodedImage.java:654)
	at org.igmg.app.c.a.a(ArticleEntry.java:169)
	at org.igmg.app.c.a.a(ArticleEntry.java:154)
	at org.igmg.app.c.c.a(Unknown Source:4)
	at com.codename1.y.d.run(CallbackDispatcher.java:53)
	at com.codename1.x.q.m(Display.java:1137)
	at com.codename1.x.q.k(Display.java:1081)
	at com.codename1.x.q.j(Display.java:969)
	at com.codename1.x.ai.run(RunnableWrapper.java:120)
	at com.codename1.impl.b$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:784)
```
respective code of class `ArticleEntry`:

    private Image uniformThumbnail(Image original) {
        if(original == null || targetThumbWidth == 0 || targetThumbHeight == 0) {
            System.err.println("thumbnail couldn't be scaled!");
            return null;
        }
        //log.p("image: " + original);
        //log.p("to target size: " + targetThumbWidth +"x" + targetThumbHeight);
        return original.scaled(targetThumbWidth, targetThumbHeight); // line 169 here
    }

**Comment by codenameone** [comment]
This can happen if the encoded image was pointed at invalid data e.g. a corrupt image file
