### ISSUE TITLE
 FAILED run project when use some char in Gui Builder 

### ISSUE THREAD

**Issue by fuadnassar90** [codenameone/CodenameOne#2681]
OS: Windows 10 
IDE: Netbeans 8.2
Description:
i try to use gui builder and use span label to set this text  "Hello & Word"
and run project ,
the project is FAILED and get this erorr :

`Failed to generate Gui Source with System JAXB.  Will attempt using bundled JAXB.
C:\Users\Fuad Nassar\Documents\NetBeansProjects\Test\build.xml:520: 
java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at com.codename1.build.client.GenerateGuiSources.execute(GenerateGuiSources.java:210)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
BUILD FAILED (total time: 0 seconds)`
i think the reason is to use this char '&' in SpanLabel.
Note: i tried to set text from Gui class whit SpanLabel.setText() Function and that was work 💯

**Comment by codenameone** [comment]
It looks like your build client version is out of date. Please use update client libs and try again. Also please include the content of the applicable .gui file (it's XML) that way we can see if the `&` character was encoded incorrectly.

**Comment by fuadnassar90** [comment]
i tried to update build.xml file and problem is keep,

`**Failed to generate Gui** Source with System JAXB.  Will attempt using bundled JAXB.
C:\Users\Administrator\Documents\NetBeansProjects\CodenameOne\build.xml:520: 
java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at com.codename1.build.client.GenerateGuiSources.execute(GenerateGuiSources.java:210)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
BUILD FAILED (total time: 0 seconds)
`
the .gui file is: 
`<?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="LayeredLayout" layeredLayoutPreferredWidthMM="0.0" layeredLayoutPreferredHeightMM="0.0"  autolayout="true" title="GuiComponent" scrollableY="true" name="GuiComponent">
  <component type="SpanLabel" text="Hello & Word" preferredSize="41.26984mm 19.84127mm" name="Span_Label">
    <layoutConstraint insets="auto auto auto auto" referenceComponents="-1 -1 -1 -1" referencePositions="0.0 0.0 0.0 0.0" />
  </component>
</component>
`

**Comment by fuadnassar90** [comment]
the .gui file is: 
`<?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="LayeredLayout" layeredLayoutPreferredWidthMM="0.0" layeredLayoutPreferredHeightMM="0.0"  autolayout="true" title="GuiComponent" scrollableY="true" name="GuiComponent">
  <component type="SpanLabel" text="Hello & Word" preferredSize="41.26984mm 19.84127mm" name="Span_Label">
    <layoutConstraint insets="auto auto auto auto" referenceComponents="-1 -1 -1 -1" referencePositions="0.0 0.0 0.0 0.0" />
  </component>
</component>
`

**Comment by codenameone** [comment]
The XML file is written incorrectly. This will be fixed for the next update of the GUI builder. You will need to re-save the file for this to work.
