### ISSUE TITLE
my app is not booting properly anymore(Android)

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2683]
It's linked to the `MapContainer`. I'm getting the following error on android:
```
01-23 14:23:51.664 7623-7636/org.igmg.android W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.codename1.x.g.f com.codename1.x.l.U()' on a null object reference
        at com.codename1.x.m.g(ComponentSelector.java:1785)
        at com.codename1.x.m.c(ComponentSelector.java:1733)
        at com.codename1.j.d.<init>(MapContainer.java:200)
        at com.codename1.j.d.<init>(MapContainer.java:163)
```

**Comment by shannah** [comment]
Can you try a debug build so you can provide a non-obfuscated stack trace?

**Comment by kutoman** [comment]
sure:

```
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.codename1.ui.plaf.Style com.codename1.ui.Component.getAllStyles()' on a null object reference
W/System.err:     at com.codename1.ui.ComponentSelector.getAllStyles(ComponentSelector.java:1785)
                  at com.codename1.ui.ComponentSelector.selectAllStyles(ComponentSelector.java:1733)
                  at com.codename1.googlemaps.MapContainer.<init>(MapContainer.java:200)
                  at com.codename1.googlemaps.MapContainer.<init>(MapContainer.java:163)
```

**Comment by shannah** [comment]
Is there anything logged before that.  It looks like the native map is not being created, and is returning null.  But looking at the sources, there should have been something logged about that.

**Comment by kutoman** [comment]
oh sorry .. my bad.. I must have accidently overwritten the api key since this was the reason. Thanks for the hint as it was logged!
