### ISSUE TITLE
make PropertyBusinessObject usable universally

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2687]
As long as the app is running we can make use of the storage api and `PropertyBusinessObject` instances from native code (with [native callbacks](https://www.codenameone.com/blog/native-ios-code-callbacks.html) in between). It is not working when we want to access the api from e.g. background services or widgets while the app is not running. 
I think this would be really appreciated as there are cases we want to share persisted state and esspecially when we want to reuse the same object models (`PropertyBusinessObject`s).

**Comment by codenameone** [comment]
There is no inherent block against this. What's the failure you're experiencing?

**Comment by kutoman** [comment]
a NPE is thrown when we try to load a PBO (since the `CodenameOneImplementation` instance is `null` in that moment):

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.CodenameOneImplementation.setStorageData(java.lang.Object)' on a null object reference
        at com.codename1.io.Storage.init(Storage.java:89)
        at com.codename1.io.Storage.getInstance(Storage.java:112)
        at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:680)

or on an attempt to store the object:

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.CodenameOneImplementation.setStorageData(java.lang.Object)' on a null object reference
        at com.codename1.io.Storage.init(Storage.java:89)
        at com.codename1.io.Storage.getInstance(Storage.java:112)

**Comment by codenameone** [comment]
That's storage not property business object. In this case you will need to activate Codename One from the native code. You can use 

````java
if(!Display.isInitialized()) {
     Display.init(AndroidNativeUtil.getActivity());
}
````

**Comment by kutoman** [comment]
there is still something missing. This error comes up when `Display.init(AndroidNativeUtil.getActivity()); `is invoked.

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at com.codename1.impl.android.AndroidImplementation.translatePixelForDPI(AndroidImplementation.java:1155)
        at com.codename1.impl.android.AndroidImplementation.init(AndroidImplementation.java:1072)
        at com.codename1.impl.CodenameOneImplementation.initImpl(CodenameOneImplementation.java:169)
        at com.codename1.ui.Display.init(Display.java:479)

**Comment by kutoman** [comment]
@codenameone ok I needed to `AndroidImplementation.startContext` prior to that. It seems to be working now!
