### ISSUE TITLE
problem compiling in built server

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#2688]
**this error is ocurring while I try to compile my app**

Not copying library F:\data_kdp\programs\CodenameOne\ws_codenameone\ForceSos_ua\override , it's a directory.
Not copying library F:\data_kdp\programs\CodenameOne\ws_codenameone\ForceSos_ua\lib\impl\cls , it's a directory.
Not copying library F:\data_kdp\programs\CodenameOne\ws_codenameone\ForceSos_ua\lib\impl\stubs , it's a directory.
java.io.IOException: Server returned HTTP response code: 521 for URL: https://cloud.codenameone.com/build/getData?m=loginOneBuild3&u=xxxxxxxxxx&p=xxxxxxxx
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.codename1.build.client.BuildProcess.login(BuildProcess.java:121)
	at com.codename1.build.client.CodeNameOneBuildTask.execute(CodeNameOneBuildTask.java:223)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor972.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
F:\data_kdp\programs\CodenameOne\ws_codenameone\ForceSos_ua\build.xml:338: Error in server build process
BUILD FAILED (total time: 39 seconds)

**Comment by codenameone** [comment]
This was resolved shortly after
