### ISSUE TITLE
Resources issue after saving in the GUI Builder

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2697]
Everytime when I save the state in the `GUI Builder` I get a NPE on the next device simulator run. I then need to reopen `theme.res` and resave in the `Codename One Designer` in order to fix the issue.

error:
```
java.lang.NullPointerException
	at com.codename1.ui.util.Resources.getL10N(Resources.java:819)
```

Note: I'm using Intellij IDEA

**Comment by codenameone** [comment]
Do you add a resource bundle to the CSS? What's the rest of the stack?

**Comment by kutoman** [comment]
```
java.lang.NullPointerException
	at com.codename1.ui.util.Resources.getL10N(Resources.java:819)
	at d.i.d.controller.Configuration.setLocale(Configuration.kt:12)
	at d.i.d.HUDG.init(HUDG.kt:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:134)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1138)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:933)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

object Configuration looks like this:
```
import com.codename1.ui.plaf.UIManager
import com.codename1.ui.util.Resources


object Configuration {

    lateinit var resources: Resources

    fun setLocale(locale: String) {
        //Display.getInstance().localizationManager.language
        val bundle = resources.getL10N("Main", locale)
        UIManager.getInstance().bundle = bundle
    }
}
```

my css is as simple as that:

```
#Constants {
    includeNativeBool: false;
}

Tab {
  margin: 0;
}

DuaLabelStyle1st {
  color: green;
  padding: 0.4mm;
}

DuaLabelStyle2nd {
  color: black;
  padding: 0.4mm;
}
```
I'm not sure what you mean by "adding a resource bundle to the CSS" but I'm not calling anything with respect to CSS programmatically

**Comment by kutoman** [comment]
there is also another issue. Even when I've deactivated css I still get console output concerning css when booting the simulator:

```
CSS> Retina Scale: 2.0
CSS> Input: /Users/SoftwareDev/Development/projects/IGMGhuApp/css/theme.css
CSS> Output: /Users/SoftwareDev/Development/projects/IGMGhuApp/src/theme.res
CSS> Acquiring lock on CSS checksums file /Users/SoftwareDev/Development/projects/IGMGhuApp/.cn1_css_checksums...
CSS> Lock obtained
CSS> /Users/SoftwareDev/Development/projects/IGMGhuApp/src/theme.res has been modified since it was last compiled.  Making copy at /Users/SoftwareDev/Development/projects/IGMGhuApp/css/.backups/theme.res.1549987662899.bak
CSS> Releasing lock
CSS> CSS file successfully compiled.  /Users/SoftwareDev/Development/projects/IGMGhuApp/src/theme.res
CSS> Watching file /Users/SoftwareDev/Development/projects/IGMGhuApp/css/theme.css for changes...
```

**Comment by kutoman** [comment]
the primary issue got somehow fixed (no NPE and css ignoring anymore), but the recently mentioned remains.

**Comment by kutoman** [comment]
nah.. the main issue is back again. I have currently no idea what might be the cause for this.

**Comment by kutoman** [comment]
at that moment when I get the NPE, `resources` only has one entry with key "Theme", even though my resources look like this in the Designer:

<img width="790" alt="bildschirmfoto 2019-02-13 um 17 44 31" src="https://user-images.githubusercontent.com/5825645/52728401-877abf80-2fb7-11e9-955f-9cb3f291cb7e.png">

<img width="795" alt="bildschirmfoto 2019-02-13 um 17 44 36" src="https://user-images.githubusercontent.com/5825645/52728403-88abec80-2fb7-11e9-9818-3900a5bbcaa6.png">

while debugging before NPE is thrown:

![bildschirmfoto 2019-02-13 um 17 41 48](https://user-images.githubusercontent.com/5825645/52728467-9f524380-2fb7-11e9-92fe-f19eb2ff272b.png)

**Comment by kutoman** [comment]
Note: from https://www.codenameone.com/blog/live-css-update.html I noticed that localization is missing while css is activated. I actually assumed that we still can use the localization bundles form the designer and both css and those bundles get merged. I now believe that this is not the case and the NPE is  based on that?

**Comment by codenameone** [comment]
When you use CSS it rewrites your `theme.res` file with every build. You can create a secondary resource file and do localization there. We plan to introduce a format for localization that will be based on properties file and "play nice" with the css plugin. It's not something that's scheduled yet though so we don't know when we'll get around to it.

**Comment by kutoman** [comment]
That explains the main issue, I see. Thanks for the provided workaround though
