### ISSUE TITLE
CSS font downloading not working

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2704]
I've got the following font-faces, which causes the error mentioned at the end of the post:

```
@font-face {
    font-family: "DefaultLight";
    src: url(github://googlefonts/opensans/blob/master/ttfs/OpenSans-Light.ttf);
}

@font-face {
    font-family: "DefaultBold";
    src: url(github://googlefonts/opensans/blob/master/ttfs/OpenSans-Bold.ttf);
}
```
but when I take those downloaded ttf files (OpenSans-Bold.ttf and OpenSans-Light.ttf located in the `css` folder) and put them in the `res` folder and load them accordingly with the following css no error occurs and the fonts are displayed properly in the view:

```
@font-face {
    font-family: "DefaultLight";
    src: url(res/OpenSans-Light.ttf);
}

@font-face {
    font-family: "DefaultBold";
    src: url(res/OpenSans-Bold.ttf);
}
```

Error when downloading:
```
CSS> java.awt.FontFormatException: Unsupported sfnt /Users/SoftwareDev/Development/projects/myproject/src/OpenSans-Light.ttf
CSS> 	at sun.font.TrueTypeFont.init(TrueTypeFont.java:540)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:198)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:178)
CSS> 	at sun.font.CFontManager.createFont2D(CFontManager.java:155)
CSS> 	at java.awt.Font.<init>(Font.java:615)
CSS> 	at java.awt.Font.createFont(Font.java:1056)
CSS> 	at com.codename1.ui.EditorTTFFont.refresh(EditorTTFFont.java:115)
CSS> 	at com.codename1.ui.EditorTTFFont.<init>(EditorTTFFont.java:46)
CSS> 	at com.codename1.ui.util.EditableResourcesForCSS.createTrueTypeFont(EditableResourcesForCSS.java:29)
CSS> 	at com.codename1.ui.util.Resources.loadTheme(Resources.java:1360)
CSS> 	at com.codename1.ui.util.EditableResources.loadTheme(EditableResources.java:1613)
CSS> 	at com.codename1.ui.util.Resources.openFileImpl(Resources.java:305)
CSS> 	at com.codename1.ui.util.Resources.openFile(Resources.java:271)
CSS> 	at com.codename1.ui.util.EditableResources.openFile(EditableResources.java:1483)
CSS> 	at com.codename1.designer.css.CSSTheme.loadResourceFile(CSSTheme.java:2065)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:358)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
CSS> 	at java.lang.Thread.run(Thread.java:745)
CSS> java.awt.FontFormatException: Unsupported sfnt /Users/SoftwareDev/Development/projects/IGMGhuApp/src/OpenSans-Light.ttf
CSS> 	at sun.font.TrueTypeFont.init(TrueTypeFont.java:540)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:198)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:178)
CSS> 	at sun.font.CFontManager.createFont2D(CFontManager.java:155)
CSS> 	at java.awt.Font.<init>(Font.java:615)
CSS> 	at java.awt.Font.createFont(Font.java:1056)
CSS> 	at com.codename1.ui.EditorTTFFont.refresh(EditorTTFFont.java:115)
CSS> 	at com.codename1.ui.EditorTTFFont.<init>(EditorTTFFont.java:46)
CSS> 	at com.codename1.ui.util.EditableResourcesForCSS.createTrueTypeFont(EditableResourcesForCSS.java:29)
CSS> 	at com.codename1.ui.util.Resources.loadTheme(Resources.java:1360)
CSS> 	at com.codename1.ui.util.EditableResources.loadTheme(EditableResources.java:1613)
CSS> 	at com.codename1.ui.util.Resources.openFileImpl(Resources.java:305)
CSS> 	at com.codename1.ui.util.Resources.openFile(Resources.java:271)
CSS> 	at com.codename1.ui.util.EditableResources.openFile(EditableResources.java:1483)
CSS> 	at com.codename1.designer.css.CSSTheme.loadResourceFile(CSSTheme.java:2065)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:358)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
CSS> 	at java.lang.Thread.run(Thread.java:745)
CSS> java.awt.FontFormatException: Unsupported sfnt /Users/SoftwareDev/Development/projects/IGMGhuApp/src/OpenSans-Light.ttf
CSS> 	at sun.font.TrueTypeFont.init(TrueTypeFont.java:540)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:198)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:178)
CSS> 	at sun.font.CFontManager.createFont2D(CFontManager.java:155)
CSS> 	at java.awt.Font.<init>(Font.java:615)
CSS> 	at java.awt.Font.createFont(Font.java:1056)
CSS> 	at com.codename1.ui.EditorTTFFont.refresh(EditorTTFFont.java:115)
CSS> 	at com.codename1.ui.EditorTTFFont.<init>(EditorTTFFont.java:46)
CSS> 	at com.codename1.ui.util.EditableResourcesForCSS.createTrueTypeFont(EditableResourcesForCSS.java:29)
CSS> 	at com.codename1.ui.util.Resources.loadTheme(Resources.java:1360)
CSS> 	at com.codename1.ui.util.EditableResources.loadTheme(EditableResources.java:1613)
CSS> 	at com.codename1.ui.util.Resources.openFileImpl(Resources.java:305)
CSS> 	at com.codename1.ui.util.Resources.openFile(Resources.java:271)
CSS> 	at com.codename1.ui.util.EditableResources.openFile(EditableResources.java:1483)
CSS> 	at com.codename1.designer.css.CSSTheme.loadResourceFile(CSSTheme.java:2065)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:358)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
CSS> 	at java.lang.Thread.run(Thread.java:745)
CSS> java.awt.FontFormatException: Unsupported sfnt /Users/SoftwareDev/Development/projects/IGMGhuApp/src/OpenSans-Light.ttf
CSS> 	at sun.font.TrueTypeFont.init(TrueTypeFont.java:540)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:198)
CSS> 	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:178)
CSS> 	at sun.font.CFontManager.createFont2D(CFontManager.java:155)
CSS> 	at java.awt.Font.<init>(Font.java:615)
CSS> 	at java.awt.Font.createFont(Font.java:1056)
CSS> 	at com.codename1.ui.EditorTTFFont.refresh(EditorTTFFont.java:115)
CSS> 	at com.codename1.ui.EditorTTFFont.<init>(EditorTTFFont.java:46)
CSS> 	at com.codename1.ui.util.EditableResourcesForCSS.createTrueTypeFont(EditableResourcesForCSS.java:29)
CSS> 	at com.codename1.ui.util.Resources.loadTheme(Resources.java:1360)
CSS> 	at com.codename1.ui.util.EditableResources.loadTheme(EditableResources.java:1613)
CSS> 	at com.codename1.ui.util.Resources.openFileImpl(Resources.java:305)
CSS> 	at com.codename1.ui.util.Resources.openFile(Resources.java:271)
CSS> 	at com.codename1.ui.util.EditableResources.openFile(EditableResources.java:1483)
CSS> 	at com.codename1.designer.css.CSSTheme.loadResourceFile(CSSTheme.java:2065)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:358)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
CSS> 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kutoman** [comment]
.. and now the local loading does not work either:

```
CSS> Compile of /Users/SoftwareDev/Development/projects/myproject/css/theme.css failed
CSS> java.lang.ClassCastException: [I cannot be cast to java.awt.Font
CSS> 	at com.codename1.ui.util.EditableResources.saveTheme(EditableResources.java:2013)
CSS> 	at com.codename1.ui.util.EditableResources.save(EditableResources.java:1727)
CSS> 	at com.codename1.designer.css.CSSTheme.save(CSSTheme.java:2292)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:365)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
CSS> 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by shannah** [comment]
I can't reproduce this.  Both the github and local versions work ok for me.   Perhaps a temporary network issue.

**Comment by kutoman** [comment]
hmm I've tried it periodically over 4 hours.

I also had such an error:

```
Caused by: java.awt.FontFormatException: Unsupported sfnt /var/folders/5_/2cvvkd6n509532pnbrf5ybb80000gr/T/+~JF6858868186770196817.tmp
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:540)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:198)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:178)
	at sun.font.CFontManager.createFont2D(CFontManager.java:155)
	at java.awt.Font.<init>(Font.java:615)
	at java.awt.Font.createFont0(Font.java:969)
	at java.awt.Font.createFont(Font.java:877)
	at com.codename1.impl.javase.JavaSEPort.loadTrueTypeFont(JavaSEPort.java:6333)
	... 20 more
java.io.IOException: java.awt.FontFormatException: Unsupported sfnt /var/folders/5_/2cvvkd6n509532pnbrf5ybb80000gr/T/+~JF6858868186770196817.tmp
	at com.codename1.ui.util.Resources.open(Resources.java:757)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:704)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:668)
	at com.codename1.ui.plaf.UIManager.initFirstTheme(UIManager.java:1991)
	at de.igmghacumre.duaguide.HacUmraDuaGuide.init(HacUmraDuaGuide.kt:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:134)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1138)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:933)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

I'm not sure if it's relevant but I'm developing on Mac OS X

**Comment by codenameone** [comment]
You need to convert the font to true type see: https://stackoverflow.com/questions/28711720/getting-exception-fontformatexception-unsupported-sfnt-resources-fonts-opensanse

**Comment by kutoman** [comment]
but why has it worked for @shannah without conversion ?

**Comment by shannah** [comment]
I don't know why it works for me.  I could be using a different distribution of the JDK that supports it.  I'm on MacOS also (10.13.6).  Java(TM) SE Runtime Environment 1.8.0_151-b12

**Comment by kutoman** [comment]
ok, at least it works after conversion. I suppose this issue can be closed?
