### ISSUE TITLE
css: cn1-image-align-top is missing?

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2715]
`cn1-image-align-top` seems to be missing right, as it isn't listed in the documentation either?

**Comment by codenameone** [comment]
Thanks, this will have to wait until after the code freeze though.

**Comment by kutoman** [comment]
never mind :)

**Comment by shannah** [comment]
Merged.  I also added support for this in the background attribute, so that 

~~~
background: cn1-image-align-top;
background-image: url(someimage.png);
~~~

Works also.

**Comment by kutoman** [comment]
@shannah 
I still get the following error but why?

```
CSS> java.lang.RuntimeException: Unsupported bg type attr(cn1-image-align-top)
CSS> 	at com.codename1.designer.css.CSSTheme$Element.getThemeBgType(CSSTheme.java:3729)
CSS> 	at com.codename1.designer.css.CSSTheme.updateResources(CSSTheme.java:1473)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:364)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$000(CN1CSSCLI.java:59)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:195)
```

**Comment by shannah** [comment]
Those line numbers indicate that you aren't using the latest.  I'm not sure if this change has made it into the updates yet.

**Comment by kutoman** [comment]
hmm I see
