### ISSUE TITLE
RequestBuilder can't catch java.net.ConnectException and byte stream errors

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2726]
this exception is thrown when the server is not listening (to a specific port) or not running at all.
It is relevant to handle these scenarios when e.g. the server is down for some reason

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```

Another issue I would like to mention is that I get a `Stream closed` error when a response (to `RequestBuilder` request) doesn't provide any byte stream. This error isn't caught by any error handler (`onErrorCode`*, `onError`). Such cases happen when an API responds with a `404` without any data for example. 

```
java.io.IOException: Stream closed
	at com.codename1.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:140)
	at com.codename1.io.BufferedInputStream.read1(BufferedInputStream.java:338)
	at com.codename1.io.BufferedInputStream.read(BufferedInputStream.java:445)
	at com.codename1.io.BufferedInputStream.read(BufferedInputStream.java:668)
	at com.codename1.io.Util.copyNoClose(Util.java:136)
	at com.codename1.io.Util.copyNoClose(Util.java:122)
	at com.codename1.io.Util.copy(Util.java:157)
	at com.codename1.io.Util.copy(Util.java:111)
	at com.codename1.io.Util.readInputStream(Util.java:206)
	at com.codename1.io.ConnectionRequest.readResponse(ConnectionRequest.java:1320)
	at com.codename1.io.gzip.GZConnectionRequest.readUnzipedResponse(GZConnectionRequest.java:76)
	at com.codename1.io.rest.RequestBuilder$Connection.readUnzipedResponse(RequestBuilder.java:670)
	at com.codename1.io.gzip.GZConnectionRequest.readResponse(GZConnectionRequest.java:67)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:809)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by codenameone** [comment]
onError should grab those exceptions in the current code.

**Comment by kutoman** [comment]
@codenameone unfortunately it's not. As I always set an `onError` callback for my requests. Here is the full stack trace:

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.codename1.impl.javase.JavaSEPort.getResponseCode(JavaSEPort.java:8323)
	at com.codename1.io.ConnectionRequest.performOperation(ConnectionRequest.java:714)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:282)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by codenameone** [comment]
How is that different from the previous test case which did pass?

**Comment by kutoman** [comment]
do you mean this one #2668? Actually that's a good question.. because I'm currently working on a new project (kotlin, intellij idea). I tested that test case on another project, where it did pass and still does, but in this project the same test case does not pass somehow even though your last fix is applied and viewable in the source code (`RequestBuilder.java`).

Here are the versions of the current project:
```
CodenameOne_SRCzip=62
CodenameOneJar=62
CodeNameOneBuildClientJar=16
CLDC11Jar=18
JavaSEJar=62
```

**Comment by kutoman** [comment]
ok problem solved... in my new project`failSilently` was always reset to `true` (thus the error wasn't catched normally) because there was a code snippet, which existed from the initial CN1 project creation and caused this issue. I forgot to remove:

```
        addNetworkErrorListener { err ->
            // prevent the event from propagating
            err.consume()
            if (err.error != null) {
                Log.e(err.error)
            }
            Log.sendLogAsync()
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.connectionRequest.url, "OK", null)
        }
```

**Comment by zakhdar** [comment]
Dear,
I take the liberty to reopen this ticket because I have exactly the same problem with Coderad2, when I make an external call (Rest.post(....)) if the server is offline I get an error of the type
```
[EDT] 0:0:6,666 - Exception: java.net.ConnectException - Connection refused: connect
java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at com.codename1.impl.javase.JavaSEPort.openOutputStream(JavaSEPort.java:9976)
	at com.codename1.io.ConnectionRequest.performOperationComplete(ConnectionRequest.java:875)
	at com.codename1.io.NetworkManager$NetworkThread.runCurrentRequest(NetworkManager.java:314)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:390)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

 and if I disable the network in the simulator I get the following error: 

```
[EDT] 0:0:50,636 - Exception: java.io.IOException - Unreachable
java.io.IOException: Unreachable
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:9739)
	at com.codename1.impl.javase.JavaSEPort.connect(JavaSEPort.java:9850)
	at com.codename1.io.ConnectionRequest.performOperationComplete(ConnectionRequest.java:819)
	at com.codename1.io.NetworkManager$NetworkThread.runCurrentRequest(NetworkManager.java:314)
	at com.codename1.io.NetworkManager$NetworkThread.run(NetworkManager.java:390)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

In both cases the error isn't caught by any error handler (onErrorCode*, onError),  but they are caught by the listener in the  NetworkManager (NetworkManager. getInstance().addErrorListener).

I would like to be able to catch them via the callbaks of the request because in my scenario before making the request I display an infinite progress dialog that I want to be able to remove if an exception occurs which is not possible because the error is sent back to the NetworkManager listener where I do not have access to the infinite progress dialog.
