### ISSUE TITLE
CN1 app build fails due to OutOfMemoryError

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2746]
This happens over Intellij IDEA. is there any limit for the upload size?

```
build-for-android-device
Prompting for password
Building for username: XYZ
Your build size is: 36986kb
Sending build request to the server, notice that the build might take a while to complete!
Sending build to account: XYZ
/Users/myproject/build.xml:352: java.lang.OutOfMemoryError: Java heap space
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:29)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.codename1.build.client.BuildProcess.createRequest(BuildProcess.java:253)
	at com.codename1.build.client.BuildProcess.sendS3Build(BuildProcess.java:384)
	at com.codename1.build.client.BuildProcess.sendRequestToServer(BuildProcess.java:459)
	at com.codename1.build.client.CodeNameOneBuildTask.execute(CodeNameOneBuildTask.java:505)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	... 16 more
```

**Comment by kutoman** [comment]
it's obviously a heap issue, but increasing the heap size kinda didn't help

**Comment by kutoman** [comment]
ok after restarting the ide it worked finally

**Comment by codenameone** [comment]
https://www.codenameone.com/blog/tip-intellij-idea-ram.html
