### ISSUE TITLE
Gui Builder generates code which is not executable

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2749]
**Error:**
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.codename1.ui.Container.getComponentAt(Container.java:1749)
	at com.codename1.ui.layouts.LayeredLayout$LayeredLayoutConstraint.setReferenceComponentIndices(LayeredLayout.java:1758)
	at com.codename1.ui.layouts.LayeredLayout.setReferenceComponents(LayeredLayout.java:618)
	at de.igmghacumre.duaguide.view.generated.GenExtraView.initGuiBuilderComponents(GenExtraView.java:42)
	at de.igmghacumre.duaguide.view.generated.GenExtraView.<init>(GenExtraView.java:8)
	at de.igmghacumre.duaguide.view.generated.GenExtraView.<init>(GenExtraView.java:4)
	at de.igmghacumre.duaguide.view.ExtraView.<init>(ExtraView.kt:9)
	at de.igmghacumre.duaguide.view.MainForm.showExtraView(MainForm.kt:312)
```

**GenExtraView.gui:**
```

<?xml version="1.0" encoding="UTF-8"?>

<component type="Container" layout="LayeredLayout" layeredLayoutPreferredWidthMM="0.0" layeredLayoutPreferredHeightMM="0.0"  autolayout="true" uiid="ExtraView" scrollableY="true" name="GenExtraView">
  <component type="Container" layout="BoxLayout" boxLayoutAxis="Y"  uiid="LegalNoticeArea" scrollableY="true" name="LegalNoticeArea">
    <layoutConstraint insets="0px 0px 0px 0px" referenceComponents="-1 -1 2 -1" referencePositions="0.0 0.0 1.0 0.0" />
    <component type="Label" uiid="LegalNoticeAreaTitle" text="legal_contact_title" name="ContactTitle">
    </component>
    <component type="SpanLabel" uiid="LegalNoticeAreaText" text="legal_contact_text" name="ContactText">
    </component>
    <component type="Label" uiid="LegalNoticeAreaTitle" text="legal_address_title" name="AddressTitle">
    </component>
    <component type="Label" uiid="LegalNoticeAreaTitle" text="legal_register_title" name="RegisterTitle">
    </component>
  </component>
  <component type="Container" layout="BorderLayout" borderLayoutAbsoluteCenter="false"  uiid="SocialBar" name="SocialBar">
    <layoutConstraint insets="auto 0px 0px 0px" referenceComponents="-1 -1 -1 -1" referencePositions="0.0 0.0 0.0 0.0" />
    <component type="Label" uiid="SocialBarTitle" text="title_socialbuttons" name="SocialBarTitle">
      <layoutConstraint value="North" />
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="X"  uiid="SocialButtons" name="SocialButtons">
      <layoutConstraint value="South" />
      <component type="Button" uiid="SocialButton" icon="fontImage:e157" name="LinkFB">
      </component>
      <component type="Button" uiid="SocialButton" icon="fontImage:e157" pressedIcon="fontImage:e157" name="LinkYT">
      </component>
      <component type="Button" uiid="SocialButton" icon="fontImage:e157" pressedIcon="fontImage:e157" name="LinkWebMain">
      </component>
      <component type="Button" uiid="SocialButton" icon="fontImage:e157" pressedIcon="fontImage:e157" name="LinkWebHennes">
      </component>
    </component>
  </component>
  <component type="Container" layout="BorderLayout" borderLayoutAbsoluteCenter="false"  uiid="SocialBar" name="SettingsSection">
    <layoutConstraint insets="auto 0px 0px 0px" referenceComponents="-1 -1 1 -1" referencePositions="0.0 0.0 1.0 0.0" />
    <component type="Label" uiid="SocialBarTitle" text="title_settings" name="SettingsSectionTitle">
      <layoutConstraint value="North" />
    </component>
    <component type="Container" layout="BoxLayout" boxLayoutAxis="Y"  uiid="SettingsButtons" scrollableY="false" name="SettingsButtons">
      <layoutConstraint value="South" />
    </component>
  </component>
</component>
```

**generated code (I've marked the line concerning GenExtraView.java:42):**

```
private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.LayeredLayout());
        setInlineStylesTheme(resourceObjectInstance);
        setScrollableY(true);
        setUIID("ExtraView");
                setInlineStylesTheme(resourceObjectInstance);
        setName("GenExtraView");
        addComponent(gui_LegalNoticeArea);
        gui_LegalNoticeArea.setScrollableY(true);
        gui_LegalNoticeArea.setUIID("LegalNoticeArea");
                gui_LegalNoticeArea.setInlineStylesTheme(resourceObjectInstance);
        gui_LegalNoticeArea.setName("LegalNoticeArea");
// LINE GenExtraView.java:42 is right below:       
((com.codename1.ui.layouts.LayeredLayout)gui_LegalNoticeArea.getParent().getLayout()).setInsets(gui_LegalNoticeArea, "0px 0px 0px 0px").setReferenceComponents(gui_LegalNoticeArea, "-1 -1 2 -1").setReferencePositions(gui_LegalNoticeArea, "0.0 0.0 1.0 0.0");
        gui_LegalNoticeArea.addComponent(gui_ContactTitle);
        gui_LegalNoticeArea.addComponent(gui_ContactText);
        gui_LegalNoticeArea.addComponent(gui_AddressTitle);
        gui_LegalNoticeArea.addComponent(gui_RegisterTitle);
        gui_ContactTitle.setText("legal_contact_title");
        gui_ContactTitle.setUIID("LegalNoticeAreaTitle");
                gui_ContactTitle.setInlineStylesTheme(resourceObjectInstance);
        gui_ContactTitle.setName("ContactTitle");
        gui_ContactText.setText("legal_contact_text");
        gui_ContactText.setUIID("LegalNoticeAreaText");
                gui_ContactText.setInlineStylesTheme(resourceObjectInstance);
        gui_ContactText.setName("ContactText");
        gui_AddressTitle.setText("legal_address_title");
        gui_AddressTitle.setUIID("LegalNoticeAreaTitle");
                gui_AddressTitle.setInlineStylesTheme(resourceObjectInstance);
        gui_AddressTitle.setName("AddressTitle");
        gui_RegisterTitle.setText("legal_register_title");
        gui_RegisterTitle.setUIID("LegalNoticeAreaTitle");
                gui_RegisterTitle.setInlineStylesTheme(resourceObjectInstance);
        gui_RegisterTitle.setName("RegisterTitle");
        addComponent(gui_SocialBar);
        gui_SocialBar.setUIID("SocialBar");
                gui_SocialBar.setInlineStylesTheme(resourceObjectInstance);
        gui_SocialBar.setName("SocialBar");
        ((com.codename1.ui.layouts.LayeredLayout)gui_SocialBar.getParent().getLayout()).setInsets(gui_SocialBar, "auto 0px 0px 0px").setReferenceComponents(gui_SocialBar, "-1 -1 -1 -1").setReferencePositions(gui_SocialBar, "0.0 0.0 0.0 0.0");
        gui_SocialBar.addComponent(com.codename1.ui.layouts.BorderLayout.NORTH, gui_SocialBarTitle);
        gui_SocialBar.addComponent(com.codename1.ui.layouts.BorderLayout.SOUTH, gui_SocialButtons);
        gui_SocialButtons.setUIID("SocialButtons");
                gui_SocialButtons.setInlineStylesTheme(resourceObjectInstance);
        gui_SocialButtons.setName("SocialButtons");
        gui_SocialButtons.addComponent(gui_LinkFB);
        gui_SocialButtons.addComponent(gui_LinkYT);
        gui_SocialButtons.addComponent(gui_LinkWebMain);
        gui_SocialButtons.addComponent(gui_LinkWebHennes);
        gui_LinkFB.setUIID("SocialButton");
                gui_LinkFB.setInlineStylesTheme(resourceObjectInstance);
        gui_LinkFB.setName("LinkFB");
        com.codename1.ui.FontImage.setMaterialIcon(gui_LinkFB,"\ue157".charAt(0));
        gui_LinkYT.setUIID("SocialButton");
                gui_LinkYT.setInlineStylesTheme(resourceObjectInstance);
        gui_LinkYT.setName("LinkYT");
        com.codename1.ui.FontImage.setMaterialIcon(gui_LinkYT,"\ue157".charAt(0));
        gui_LinkWebMain.setUIID("SocialButton");
                gui_LinkWebMain.setInlineStylesTheme(resourceObjectInstance);
        gui_LinkWebMain.setName("LinkWebMain");
        com.codename1.ui.FontImage.setMaterialIcon(gui_LinkWebMain,"\ue157".charAt(0));
        gui_LinkWebHennes.setUIID("SocialButton");
                gui_LinkWebHennes.setInlineStylesTheme(resourceObjectInstance);
        gui_LinkWebHennes.setName("LinkWebHennes");
        com.codename1.ui.FontImage.setMaterialIcon(gui_LinkWebHennes,"\ue157".charAt(0));
        gui_SocialBarTitle.setText("title_socialbuttons");
        gui_SocialBarTitle.setUIID("SocialBarTitle");
                gui_SocialBarTitle.setInlineStylesTheme(resourceObjectInstance);
        gui_SocialBarTitle.setName("SocialBarTitle");
        gui_SocialButtons.setUIID("SocialButtons");
                gui_SocialButtons.setInlineStylesTheme(resourceObjectInstance);
        gui_SocialButtons.setName("SocialButtons");
        addComponent(gui_SettingsSection);
        gui_SettingsSection.setUIID("SocialBar");
                gui_SettingsSection.setInlineStylesTheme(resourceObjectInstance);
        gui_SettingsSection.setName("SettingsSection");
        ((com.codename1.ui.layouts.LayeredLayout)gui_SettingsSection.getParent().getLayout()).setInsets(gui_SettingsSection, "auto 0px 0px 0px").setReferenceComponents(gui_SettingsSection, "-1 -1 1 -1").setReferencePositions(gui_SettingsSection, "0.0 0.0 1.0 0.0");
        gui_SettingsSection.addComponent(com.codename1.ui.layouts.BorderLayout.NORTH, gui_SettingsSectionTitle);
        gui_SettingsSection.addComponent(com.codename1.ui.layouts.BorderLayout.SOUTH, gui_SettingsButtons);
        gui_SettingsSectionTitle.setText("title_settings");
        gui_SettingsSectionTitle.setUIID("SocialBarTitle");
                gui_SettingsSectionTitle.setInlineStylesTheme(resourceObjectInstance);
        gui_SettingsSectionTitle.setName("SettingsSectionTitle");
        gui_SettingsButtons.setScrollableY(false);
        gui_SettingsButtons.setUIID("SettingsButtons");
                gui_SettingsButtons.setInlineStylesTheme(resourceObjectInstance);
        gui_SettingsButtons.setName("SettingsButtons");
        gui_LegalNoticeArea.setScrollableY(true);
        gui_LegalNoticeArea.setUIID("LegalNoticeArea");
                gui_LegalNoticeArea.setInlineStylesTheme(resourceObjectInstance);
        gui_LegalNoticeArea.setName("LegalNoticeArea");
        ((com.codename1.ui.layouts.LayeredLayout)gui_LegalNoticeArea.getParent().getLayout()).setInsets(gui_LegalNoticeArea, "0px 0px 0px 0px").setReferenceComponents(gui_LegalNoticeArea, "-1 -1 2 -1").setReferencePositions(gui_LegalNoticeArea, "0.0 0.0 1.0 0.0");
        gui_SocialBar.setUIID("SocialBar");
                gui_SocialBar.setInlineStylesTheme(resourceObjectInstance);
        gui_SocialBar.setName("SocialBar");
        ((com.codename1.ui.layouts.LayeredLayout)gui_SocialBar.getParent().getLayout()).setInsets(gui_SocialBar, "auto 0px 0px 0px").setReferenceComponents(gui_SocialBar, "-1 -1 -1 -1").setReferencePositions(gui_SocialBar, "0.0 0.0 0.0 0.0");
        gui_SettingsSection.setUIID("SocialBar");
                gui_SettingsSection.setInlineStylesTheme(resourceObjectInstance);
        gui_SettingsSection.setName("SettingsSection");
        ((com.codename1.ui.layouts.LayeredLayout)gui_SettingsSection.getParent().getLayout()).setInsets(gui_SettingsSection, "auto 0px 0px 0px").setReferenceComponents(gui_SettingsSection, "-1 -1 1 -1").setReferencePositions(gui_SettingsSection, "0.0 0.0 1.0 0.0");
    }
```

**Also please note that strangely this snippet here gets generated twice:**
```
gui_LegalNoticeArea.setScrollableY(true);
gui_LegalNoticeArea.setUIID("LegalNoticeArea");
```

**Comment by kutoman** [comment]
I've fixed it by cutting and repasting gui_LegalNoticeArea over the gui builder, but I think it's worth being checked anyways as this might happen under the same circumstances again.
