### ISSUE TITLE
All Javascript builds fails, even a new bare bones project

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2762]
From about an hour, all Javascript builds fails, even a new bare bones project.

This is the log of a bare bones project:
```
Executing: /home/ec2-user/jdk1.8.0_45/bin/java -Dretrolambda.inputDir=/tmp/build8788735716605901658xxx/tmpClasses -Dretrolambda.classpath=/tmp/build8788735716605901658xxx/tmpClasses:/tmp/temp6553808268453243709.jar -Dretrolambda.outputDir=/tmp/build8788735716605901658xxx/tmpClasses_retrolamda -Dretrolambda.bytecodeVersion=49 -Dretrolambda.defaultMethods=true -jar /tmp/temp8084379114287646526.jar Retrolambda 2.5.1
00:00  INFO: Bytecode version: 49 (Java 5)
00:00  INFO: Default methods:  true
00:00  INFO: Input directory:  /tmp/build8788735716605901658xxx/tmpClasses
00:00  INFO: Output directory: /tmp/build8788735716605901658xxx/tmpClasses_retrolamda
00:00  INFO: Classpath:        [/tmp/build8788735716605901658xxx/tmpClasses, /tmp/temp6553808268453243709.jar]
00:00  INFO: Included files:   all
00:00  INFO: Agent enabled:    false
00:00  INFO: Saving lambda class: net/informaticalibera/tests/MyApplication$$Lambda$2
Process return code is 0
Executing: /home/ec2-user/javascript/apache-maven-3.2.5/bin/mvn -e clean package [INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.informaticalibera:MyApplication:war:1.0
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-core:jar should not point at files within the project directory, ${basedir}/lib/CodenameOne.jar will be unresolvable by dependent projects @ line 24, column 25
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-factory:jar should not point at files within the project directory, ${basedir}/lib/Factory.jar will be unresolvable by dependent projects @ line 32, column 25
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-core-hello:jar should not point at files within the project directory, ${basedir}/lib/app.jar will be unresolvable by dependent projects @ line 40, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MyApplication 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ MyApplication ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MyApplication ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MyApplication ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 70 source files to /tmp/build8788735716605901658xxx/target/classes
[WARNING] /tmp/build8788735716605901658xxx/src/main/java/com/codename1/impl/html5/HTML5BrowserComponent.java:[22,50] com.sun.org.apache.xml.internal.serializer.ToHTMLStream is internal proprietary API and may be removed in a future release
[WARNING] /tmp/build8788735716605901658xxx/src/main/java/com/codename1/impl/html5/HTML5Implementation.java: Some input files use or override a deprecated API.
[WARNING] /tmp/build8788735716605901658xxx/src/main/java/com/codename1/impl/html5/HTML5Implementation.java: Recompile with -Xlint:deprecation for details.
[WARNING] /tmp/build8788735716605901658xxx/src/main/java/com/codename1/teavm/ext/localforage/LocalForage.java: Some input files use unchecked or unsafe operations.
[WARNING] /tmp/build8788735716605901658xxx/src/main/java/com/codename1/teavm/ext/localforage/LocalForage.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- teavm-maven-plugin:0.6.0-cn1-003:compile (web-client) @ MyApplication ---
[INFO] Preparing classpath for JavaScript generation
[INFO] Using the following classpath for JavaScript generation: /tmp/build8788735716605901658xxx/lib/CodenameOne.jar:/tmp/build8788735716605901658xxx/lib/Factory.jar:/tmp/build8788735716605901658xxx/lib/app.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-classlib/0.6.0-cn1-003/teavm-classlib-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-platform/0.6.0-cn1-003/teavm-platform-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-core/0.6.0-cn1-003/teavm-core-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-interop/0.6.0-cn1-003/teavm-interop-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/ec2-user/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar:/home/ec2-user/.m2/repository/com/carrotsearch/hppc/0.7.3/hppc-0.7.3.jar:/home/ec2-user/.m2/repository/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-jso-apis/0.6.0-cn1-003/teavm-jso-apis-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-jso-impl/0.6.0-cn1-003/teavm-jso-impl-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-metaprogramming-api/0.6.0-cn1-003/teavm-metaprogramming-api-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-metaprogramming-impl/0.6.0-cn1-003/teavm-metaprogramming-impl-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/org/ow2/asm/asm-util/7.0/asm-util-7.0.jar:/home/ec2-user/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.jar:/home/ec2-user/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar:/home/ec2-user/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.jar:/home/ec2-user/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/home/ec2-user/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/home/ec2-user/.m2/repository/joda-time/joda-time/2.7/joda-time-2.7.jar:/home/ec2-user/.m2/repository/org/teavm/teavm-jso/0.6.0-cn1-003/teavm-jso-0.6.0-cn1-003.jar:/home/ec2-user/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/ec2-user/.m2/repository/org/mitre/dsmiley/httpproxy/smiley-http-proxy-servlet/1.6/smiley-http-proxy-servlet-1.6.jar:/home/ec2-user/.m2/repository/org/apache/httpcomponents/httpclient/4.3.4/httpclient-4.3.4.jar:/home/ec2-user/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/ec2-user/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/ec2-user/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/tmp/build8788735716605901658xxx/target/classes
[INFO] Building JavaScript file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.522 s
[INFO] Finished at: 2019-04-12T15:19:22+00:00
[INFO] Final Memory: 93M/539M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.6.0-cn1-003:compile (web-client) on project MyApplication: Unexpected error occured: ArrayIndexOutOfBoundsException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.teavm:teavm-maven-plugin:0.6.0-cn1-003:compile (web-client) on project MyApplication: Unexpected error occured
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occured
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.objectweb.asm.Attribute.read(Attribute.java:130)
	at org.objectweb.asm.ClassReader.readAttribute(ClassReader.java:3293)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1723)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.teavm.parsing.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:44)
	at org.teavm.parsing.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:27)
	at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:114)
	at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:28)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:45)
	at org.teavm.parsing.resource.MapperClassHolderSource.get(MapperClassHolderSource.java:32)
	at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:42)
	at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:35)
	at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:23)
	at org.teavm.model.ClassReaderSource$2.add(ClassReaderSource.java:82)
	at org.teavm.model.ClassReaderSource$2.<init>(ClassReaderSource.java:55)
	at org.teavm.model.ClassReaderSource.lambda$getAncestors$1(ClassReaderSource.java:50)
	at org.teavm.model.ClassReaderSource$$Lambda$22/1789105088.iterator(Unknown Source)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.teavm.model.ClassReaderSource.getAncestors(ClassReaderSource.java:87)
	at org.teavm.model.ClassReaderSource.resolve(ClassReaderSource.java:91)
	at org.teavm.classlib.impl.PlatformMarkerSupport.transformProgram(PlatformMarkerSupport.java:71)
	at org.teavm.classlib.impl.PlatformMarkerSupport.transformClass(PlatformMarkerSupport.java:56)
	at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:73)
	at org.teavm.dependency.DependencyClassSource$$Lambda$15/1694072990.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:47)
	at org.teavm.dependency.DependencyAnalyzer.createClassDependency(DependencyAnalyzer.java:382)
	at org.teavm.dependency.DependencyAnalyzer$$Lambda$6/2096584765.map(Unknown Source)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:45)
	at org.teavm.dependency.DependencyAnalyzer.linkClass(DependencyAnalyzer.java:357)
	at org.teavm.dependency.DependencyGraphBuilder$1.invokeSpecial(DependencyGraphBuilder.java:652)
	at org.teavm.dependency.DependencyGraphBuilder$1.invoke(DependencyGraphBuilder.java:632)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:182)
	at org.teavm.model.instructions.InvokeInstruction.acceptVisitor(InvokeInstruction.java:69)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:287)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:129)
	at org.teavm.dependency.DependencyAnalyzer.lambda$scheduleMethodAnalysis$10(DependencyAnalyzer.java:482)
	at org.teavm.dependency.DependencyAnalyzer$$Lambda$58/851669459.run(Unknown Source)
	at org.teavm.dependency.DependencyAnalyzer.processQueue(DependencyAnalyzer.java:625)
	at org.teavm.dependency.DependencyAnalyzer.processDependencies(DependencyAnalyzer.java:652)
	at org.teavm.vm.TeaVM.build(TeaVM.java:352)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:393)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:93)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Process return code is 1
Currently 'stopOnErrors' is on.  With this enabled, even build warnings will cause the build to fail. 
Try adding the 'javascript.stopOnErrors=false' build hint and see if it builds.  
WARNING: switching stopOnErrors off may result in runtime errors, if the warnings actually fall in the execution path of the app. 
```

**Comment by shannah** [comment]
@codenameone I get the same results when using live build server.

Local builds work for me though.  I confirmed that version of JSWrapper.zip I am using has been pushed to github.  Is it possible there was a problem during deployment?

**Comment by codenameone** [comment]
I don't see what sort of problem would trigger something like that?
I pushed several updates today and did JavaScript builds in the interim, they worked so I assume the JSWrapper is up to date. Maybe the maven repo was corrupted in the cache of one of the servers?

**Comment by codenameone** [comment]
Odd, I clean built and redeployed. Seemed to fix it. No idea what happened.
