### ISSUE TITLE
NullPointerException while showing a menu

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2785]
This appears to be some sort of race condition, as it only happens rarely.
[2019/05/06 18:11:50] log request from bridge.JPopupMenu (82.19.209.248)
data=[Java cpu=27% screen=1080x2159 ppi=192 Codename1  3.09 0 The Android Project http://www.android.com/ 50.0 Linux aarch64 4.9.97] (EDT 30 threads)showing menu
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
[EDT] 0:0:0,0 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
        at com.codename1.ui.ComboBox.fireClicked(ComboBox.java:398)
        at com.codename1.ui.ComboBox.pointerReleased(ComboBox.java:477)
        at bridge.Menu.showMenu(Unknown Source:88)
        at bridge.Menu.access$000(Unknown Source:0)
        at bridge.Menu$2.run(Unknown Source:10)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:95)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1242)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1186)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1074)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:784)

The null reference seems to be to the parent, which wasn't null at the time
the code left my control.   Note that this is running in the edt loop.

Here's the code that spawned the menu:
	private void showMenu(com.codename1.ui.Container parent ,Menu jMenu,int atX,int atY)
	{	
		try {
		//showing = true;
		  ComboBox<JMenuItem>m = getMenu();
		  Dimension menuSize = m.getPreferredSize();
		  showingOn = parent;
		  showingX = Math.max(0,Math.min(atX,parent.getWidth()-G.Width(menuSize)));
		  showingY = Math.max(G.minimumFeatureSize(),Math.min(atY,parent.getHeight()-G.Height(menuSize)));
		  m.setX(showingX);
		  m.setY(showingY);
		 // menu.setSize(menuSize);
		 // G.print("Menu "+menu.getX()+" "+menu.getY() +" "+ menu.getWidth()+" "+menu.getHeight());
		  parent.removeComponent(m);	// just in case
		  parent.add(m);
		  MouseAdapter ma = getMouse();
		  m.addActionListener(ma);
		  ma.addActionListener(jMenu);
		  m.setVisible(true);
		  m.pointerReleased(showingX,showingY);
		  final com.codename1.ui.Container fp = parent;
		  fp.removeComponent(m);  
		  showingOn = null; 
		}
    	catch (ThreadDeath err) { throw err;}
		catch (Throwable err)
		{
			 Http.postError(this,"showing menu",err); 
		}
	}

**Comment by ddyer0** [comment]
Here's another instance, likely of the same problem.
data=[Java cpu=18% screen=810x1386 ppi=160 Codename1  3.91 0 The Android Project http://www.android.com/ 50.0 Linux armv8l 3.18.14-14381225-QB27028076] (EDT 11 threads)last chance error catcher
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
[EDT] 0:0:0,1 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.codename1.ui.Form.getTintColor()' on a null object reference
	at com.codename1.ui.ComboBox.fireClicked(ComboBox.java:399)
	at com.codename1.ui.ComboBox.pointerReleased(ComboBox.java:478)
	at com.codename1.ui.LeadUtil.pointerReleased(LeadUtil.java:153)
	at com.codename1.ui.Form.pointerReleased(Form.java:3727)
	at com.codename1.ui.Component.pointerReleased(Component.java:4729)
	at bridge.MasterForm.pointerReleased(Unknown Source:28)
	at com.codename1.ui.Display.handleEvent(Display.java:2324)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1216)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1134)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ddyer0** [comment]
Adding this trace to the menagerie of undeserved NullPointerExceptions deep in the guts of your code.
This is a little different because it's in a text input field rather than a menu pop-up

[2021/01/16 12:59:47] log request from JWSApplication (78.234.53.146)
data=[Java cpu=4.9% screen=2048x1536 ppi=160 deviceDPI=160 scale =1.666667  Codename1  1.92 Ios] (launcher 5 threads)Unexpected error
error is : java.lang.NullPointerException
java.lang.NullPointerException
    at com_codename1_impl_ios_IOSImplementation.stopTextEditing:410
    at com_codename1_impl_ios_IOSVirtualKeyboard.showKeyboard:69
    at com_codename1_ui_Display.setShowVirtualKeyboard:2711
    at com_codename1_ui_Form.showModal:2554
    at com_codename1_ui_Dialog.showModal:1139
    at com_codename1_ui_Dialog.show:583
    at com_codename1_ui_Dialog.showPackedImpl:1452
    at com_codename1_ui_Dialog.showPacked:1368
    at com_codename1_ui_Dialog.showImpl:1095
    at com_codename1_ui_Dialog.show:1073
    at com_codename1_ui_Dialog.show:1028
    at com_codename1_ui_Dialog.show:893
    at com_codename1_ui_Dialog.show:874
    at com_codename1_ui_Dialog.show:856
    at bridge_JOptionPane.showInputDialog:476
    at online_shared_SeatingViewer.handleUserMenu:77
    at online_shared_SeatingViewer.handleDeferredEvent:783
    at lib_DeferredEventManager.handleDeferredEvent:3359
    at online_shared_exCanvasWindow.ViewerRun:3373
    at online_shared_exPanel.runStep:1127
    at online_shared_exPanel.run:117
    at online_shared_commonRootApplet.StartLframe:87
    at util_JWSApplication.runApp:428
    at util_JWSApplication.runLogin:560
    at util_JWSApplication.runMain:141
    at util_JWSApplication.runLobby:560
    at com_tantrix_TantrixLauncher.launchLobby:115
    at com_tantrix_TantrixLauncher.doit:29
    at com_tantrix_TantrixLauncher.run:54
    at java_lang_Thread.runImpl:153

**Comment by ddyer0** [comment]
And another
[2021/01/21 15:23:50] log request from com.tantrix.TantrixLauncher (195.74.76.194)
data=[Java cpu=50% screen=768x1184 ppi=300 deviceDPI=320 scale =1.875  Codename1  1.92 0 The Android Project http://www.android.com/ 50.0 Linux i686 3.10.0+] (launcher 10 threads)outermost run
error is : java.lang.NumberFormatException: Invalid int: "__ChadronAlwaysEqualString"
java.lang.NumberFormatException: Invalid int: "__ChadronAlwaysEqualString"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at com.codename1.ui.Form.initAdPadding(Form.java:547)
	at com.codename1.ui.Form.<init>(Form.java:211)
	at com.codename1.ui.Form.<init>(Form.java:180)
	at com.codename1.ui.Form.<init>(Form.java:1344)
	at bridge.MasterForm.<init>(Unknown Source)
	at bridge.MasterForm.getMasterForm(Unknown Source)
	at bridge.MasterForm.getMasterPanel(Unknown Source)
	at bridge.Frame.init(Unknown Source)
	at bridge.Frame.<init>(Unknown Source)
	at com.tantrix.Splash.<init>(Unknown Source)
	at com.tantrix.Splash.doSplash(Unknown Source)
	at com.tantrix.TantrixLauncher.doit(Unknown Source)
	at com.tantrix.TantrixLauncher.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:819)

**Comment by ddyer0** [comment]
a lot of things of this sort have been fixed.  Will open new bugs as they appear.
