### ISSUE TITLE
"Send Javascript build" error (for a new barebones project)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2791]
Please try to "Send Javascript build" a new barebones project.
The build server gives the following error:

```
Executing: /home/ec2-user/jdk1.8.0_45/bin/java -Dretrolambda.inputDir=/tmp/build7107885482073875792xxx/tmpClasses -Dretrolambda.classpath=/tmp/build7107885482073875792xxx/tmpClasses:/tmp/temp1992069742345085508.jar -Dretrolambda.outputDir=/tmp/build7107885482073875792xxx/tmpClasses_retrolamda -Dretrolambda.bytecodeVersion=49 -Dretrolambda.defaultMethods=true -jar /tmp/temp7026550343824411369.jar Retrolambda 2.5.1
00:00  INFO: Bytecode version: 49 (Java 5)
00:00  INFO: Default methods:  true
00:00  INFO: Input directory:  /tmp/build7107885482073875792xxx/tmpClasses
00:00  INFO: Output directory: /tmp/build7107885482073875792xxx/tmpClasses_retrolamda
00:00  INFO: Classpath:        [/tmp/build7107885482073875792xxx/tmpClasses, /tmp/temp1992069742345085508.jar]
00:00  INFO: Included files:   all
00:00  INFO: Agent enabled:    false
00:00  INFO: Saving lambda class: net/informaticalibera/tests/MyApplication$$Lambda$2
Process return code is 0
Executing: /home/ec2-user/javascript/apache-maven-3.2.5/bin/mvn -e clean package [INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.informaticalibera:MyApplication:war:1.0
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-core:jar should not point at files within the project directory, ${basedir}/lib/CodenameOne.jar will be unresolvable by dependent projects @ line 24, column 25
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-factory:jar should not point at files within the project directory, ${basedir}/lib/Factory.jar will be unresolvable by dependent projects @ line 32, column 25
[WARNING] 'dependencies.dependency.systemPath' for ca.weblite:codename1-core-hello:jar should not point at files within the project directory, ${basedir}/lib/app.jar will be unresolvable by dependent projects @ line 40, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MyApplication 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ MyApplication ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MyApplication ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MyApplication ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 72 source files to /tmp/build7107885482073875792xxx/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/HTML5BrowserComponent.java:[22,50] com.sun.org.apache.xml.internal.serializer.ToHTMLStream is internal proprietary API and may be removed in a future release
[WARNING] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/HTML5Implementation.java: Some input files use or override a deprecated API.
[WARNING] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/HTML5Implementation.java: Recompile with -Xlint:deprecation for details.
[WARNING] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/teavm/ext/localforage/LocalForage.java: Some input files use unchecked or unsafe operations.
[WARNING] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/teavm/ext/localforage/LocalForage.java: Recompile with -Xlint:unchecked for details.
[INFO] 5 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/database/CursorImpl.java:[90,13] com.codename1.impl.html5.database.CursorImpl.RowImpl is not abstract and does not override abstract method wasNull() in com.codename1.db.Row
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.594 s
[INFO] Finished at: 2019-05-10T08:35:37+00:00
[INFO] Final Memory: 19M/296M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project MyApplication: Compilation failure
[ERROR] /tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/database/CursorImpl.java:[90,13] com.codename1.impl.html5.database.CursorImpl.RowImpl is not abstract and does not override abstract method wasNull() in com.codename1.db.Row
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project MyApplication: Compilation failure
/tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/database/CursorImpl.java:[90,13] com.codename1.impl.html5.database.CursorImpl.RowImpl is not abstract and does not override abstract method wasNull() in com.codename1.db.Row

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/tmp/build7107885482073875792xxx/src/main/java/com/codename1/impl/html5/database/CursorImpl.java:[90,13] com.codename1.impl.html5.database.CursorImpl.RowImpl is not abstract and does not override abstract method wasNull() in com.codename1.db.Row

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Process return code is 1
Currently 'stopOnErrors' is on.  With this enabled, even build warnings will cause the build to fail. 
Try adding the 'javascript.stopOnErrors=false' build hint and see if it builds.  
WARNING: switching stopOnErrors off may result in runtime errors, if the warnings actually fall in the execution path of the app. 
```

**Comment by codenameone** [comment]
This is due to this PR: https://github.com/codenameone/CodenameOne/pull/2755

**Comment by codenameone** [comment]
I posted a temporary workaround until @shannah can address the issue properly.

**Comment by jsfan3** [comment]
Thank you!
