### ISSUE TITLE
IntelliJ Cannot run program "*/java" when creating new project

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#2812]
Creating a new project in IntelliJ on Mac, exception when trying to generate resource file.... this gums lots of stuff up afterwards including kotlin support.

![image](https://user-images.githubusercontent.com/2677562/58196939-2af70280-7c80-11e9-839e-3e512483dd95.png)

~~~~
Error opening resource editor

java.io.IOException: Cannot run program "/Applications/IntelliJ IDEA CE.app/Contents/bin/java" (in directory "/Applications/IntelliJ IDEA CE.app/Contents/bin"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.codename1.plugin.intellij.JavaProcess.executeProcess(JavaProcess.java:52)
	at com.codename1.plugin.intellij.JavaProcess.exec(JavaProcess.java:46)
	at com.codename1.plugin.intellij.JavaProcess.exec(JavaProcess.java:30)
	at com.codename1.plugin.intellij.ResourceEditorHelper.openResourceEditorImpl(ResourceEditorHelper.java:120)
	at com.codename1.plugin.intellij.ResourceEditorHelper.openResourceEditor(ResourceEditorHelper.java:48)
	at com.codename1.plugin.intellij.ResourceEditorHelper.create(ResourceEditorHelper.java:44)
	at com.codename1.plugin.intellij.module.NewCodenameOneProject.generateResourceFile(NewCodenameOneProject.java:173)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder.createProject(CodenameOneProjectBuilder.java:116)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder$1$1.run(CodenameOneProjectBuilder.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at com.codename1.plugin.intellij.module.CodenameOneProjectBuilder$1.run(CodenameOneProjectBuilder.java:63)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:356)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:170)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:231)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$5(StartupManagerImpl.java:385)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:387)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:223)
	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:170)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$400(StartupManagerImpl.java:46)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$run$0(StartupManagerImpl.java:200)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:200)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:370)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:362)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 47 more
~~~~

**Comment by shannah** [comment]
@codenameone I ran into this issue trying to debug the iOS kotlin issue.  Can you try creating a new Hello World CN1 project and see if you get the same thing?  I committed a patch that should fix this issue, but I am unable to build the IntelliJ module due to some problem with dependencies, so I can't test it.

**Comment by codenameone** [comment]
Just tested this and it works on my machine
