### ISSUE TITLE
MapProperty<String, ListProperty<SportCareerPBO, UserDB>, UserDB> crashes the app

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2823]
I projected the data structure of the app I'm developing assuming that the following code is valid and that it makes sense to be used to and from JSON:

```
// career -> the key of the map is the season, the value of the map is a list containing a SportCareerPBO for each type of competition
    public final MapProperty<String, ListProperty<SportCareerPBO, UserDB>, UserDB> careerInfos_Profile1 = new MapProperty<>("CareerInfos_Profile1", String.class, ListProperty.class);
    public final MapProperty<String, ListProperty<SportCareerPBO, UserDB>, UserDB> careerInfos_Profile2 = new MapProperty<>("CareerInfos_Profile2", String.class, ListProperty.class);
```
`SportCareerPBO` is an interface that extends `PropertyBusinessObject`, so all the instances of `SportCareerPBO` implement also `PropertyBusinessObject`. I have several different classes that implements `SportCareerPBO`: all of them are standard `PropertyBusinessObject`, but their `Properties` are different because different sports have different infos.
`UserDB` is a standard `PropertyBusinessObject`.

I've already wrote some complex code that assumes that my two `MapProperty` are valid, but, when I run the app, it crashes with:

```
java.lang.ExceptionInInitializerError
	at cool.teammate.apps.frontend.StartPoint.init(StartPoint.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$3$1.run(Executor.java:250)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1298)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1093)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.IllegalArgumentException: the element type class needs to be a subclass of PropertyBusinessObject
	at com.codename1.properties.PropertyBase.validateCollectionType(PropertyBase.java:220)
	at com.codename1.properties.MapProperty.<init>(MapProperty.java:58)
	at cool.teammate.apps.frontend.database.UserDB.<init>(UserDB.java:204)
	at cool.teammate.apps.frontend.database.DB.<clinit>(DB.java:26)
	... 10 more
```

this exception is thrown by the following method of `PropertyBase.java`:
```
    /**
     * Validates that the collection type is valid and throws an exception otherwise
     * @param elementType the generic type of the collection
     */
    protected final void validateCollectionType(Class elementType) {
        if(elementType == null || !PropertyBusinessObject.class.isAssignableFrom(elementType)) {
            if(elementType == String.class || elementType == Integer.class ||
                elementType == Long.class  || elementType == Double.class ||
                elementType == Byte.class  || elementType == Float.class ||
                elementType == Boolean.class  || elementType == Character.class) {
                return;
            }
            throw new IllegalArgumentException(
                    "the element type class needs to be a subclass of PropertyBusinessObject");
        }
    }
}
```

In this case, the value of the `MapProperty` is a subclass of `CollectionProperty`. Is there a reason to don't allow my code? Can you make it supported?

Thank you

**Comment by codenameone** [comment]
That won't work. A property can't stand on its own without a surrounding class. You can't create it dynamically as will be required for this code to work.

You would need to create a class such as:

````java
public class SportCareerPBOList implements PropertyBusinessObject {
//...
}
````

Here you can use the list property and then refer to that class. That approach should work fine.

If this isn't enough we might need a special case property type for that e.g. MapOfLists.

**Comment by jsfan3** [comment]
Thank you, your suggestion partially worked and simplified some pieces of my code.
`MapProperty<String, SportCareerPBOList, UserDB>` is also more readable.

The implementation of `SportCareerPBOList` is:
```
public class SportCareerPBOList implements PropertyBusinessObject {

    public final ListProperty<SportCareerPBO, SportCareerPBOList> sportCareerPBOList = new ListProperty<>("sportCareerPBOList", SportCareerPBO.class);

    public final PropertyIndex idx = new PropertyIndex(this, "SportCareerPBOList",
            sportCareerPBOList
    );

    @Override
    public PropertyIndex getPropertyIndex() {
        return idx;
    }

}
```

However, while it works when the app populates the MapProperty and saves it to JSON, it fails restoring it from JSON.

I suspect that the problem is that `SportCareerPBO` is only an interface. Its code is simply:
```
public interface SportCareerPBO extends PropertyBusinessObject {
    
}
```
I used that interface instead of `PropertyBusinessObject` directly only for a semantic reason: I have a packages of classes that implements `SportCareerPBO`, each of them has a set of Properties according to the type of sport. 

So, I suppose that `userDB.getPropertyIndex().loadJSON("UserDB");` doesn't know which classes that implement `SportCareerPBO` it has to instantiate when it reads the JSON.

There is a `NullPointerException` thrown by `PropertyIndex.java` at line 369, because in the line `po.getPropertyIndex().populateFromMap((Map<String, Object>)value, recursiveType);` the `PropertyBusinessObject po` is null.

This is an example of the saved JSON:
```
{
  "CareerInfos_Profile1": {"Season-2019/20": {"sportCareerPBOList": [
    {
      "SportCareerPBO-Club": "Team 1",
      "SportCareerPBO-FinalResult": 0,
      "SportCareerPBO-NumMatches": 0,
      "SportCareerPBO-Minutes": 0,
      "SportCareerPBO-Runs": 0,
      "SportCareerPBO-Hits": 0,
    },
    {
      "SportCareerPBO-Club": "Team 1",
      "SportCareerPBO-FinalResult": 0,
      "SportCareerPBO-NumMatches": 0,
      "SportCareerPBO-Minutes": 0,
      "SportCareerPBO-Runs": 0,
      "SportCareerPBO-Hits": 0,
    },
    {
      "SportCareerPBO-Club": "Team 1",
      "SportCareerPBO-FinalResult": 0,
      "SportCareerPBO-NumMatches": 0,
      "SportCareerPBO-Minutes": 0,
      "SportCareerPBO-Runs": 0,
      "SportCareerPBO-Hits": 0,
    },
    {
      "SportCareerPBO-Club": "Team 1",
      "SportCareerPBO-FinalResult": 0,
      "SportCareerPBO-NumMatches": 0,
      "SportCareerPBO-Minutes": 0,
      "SportCareerPBO-Runs": 0,
      "SportCareerPBO-Hits": 0,
    }
  ]}},
  "CareerInfos_Profile2": {}
}
```

In this example, `SportCareerPBO` is actually an instance of `Career_Baseball` that implements `SportCareerPBO`.

Do you think that my thinking of the cause of this exception is correct?
Do you have any hint to solve it?

Thank you

**Comment by codenameone** [comment]
Using an interface in this way would be a bit problematic because restoring wouldn't know the type of the object to place there. I don't think there's a way to make that work as during restore we have no way of knowing which object to instantiate.

Typically I solved similar issues by either having one concrete class with all the needed properties or having a separate list for each business object type even if they have common ancestry.

**Comment by jsfan3** [comment]
Dear Shai,
probably my use case is not currently supported by Codename One, because if I have one concrete class with all the needed properties, it still gives a `java.lang.NullPointerException
	at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:369)`

Could you please test the following test case to find a solution? Thank you

```
    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        hi.show();

        // Populate UserDB
        UserDB userDB = new UserDB();
        SportCareerPBOList listPBO1 = new SportCareerPBOList();
        listPBO1.sportCareerPBOList.add(new SportCareerPBO());
        listPBO1.sportCareerPBOList.add(new SportCareerPBO());
        listPBO1.sportCareerPBOList.add(new SportCareerPBO());
        SportCareerPBOList listPBO2 = new SportCareerPBOList();
        listPBO2.sportCareerPBOList.add(new SportCareerPBO());
        listPBO2.sportCareerPBOList.add(new SportCareerPBO());
        listPBO2.sportCareerPBOList.add(new SportCareerPBO());
        userDB.careerInfos_Profile1.set("Season2019", listPBO1);
        userDB.careerInfos_Profile1.set("Season2018", listPBO2);
        
        // Save UserDB, it works fine
        userDB.getPropertyIndex().storeJSON("UserDB");
        
        // Restores UserDB, it throws a NullPointerException
        if (Storage.getInstance().exists("UserDB")) {
            userDB.getPropertyIndex().loadJSON("UserDB");
        }
        

    }

    public class UserDB implements PropertyBusinessObject {

        public final MapProperty<String, SportCareerPBOList, UserDB> careerInfos_Profile1 = new MapProperty<>("CareerInfos_Profile1", String.class, SportCareerPBOList.class);

        public final PropertyIndex idx = new PropertyIndex(this, "UserDB",
                careerInfos_Profile1
        );

        @Override
        public PropertyIndex getPropertyIndex() {
            return idx;
        }

    }

    public class SportCareerPBOList implements PropertyBusinessObject {

        public final ListProperty<SportCareerPBO, SportCareerPBOList> sportCareerPBOList = new ListProperty<>("sportCareerPBOList", SportCareerPBO.class);

        public final PropertyIndex idx = new PropertyIndex(this, "SportCareerPBOList",
                sportCareerPBOList
        );

        @Override
        public PropertyIndex getPropertyIndex() {
            return idx;
        }

    }

    public class SportCareerPBO implements PropertyBusinessObject {

        public final Property<String, SportCareerPBO> sport = new Property<>("SportCareerPBO-Sport", "MySport");
        public final Property<String, SportCareerPBO> club = new Property<>("SportCareerPBO-Club", "MyClub");
        public final IntProperty<SportCareerPBO> position = new IntProperty<>("SportCareerPBO-Position", 0);

        public final PropertyIndex idx = new PropertyIndex(this, "SportCareerPBO",
                sport, club, position
        );

        @Override
        public PropertyIndex getPropertyIndex() {
            return idx;
        }
    }
}

```

It logs:
```
java.lang.NullPointerException
	at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:369)
	at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:691)
	at net.informaticalibera.tests.TestCaseMap.start(TestCaseMap.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$3$1.run(Executor.java:256)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1298)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1093)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Java Result: 1
```

**Comment by codenameone** [comment]
What's the saved JSON for this?
I'll try to run this test case later today

**Comment by jsfan3** [comment]
The JSON for this test case (saved in `~/.cn1/UserDB`) is:
```
{"CareerInfos_Profile1": {
  "Season2019": {"sportCareerPBOList": [
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    },
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    },
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    }
  ]},
  "Season2018": {"sportCareerPBOList": [
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    },
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    },
    {
      "SportCareerPBO-Sport": "MySport",
      "SportCareerPBO-Position": 0,
      "SportCareerPBO-Club": "MyClub"
    }
  ]}
}}
```

**Comment by jsfan3** [comment]
I hope that a general solution can exist recursively, for example I could have a map that contains other maps, which in turn contain lists, which in turn could contain a map or a list, and so on.
I'm not saying that my app needs exceptional levels of complexity in the JSON, but surely I will need something more complex than this test case.

The alternative is to rethink and rewrite all the logic of my app data using only simple lists ... but this would eliminate the usefulness of the Java Collections and it would also make everything more difficult to organize in a manner consistent with the UI and with the meaning of the data itself.

**Comment by codenameone** [comment]
This should work, the problem is polymorphism which we can't detect on our side. I have the test case running but it's a bit of a problematic fix. I'm looking into it.

**Comment by jsfan3** [comment]
Thank you very much Shai, your fix works in my actual app.

But there is a strange fact: **while my actual app works, the test case that I reported in this discussion doesn't work**, it crashes with this log. How is it possible? I don't understand...

```
[EDT] 0:0:0,311 - Codename One revisions: b13e87ec4b137751fec556c1bf8c1d93ee77c074

[EDT] 0:0:0,314 - Exception: java.lang.InstantiationException - net.informaticalibera.tests.TestShaiFix$SportCareerPBOList
java.lang.InstantiationException: net.informaticalibera.tests.TestShaiFix$SportCareerPBOList
	at java.lang.Class.newInstance(Class.java:427)
	at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:379)
	at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:711)
[EDT] 0:0:0,324 - Exception: java.lang.RuntimeException - Can't create instanceof class: java.lang.InstantiationException: net.informaticalibera.tests.TestShaiFix$SportCareerPBOList
	at net.informaticalibera.tests.TestShaiFix.lambda$start$1(TestShaiFix.java:82)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1298)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1242)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1130)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.NoSuchMethodException: net.informaticalibera.tests.TestShaiFix$SportCareerPBOList.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 8 more
java.lang.RuntimeException: Can't create instanceof class: java.lang.InstantiationException: net.informaticalibera.tests.TestShaiFix$SportCareerPBOList
	at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:430)
	at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:711)
	at net.informaticalibera.tests.TestShaiFix.lambda$start$1(TestShaiFix.java:82)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1298)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1242)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1130)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```

**Comment by codenameone** [comment]
SportCareerPBOList isn't public or doesn't have a public constructor. If it's an inner class you need to make it public and static. Ideally it should be an outer class to avoid these nuances such as the Java auto-generated hidden constructors.

**Comment by jsfan3** [comment]
Thank you, after your suggestion the test case works :)
