### ISSUE TITLE
Offline build server 2176

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2828]
The same app works fine when built with the online build server, while it throws several exceptions and crashes when built with the offline build server 2176.

This issue started today after the fix https://github.com/codenameone/CodenameOne/issues/2823
That fix works with the online build server, but it doesn't work with the offline server.
However there are exceptions that are not related to that fix.

This is the log of the Android app when built with offline build server 2176:
```
[EDT] 0:0:0,1 - Codename One revisions: 91f049dec16f5439ccd8bf59e141efb554c9fe33

[EDT] 0:0:0,4 - Exception: java.lang.ClassCastException - net.informaticalibera.cn1.nativelogreader.NativeLogsReaderImpl cannot be cast to com.codename1.system.NativeInterface
java.lang.ClassCastException: net.informaticalibera.cn1.nativelogreader.NativeLogsReaderImpl cannot be cast to com.codename1.system.NativeInterface
        at com.codename1.system.NativeLookup.create(NativeLookup.java:82)
        at net.informaticalibera.cn1.nativelogreader.NativeLogs.initNativeLogs(NativeLogs.java:43)
        at cool.teammate.apps.frontend.StartPoint.init(StartPoint.java:67)
        at cool.teammate.apps.frontend.StartPointStub.run(StartPointStub.java:125)
        at cool.teammate.apps.frontend.StartPointStub$1.run(StartPointStub.java:106)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1247)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1042)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:776)
[EDT] 0:0:0,7 - Native Logs Reader cannot be executed in the current platform
[EDT] 0:0:0,12 - Current date and time: 7 giu 2019 2:13:41 PM
[EDT] 0:0:0,13 - Current locale: IT
[EDT] 0:0:0,13 - Current language: it
[EDT] 0:0:0,14 - The app is running on Android as native app, OS version: 7.0
[EDT] 0:0:0,15 - Exception: java.lang.ClassCastException - com.diamonddevgroup.device.DeviceNativeImpl cannot be cast to com.codename1.system.NativeInterface
java.lang.ClassCastException: com.diamonddevgroup.device.DeviceNativeImpl cannot be cast to com.codename1.system.NativeInterface
        at com.codename1.system.NativeLookup.create(NativeLookup.java:82)
        at com.diamonddevgroup.device.Device.get(Device.java:17)
        at com.diamonddevgroup.device.Device.isSupported(Device.java:31)
        at com.diamonddevgroup.device.Device.getName(Device.java:53)
        at net.informaticalibera.cn1.simpleapi.LogUtilities.logDeviceInfo(LogUtilities.java:41)
        at cool.teammate.apps.frontend.StartPoint.init(StartPoint.java:93)
        at cool.teammate.apps.frontend.StartPointStub.run(StartPointStub.java:125)
        at cool.teammate.apps.frontend.StartPointStub$1.run(StartPointStub.java:106)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1247)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1042)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:776)
[EDT] 0:0:0,18 - The device detection cannot be used

[...]

[EDT] 0:0:0,479 - DB.restoreUserDB executing
[EDT] 0:0:0,492 - Exception: java.lang.NullPointerException - Attempt to invoke interface method 'com.codename1.properties.PropertyIndex com.codename1.properties.PropertyBusinessObject.getPropertyIndex()' on a null object reference
java.lang.NullPointerException: Attempt to invoke interface method 'com.codename1.properties.PropertyIndex com.codename1.properties.PropertyBusinessObject.getPropertyIndex()' on a null object reference
        at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:368)
        at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:690)
        at cool.teammate.apps.frontend.database.DB.restoreDB(DB.java:89)
        at cool.teammate.apps.frontend.database.DB.initPersistenceDB(DB.java:55)
        at cool.teammate.apps.frontend.StartPoint.init(StartPoint.java:129)
        at cool.teammate.apps.frontend.StartPointStub.run(StartPointStub.java:125)
        at cool.teammate.apps.frontend.StartPointStub$1.run(StartPointStub.java:106)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1247)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1042)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:776)
[EDT] 0:0:0,494 - ActionListener in SendLog (EdtErrorHandler) executing...
[EDT] 0:0:0,496 - Exception: java.lang.NullPointerException - Attempt to invoke interface method 'com.codename1.properties.PropertyIndex com.codename1.properties.PropertyBusinessObject.getPropertyIndex()' on a null object reference
java.lang.NullPointerException: Attempt to invoke interface method 'com.codename1.properties.PropertyIndex com.codename1.properties.PropertyBusinessObject.getPropertyIndex()' on a null object reference
        at com.codename1.properties.PropertyIndex.populateFromMap(PropertyIndex.java:368)
        at com.codename1.properties.PropertyIndex.loadJSON(PropertyIndex.java:690)
        at cool.teammate.apps.frontend.database.DB.restoreDB(DB.java:89)
        at cool.teammate.apps.frontend.database.DB.initPersistenceDB(DB.java:55)
        at cool.teammate.apps.frontend.StartPoint.init(StartPoint.java:129)
        at cool.teammate.apps.frontend.StartPointStub.run(StartPointStub.java:125)
        at cool.teammate.apps.frontend.StartPointStub$1.run(StartPointStub.java:106)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1247)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1042)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:776)
```

**Comment by codenameone** [comment]
I don't see what could have impacted this. Is it possible the local build script you have lost the native interface sources?
This is what's missing and there was no change to that logic on our side.

**Comment by jsfan3** [comment]
Good news: solved.

I only deleted and reinstalled the build server 2176 and deleted `build` and `dist` directories. This solved the issue without any other change.

If I have further problems, I will report them.
