### ISSUE TITLE
RFE: Linux Desktop App (distribution independent)?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2835]
I read your article about ZuluFX for desktop builds: https://www.codenameone.com/blog/zulu-desktop-builds.html

Could you consider to target to Linux desktops also, perhaps in one or more distribution independent formats? For example, Snap?

I don't know how much it is easy/hard to do or if is it possible, I'm only asking. 

I found an article that describes three "distribution independent" format to distribute a Linux desktop app: Snap, Flatpak and AppImage.
https://verummeum.com/portable-package-formats/

Probably Snap is the most popular format and it has the biggest store (managed by Canonical). Currently publish proprietary software with Snapcraft (the Canonical store for Snaps) is allowed, while with Flathub (the store of Flatpak) it can be an issue.

Thank you

**Comment by shannah** [comment]
I have some unreleased stuff that I've used for distributing CN1 and Java apps as self-contained linux desktop apps internally.  It wouldn't be too hard for me to throw that onto the build server.

**Comment by jsfan3** [comment]
Thank you

**Comment by codenameone** [comment]
This will take a while as we will need to setup new servers for desktop builds on Linux. Up until now we recommended developers just take the fat JARs generated in the build and use them as Linux is so painful in terms of package management. Snap might be a decent option.

**Comment by jsfan3** [comment]
Today I've just implemented a small app that works fine on Android and on iOS. I need to run it as Linux desktop build also.
I'm not sure if I understood your suggestion "just take the fat JARs generated in the build and use them". I tried:
```
java -jar "/home/francesco/NetBeansProjects/myProjectDir/dist/MyProjectName.jar"
```
but I got an exception.

Could you please give me more detailed instructions? Thank you
```
JavaFX is loaded
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.codename1.impl.javase.Executor$3.run(Executor.java:222)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by codenameone** [comment]
I was referring to the jar that's embedded within the installed Windows or Mac OS desktop builds. That means send a build to one of these platforms then find the jar from there. 
Alternatively you can download the source of one of those builds and build the fat jar using ant. It will include all the additional desktop related sources there.

**Comment by jsfan3** [comment]
Thanks for the explanation :)

**Comment by liannacasper** [comment]
We support native linux builds now
