### ISSUE TITLE
edt not running ? 

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2872]
I'm not sure if this should be an issue, but it's worth consideration.  In the stack
trade below, the "isEdt()" assertion failed at a point where it should be guaranteed
true, under "call serially and wait".   As I read the code, the only way that could
be true is if "codenameOneRunning" is false in callSerially.    It's plausible that
a shutdown may be in progress at this point in the app, but it seems strange
that codenameOneRunning would be false while a user process is still running.

--

[online.game.Game] 0:0:0,0 - Exception: lib.ErrorX - must be in edt
lib.ErrorX: must be in edt
        at lib.G.Assert(Unknown Source)
        at lib.CachedImage.getScaledInstance(Unknown Source)
        at lib.CachedImageManager.manageCachedImages(Unknown Source)
        at online.common.exCanvas.manageCanvasCache(Unknown Source)
        at lib.RepaintManager$2.run(Unknown Source)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:95)
        at com.codename1.ui.Display.callSerially(Display.java:843)
        at com.codename1.ui.Display.callSeriallyAndWait(Display.java:932)
        at bridge.Platform.runInEdt(Unknown Source)
        at lib.RepaintManager.repaintAndOrSleep(Unknown Source)
        at online.common.exCanvas.ViewerRun(Unknown Source)
        at online.game.commonCanvas.ViewerRun(Unknown Source)
        at online.common.commonPanel.runStep(Unknown Source)
        at online.game.Game.runStep(Unknown Source)
        at online.game.Game.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:761)

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`STALE_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/STALE_REVIEW.md)).

Reporter speculates about a race during shutdown. No concrete repro and the `callSerially` codenameOneRunning check has been refactored since. Untestable.
