### ISSUE TITLE
Codenameone BrowserComponent.setProperty giving NullPointerException

### ISSUE THREAD

**Issue by uncleboni** [codenameone/CodenameOne#2964]
Until today, my code has been working great. However, I've just started getting NPE when using the Crisp CN1lib. It turns out that BrowserComponent.setProperty() is the culprit. Here is my stacktrace

java.lang.NullPointerException
    at com.codename1.impl.javase.JavaSEPort.setBrowserProperty(JavaSEPort.java:11340)
    at com.codename1.ui.BrowserComponent.setProperty(BrowserComponent.java:607)
![Screen Shot 2019-12-13 at 3 46 38 PM](https://user-images.githubusercontent.com/7860254/70801575-4c584100-1dc0-11ea-92ef-5d9ce7c97690.png)

Looks like the JavaSEPort.setBrowserProperty() is causing it. Github shows the code was edited 2 days ago so maybe something broke.

My code is pretty basic:

```
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        BrowserComponent browser = new BrowserComponent();
        browser.addWebEventListener(BrowserComponent.onLoad, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {

            }
        });
        browser.setProperty("UseWideViewPort", true);
        browser.setProperty("LoadWithOverviewMode", true);
        browser.setProperty("DatabaseEnabled", true);
        browser.setProperty("BuiltInZoomControls", true);
        browser.setProperty("DisplayZoomControls", false);
        browser.setProperty("WebContentsDebuggingEnabled", true);
        browser.setFireCallbacksOnEdt(true);
        browser.setURL("https://www.instagram.com/brianabette/");

        Form hi = new Form("Hi World", new BorderLayout());
        hi.add(BorderLayout.CENTER, browser);
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
```

Any pointers? Bug maybe?

**Comment by uncleboni** [comment]
Wrote to @codenameone  team on website chat and @shannah had this to say:

> Thanks for reporting this. I have already fixed this issue on Github. It will appear in the next update next Friday.
