### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication"

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2983]
This is a blocking bug, I cannot execute the app I'm developing on Android, starting from yesterday. Please see the chat transcript with Lianna (of your technical support).

I'm writing also here because I found a test case.

1. Create a new bare bones project.
2. Add the build hints:
```
android.buildToolsVersion=28
android.min_sdk_version=24
android.multidex=true
```
3. Build to Android
4. Run the apk, it will fail to start the app, throwing the following exception:

```
AndroidRuntime( 2064): FATAL EXCEPTION: main
01-04 14:33:37.300 E/AndroidRuntime( 2064): Process: net.informaticalibera.testmultidex, PID: 2064
01-04 14:33:37.300 E/AndroidRuntime( 2064): java.lang.RuntimeException: Unable to instantiate application android.support.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.informaticalibera.testmultidex-U5PgOOsjavtkEezDgaHzQQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.informaticalibera.testmultidex-U5PgOOsjavtkEezDgaHzQQ==/lib/arm64, /system/lib64]]
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1136)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6175)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.ActivityThread.access$1200(ActivityThread.java:236)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.os.Looper.loop(Looper.java:214)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.ActivityThread.main(ActivityThread.java:7032)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at java.lang.reflect.Method.invoke(Native Method)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
01-04 14:33:37.300 E/AndroidRuntime( 2064): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.informaticalibera.testmultidex-U5PgOOsjavtkEezDgaHzQQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.informaticalibera.testmultidex-U5PgOOsjavtkEezDgaHzQQ==/lib/arm64, /system/lib64]]
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
01-04 14:33:37.300 E/AndroidRuntime( 2064): 	... 9 more
```

**Comment by jsfan3** [comment]
After reading the documentation at the page https://developer.android.com/studio/build/multidex, I found the solution, that is to add the following build hint:
android.gradleDep=implementation 'com.android.support:multidex:1.0.3'

However, it's odd, because that dependency should be necessary only for very old Android versions. Do you have an opinion about why that build hint is necessary even for my app that supports Android 7 or later?

**Comment by shannah** [comment]
Are you certain the `android.min_sdk_version=24` build hint is being picked up?  Can you post the application manifest and gradle build files?  As far as I can tell, with min_sdk_version >=21, you shouldn't need the com.android.support:multidex dependency.

**Comment by jsfan3** [comment]
I confirm the issue repeating the steps I described above. I report the files you requested without adding the build hint `android.gradleDep=implementation 'com.android.support:multidex:1.0.3'`

build.gradle:
```
apply plugin: 'com.android.application'

buildscript {
    repositories {
     jcenter()
     mavenLocal()
      mavenCentral()
      google()
     mavenLocal()
      mavenCentral()
      google()
    }
    dependencies {
classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

android {
    compileSdkVersion 28
    buildToolsVersion '28'

    dexOptions {
        preDexLibraries = false
        incremental false
        jumboMode = true
        javaMaxHeapSize "3g"
    }
    defaultConfig {
        applicationId "net.informaticalibera.test"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 100
        versionName "1.0"
        multiDexEnabled true
    }
    sourceSets {
        main {
            aidl.srcDirs = ['src/main/java']
        }
    }

    lintOptions {
        lintOptions {
        checkReleaseBuilds false
        abortOnError false
        }
    }
    signingConfigs {
        release {
            storeFile file("keyStore")
            storePassword "xxx"
            keyAlias "Teammate"
            keyPassword "xxx"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.cfg'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
}

repositories {
    jcenter()
     mavenLocal()
      mavenCentral()
      google()
    flatDir{
              dirs 'libs'
       }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:27.+'
     implementation 'com.android.support:appcompat-v7:27.+'

 compile 'com.google.android.gms:play-services-auth:12.0.0'
 compile 'com.google.android.gms:play-services-base:12.0.0'
 compile 'com.google.android.gms:play-services-analytics:12.0.0'
 compile 'com.google.android.gms:play-services-gcm:12.0.0'
 compile 'com.google.android.gms:play-services-location:12.0.0'
 compile 'com.google.android.gms:play-services-maps:12.0.0'
 compile 'com.google.android.gms:play-services-ads:12.0.0'
}
```

AndroidManifest.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="net.informaticalibera.test"
      android:versionCode="100"
      android:versionName="1.0"
      xmlns:tools="http://schemas.android.com/tools"
      android:minSdkVersion="24"
      android:installLocation="auto">
    <uses-sdk android:minSdkVersion="24" android:targetSdkVersion="28"  />
    <supports-screens android:smallScreens="true"
          android:normalScreens="true"
          android:largeScreens="true"
          android:xlargeScreens="true"
          android:anyDensity="true" />
  <application  android:label="MultiDexApplicationTest"  android:icon="@drawable/icon"  android:name="android.support.multidex.MultiDexApplication"  android:allowBackup="true" >
<provider
          android:name="android.support.v4.content.FileProvider"
          android:authorities="${applicationId}.provider"
          android:exported="false"
          android:grantUriPermissions="true">
          <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/file_paths">
          </meta-data>
      </provider>        <uses-library android:name="org.apache.http.legacy" android:required="false" />
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>        <activity android:name="MultiDexApplicationTestStub"
                  android:theme="@style/CustomTheme"
                  android:configChanges="orientation|keyboardHidden|screenSize|smallestScreenSize|screenLayout"
                  android:launchMode="singleTop"
                  android:label="MultiDexApplicationTest">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
  <receiver android:name="com.codename1.impl.android.LocalNotificationPublisher" ></receiver>
<receiver android:name="com.codename1.location.BackgroundLocationBroadcastReceiver" ></receiver>
<service android:name="com.codename1.impl.android.BackgroundFetchHandler" android:exported="false" />
<activity android:name="com.codename1.impl.android.CodenameOneBackgroundFetchActivity" android:theme="@android:style/Theme.NoDisplay" />
<activity android:name="com.codename1.location.CodenameOneBackgroundLocationActivity" android:theme="@android:style/Theme.NoDisplay" />
<service android:name="com.codename1.location.BackgroundLocationHandler" android:exported="false" />
<service android:name="com.codename1.location.GeofenceHandler" android:exported="false" />
<service android:name="com.codename1.media.AudioService" android:exported="false" />    </application>
    <uses-feature android:name="android.hardware.touchscreen" android:required="false" />
    <uses-feature android:name="android.hardware.telephony" android:required="false" />
    <uses-permission android:name="android.permission.INTERNET" android:required="false" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:required="false" />
  </manifest>
```

**Comment by shannah** [comment]
Thanks.  I think I see the issue.  I think it is because we are setting `android:name="android.support.multidex.MultiDexApplication"` in the `<application>` tag, which explicitly references the support library.  I suspect that with API 21 and higher we don't need to explicitly extend the MultiDexApplication class anymore.  I'm having trouble getting a clear reading of the docs to confirm this, but the logic makes sense.

I'm going to try changing it so that if min SDK is 21 or higher, that we don't add that `android:name` attribute to the `<application>` tag.  And if SDK is lower than 21, we automatically add the support library dependency.  I think that should fix it.

**Comment by shannah** [comment]
I have made these changes and tested them.  Seems to work in both cases.  This will be part of the next server update on Friday.

After the server update you'll no longer need to explicitly add the support library, even if you are targeting API < 21.  The build server will automatically add it as necessary.

**Comment by jsfan3** [comment]
Thank you!

**Comment by jsfan3** [comment]
After the build server update of today, I removed both the following build hints and it compiles without issues :-)
```
codename1.arg.android.multidex=true
codename1.arg.android.gradleDep=implementation 'com.android.support\:multidex\:1.0.3'
```
