### ISSUE TITLE
[BUG] CSS `text-decoraton` is ignored

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3020]
Test case:
```
Form hi = new Form("Hi World", BoxLayout.y());
hi.add(new Label("Hi World", "ChatNumber"));
hi.show();
```

```
#Constants {
    includeNativeBool: true; 
}

ChatNumber {
    font-size: 5mm;
    font-family: "native:MainBold";
    color: red;
    text-align: center;
    text-decoraton: underline overline cn1-3d black;
}
```

Result (`text-decoraton` is ignored):
![CodenameOne Screenshot 1](https://user-images.githubusercontent.com/1997316/74197396-b7f34900-4c5f-11ea-8a8f-1dde33160725.png)

**Comment by codenameone** [comment]
I think some of those aren't supported and as a result none of this works. Did you look at the console output when saving the CSS?

**Comment by jsfan3** [comment]
According to the developer guide, `text-decoraton: underline overline cn1-3d black;` should be supported. Example of usage in the Javadoc: https://www.codenameone.com/manual/css.html#text-decoration

Console output when saving the CSS:
```
CSS> Changed detected in /home/francesco/NetBeansProjects/CSSTest/css/theme.css.  Recompiling
CSS> Updating merge file /home/francesco/NetBeansProjects/CSSTest/css/theme.css.merged
CSS> Acquiring lock on CSS checksums file /home/francesco/NetBeansProjects/CSSTest/.cn1_css_checksums...
CSS> Lock obtained
CSS> java.lang.RuntimeException: Unsupported CSS property text-decoraton
CSS> Exception occurred while parsing property text-decoraton attr(underline) attr(overline) attr(cn1-3d) attr(black)
CSS> CSS Error: Unsupported CSS property text-decoraton on line 12 col: 47 of file file:/home/francesco/NetBeansProjects/CSSTest/css/theme.css.merged
CSS> 	at com.codename1.designer.css.CSSTheme.apply(CSSTheme.java:5739)
CSS> 	at com.codename1.designer.css.CSSTheme.apply(CSSTheme.java:5848)
CSS> 	at com.codename1.designer.css.CSSTheme$2.property_(CSSTheme.java:6353)
CSS> 	at com.codename1.designer.css.CSSTheme$2.property(CSSTheme.java:6288)
CSS> 	at org.w3c.flute.parser.Parser.declaration(Parser.java:2090)
CSS> 	at org.w3c.flute.parser.Parser.styleRule(Parser.java:1436)
CSS> 	at org.w3c.flute.parser.Parser.afterImportDeclaration(Parser.java:561)
CSS> 	at org.w3c.flute.parser.Parser.parserUnit(Parser.java:498)
CSS> 	at org.w3c.flute.parser.Parser.parseStyleSheet(Parser.java:107)
CSS> 	at com.codename1.designer.css.CSSTheme.load(CSSTheme.java:6361)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:454)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$100(CN1CSSCLI.java:63)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:321)
CSS> 	at java.lang.Thread.run(Thread.java:748)
CSS> Releasing lock
CSS> CSS file successfully compiled.  /home/francesco/NetBeansProjects/CSSTest/src/theme.res
CSS> ::refresh::
CSS File css/theme.css has been updated.  Reloading styles from src/theme.res
```
