### ISSUE TITLE
Crash when reading edited theme.css file

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3097]
Since some time I regularly get the stack trace below when editing theme.css file. 

It has appeared random and usually I could undo some edits or make other changes and then it would go away. I still cannot reproduce it reliably, but it may be linked to the use of comments within the style definition (like `/* comment */`), maybe multi-line comments at the end of the definition. 

However,  since it also seems to come and go away for the same text (eg the stack trace appears, I change the text, the stack trace disappears, I change the text back again and this time no stack trace) it may also be some internal error in the css parser.

NB. I'm currently using the designer_1.jar that Steve provide in issue #3084 

Sorry I can't give more reliable feedback, but hopefully it can help find the cause anyway. 

Stack trace:
````
CSS> Changed detected in /Users/user/NetBeansProjects/myapp/css/theme.css.  Recompiling
CSS> Updating merge file /Users/user/NetBeansProjects/myapp/css/theme.css.merged
CSS> Acquiring lock on CSS checksums file /Users/user/NetBeansProjects/myapp/.cn1_css_checksums...
CSS> Lock obtained
CSS> Releasing lock
CSS> Compile of /Users/user/NetBeansProjects/myapp/css/theme.css failed
CSS> java.io.EOFException
CSS> 	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
CSS> 	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
CSS> 	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
CSS> 	at com.codename1.ui.util.Resources.loadTheme(Resources.java:1273)
CSS> 	at com.codename1.ui.util.EditableResources.loadTheme(EditableResources.java:1631)
CSS> 	at com.codename1.ui.util.Resources.openFileImpl(Resources.java:306)
CSS> 	at com.codename1.ui.util.Resources.openFile(Resources.java:272)
CSS> 	at com.codename1.ui.util.EditableResources.openFile(EditableResources.java:1501)
CSS> 	at com.codename1.designer.css.CSSTheme.loadResourceFile(CSSTheme.java:2325)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:529)
CSS> 	at com.codename1.designer.css.CN1CSSCLI.access$100(CN1CSSCLI.java:63)
CSS> 	at com.codename1.designer.css.CN1CSSCLI$2.run(CN1CSSCLI.java:321)
CSS> 	at java.lang.Thread.run(Thread.java:748)
````

**Comment by liannacasper** [comment]
This was resolved in current maven versions
