### ISSUE TITLE
TimerAreadyCancelled in media

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3227]
[EDT] 0:0:30,79 - Exception: java.lang.IllegalStateException - Timer
already cancelled.
java.lang.IllegalStateException: Timer already cancelled.
at java.util.Timer.sched(Timer.java:397)
at java.util.Timer.schedule(Timer.java:248)
at
com.codename1.impl.javase.fx.JavaFXSEPort$CodenameOneMediaPlayer.startEndMediaPoller(JavaFXSEPort.java:401)
at
com.codename1.impl.javase.fx.JavaFXSEPort$CodenameOneMediaPlayer.playInternal(JavaFXSEPort.java:614)
at
com.codename1.impl.javase.fx.JavaFXSEPort$CodenameOneMediaPlayer.playImpl(JavaFXSEPort.java:606)
at com.codename1.media.AbstractMedia.playAsync(AbstractMedia.java:249)
at com.codename1.media.AbstractMedia.playAsync(AbstractMedia.java:143)
at com.codename1.media.MediaChannel.updateTrack(MediaChannel.java:144)
at com.codename1.media.MediaChannel.play(MediaChannel.java:259)
at com.codename1.media.MediaChannel.play(MediaChannel.java:215)
at com.codename1.media.MediaChannel.play(MediaChannel.java:203)
at labs.artie.ui.media.CN1SpeakerImpl.play(CN1SpeakerImpl.java:125)
at labs.artie.ui.media.CN1MediaImpl$2.run(CN1MediaImpl.java:443)
at com.codename1.ui.Display.processSerialCalls(Display.java:1331)
at com.codename1.ui.Display.edtLoopImpl(Display.java:1274)
at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by liannacasper** [comment]
We rewrote media playback
