### ISSUE TITLE
CEF Error

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3240]
Today I tried turning on CEF now that I am in a quiet dev stage

I use Win32 JDK

I use 3 different browser components. 2 of them, usually (not always) throw the following warning in the console when started:

     Failed to get location on screen:component must be showing on the screen to determine its location

These browsers load from a local HTML string (`setPage(html, null)`). They contain HTML5 Canvases that draw stuff and also listen to clicks, drags, zooms, etc

They initially load but then crash after a few seconds (and a click) with the following error

    java.lang.StackOverflowError
	at org.cef.browser.CefBrowser_N.N_SetFocus(Native Method)
	at org.cef.browser.CefBrowser_N.setFocus(CefBrowser_N.java:447)
	at org.cef.browser.CN1CefBrowser.setFocus(CN1CefBrowser.java:52)
	at org.cef.CefClient.onGotFocus(CefClient.java:419)
        //then repeats the above lines several times
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at java.awt.Component.lightweightPaint(Component.java:3283)
	at java.awt.Container.lightweightPaint(Container.java:2058)
	at java.awt.GraphicsCallback$PeerPaintCallback.run(GraphicsCallback.java:85)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at java.awt.Component.paintAll(Component.java:3269)
	at com.codename1.impl.javase.JavaSEPort$Peer.paintOnBufferImpl(JavaSEPort.java:11906)
	at com.codename1.impl.javase.JavaSEPort$Peer.paintOnBuffer(JavaSEPort.java:11777)
	at com.codename1.impl.javase.JavaSEPort$Peer$12.run(JavaSEPort.java:12147)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I tried running NetBeans with elevated priviledges but this didn't help
    

The last browser loads a simple URL with some simple HTML. That one works

**Comment by javieranton-zz** [comment]
On Win64, it at least starts. The alignment is too far to the right and the bottom

The Simulator throws the belwo warning when first starting the app

     WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

The browser initially runs ok, but a later call to executeAndWait blocks the rendering and throws the below

    Failed to get location on screen:component must be showing on the screen to determine its location
    Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0"

**Comment by shannah** [comment]
Can you provide a minimal test case to reproduce this?

**Comment by javieranton-zz** [comment]
> 
> 
> Can you provide a minimal test case to reproduce this?

Will do

**Comment by shannah** [comment]
Fixed this a while back.  It was entering an infinite recursion of focus handlers.

**Comment by javieranton-zz** [comment]
thx. sry I went back to javaFX and forgot to provide the test case
