### ISSUE TITLE
[BUG] Valid CSS variable throws an exception

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3307]
A syntax like `border: 1pt solid var(--color-dark-gray);` is valid according to https://www.w3schools.com/css/css3_variables.asp, but it doesn't work in Codename One, since it throws `java.lang.RuntimeException: Unsupported color type 41`.

Test case:
```
#Constants {
    includeNativeBool: true; 
    
    --color-dark-gray: #393536;
}

Label {
    border: 1pt solid var(--color-dark-gray);
}
```

Stack trace:
```
java.lang.RuntimeException: Unsupported color type 41
	at com.codename1.designer.css.CSSTheme.getColorString(CSSTheme.java:6529)
	at com.codename1.designer.css.CSSTheme.getColorInt(CSSTheme.java:6428)
	at com.codename1.designer.css.CSSTheme$Border.canBeAchievedWithRoundRectBorder(CSSTheme.java:2716)
	at com.codename1.designer.css.CSSTheme$Element.requiresImageBorder(CSSTheme.java:3805)
	at com.codename1.designer.css.CSSTheme.createImageBorders(CSSTheme.java:2361)
	at com.codename1.designer.css.CN1CSSCLI.compile(CN1CSSCLI.java:538)
	at com.codename1.designer.css.CN1CSSCLI.main(CN1CSSCLI.java:394)
	at com.codename1.designer.ResourceEditorApp.main(ResourceEditorApp.java:556)
```

**Comment by jsfan3** [comment]
I don't know if it matters, anyway I have CEF enabled.

**Comment by shannah** [comment]
This is fixed in the latest.
