### ISSUE TITLE
Error with svg Generated code using flamingo transcoder

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3314]
java.lang.RuntimeException: Transforms not supported
java.lang.RuntimeException: Transforms not supported
[EDT] 0:2:58,154 - Exception: java.lang.RuntimeException - Transforms not supported
	at com.codename1.impl.CodenameOneImplementation.makeTransformAffine(CodenameOneImplementation.java:6110)
	at com.codename1.ui.Transform.makeAffine(Transform.java:428)
	at com.codename1.ui.geom.AffineTransform.toTransform(AffineTransform.java:351)
	at com.geotracksolutionsint.forcesos.svg.Location.paint(Location.java:154)
	at com.geotracksolutionsint.forcesos.svg.Location.drawImage(Location.java:117)
	at com.codename1.ui.Graphics.drawImage(Graphics.java:660)
	at com.codename1.ui.Component$BGPainter.paint(Component.java:7179)
	at com.codename1.ui.Component.paintBackgroundImpl(Component.java:2673)
	at com.codename1.ui.Component.paintComponentBackground(Component.java:2631)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2245)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Container.paint(Container.java:1786)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2261)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Container.paint(Container.java:1786)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2261)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Container.paint(Container.java:1786)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2261)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Container.paint(Container.java:1786)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2261)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Container.paint(Container.java:1786)
	at com.codename1.ui.Form.paint(Form.java:4408)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:2261)
	at com.codename1.ui.Form.internalPaintImpl(Form.java:4418)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:2234)
	at com.codename1.ui.Component.paintInternal(Component.java:2209)
	at com.codename1.ui.Component.paintInternal(Component.java:2177)
	at com.codename1.ui.Component.paintComponent(Component.java:2474)
	at com.codename1.ui.Component.paintComponent(Component.java:2418)
	at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:625)
	at com.codename1.impl.javase.JavaSEPort.paintDirty(JavaSEPort.java:2107)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1253)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

I attached the genereted code

Generated java code by flamingo
[Location.txt](https://github.com/codenameone/CodenameOne/files/5599141/Location.txt)

renamed by . svg
[Location_svg.txt](https://github.com/codenameone/CodenameOne/files/5599142/Location_svg.txt)

**Comment by DurankGts** [comment]
...
