### ISSUE TITLE
Exception when prompting for password

### ISSUE THREAD

**Issue by shannah** [codenameone/CodenameOne#3322]
I get this occasionally when sending a build.

~~~~
/Users/shannah/cn1_files/tests/WebPushTest/build.xml:343: 
java.lang.NoClassDefFoundError: com/codename1/build/client/PromptLoginDialog
	at com.codename1.build.client.CodeNameOneBuildTask.execute(CodeNameOneBuildTask.java:185)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor634.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:574)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:128)
Caused by: java.lang.ClassNotFoundException: com.codename1.build.client.PromptLoginDialog
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1362)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1313)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
~~~~

If I resend the build, it sends fine.

This is not a new issue, it has been happening for years, but haven't filed an issue on it before.

**Comment by shai-almog** [comment]
This happens when a build is sent and an update is available on the servers. It's a result of replacing the libraries that are built against while they're running. I'm not sure if there's a decent workaround for this.
