### ISSUE TITLE
Exception in GUI Builder

### ISSUE THREAD

**Issue by liannacasper** [codenameone/CodenameOne#3329]
java.lang.ClassCastException: com.codename1.ui.layouts.FlowLayout cannot be cast to com.codename1.ui.layouts.LayeredLayout
        at com.codename1.guibuilder.layeredlayout.Canvas.<init>(Canvas.java:108)
        at com.codename1.guibuilder.layeredlayout.Canvas.<init>(Canvas.java:96)
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.createCanvas(LayeredLayoutEditorKit.java:673)
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.canvasWrapper(LayeredLayoutEditorKit.java:780)
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.getEditorComponent(LayeredLayoutEditorKit.java:823)
        at com.codename1.apps.guibuilder.GUIBuilderForm.openEditorForDocument(GUIBuilderForm.java:1256)
        at com.codename1.apps.guibuilder.GUIBuilderForm.openEditorForComponent(GUIBuilderForm.java:1345)
        at com.codename1.apps.guibuilder.GUIBuilderForm.refreshEditorDocuments(GUIBuilderForm.java:1395)
        at com.codename1.apps.guibuilder.GUIBuilderForm.lambda$init$5(GUIBuilderForm.java:914)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1338)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1280)
        at com.codename1.ui.Display.invokeAndBlock(Display.java:1453)
        at com.codename1.ui.Display.invokeAndBlock(Display.java:1492)
        at com.codename1.impl.javase.fx.JavaFXSEPort.createFXBrowserComponent(JavaFXSEPort.java:1120)
        at com.codename1.impl.javase.fx.JavaFXSEPort.createBrowserComponent(JavaFXSEPort.java:1166)
        at com.codename1.ui.BrowserComponent$9.run(BrowserComponent.java:557)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1338)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1280)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by shannah** [comment]
Can you provide some more context?  It looks like it is in autolayout mode but the form is using a FlowLayout.  How did it get into that state?

**Comment by liannacasper** [comment]
It's from the crash report system so there's no additional context.

**Comment by liannacasper** [comment]
Two additional similar exceptions from the logs:

````
EDT] 0:11:25,730 - Exception: java.lang.ClassCastException - com.codename1.apps.guibuilder.fake.FakeTabs$FakeTabsLayout cannot be cast to com.codename1.ui.layouts.LayeredLayout
java.lang.ClassCastException: com.codename1.apps.guibuilder.fake.FakeTabs$FakeTabsLayout cannot be cast to com.codename1.ui.layouts.LayeredLayout
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.wrapConstraintChangeEvent(LayeredLayoutEditorKit.java:1246)
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.fireConstraintChange(LayeredLayoutEditorKit.java:1327)
        at com.codename1.guibuilder.layeredlayout.Widget.fireWidgetConstraintChange(Widget.java:1204)
        at com.codename1.guibuilder.layeredlayout.Widget.keyReleased(Widget.java:275)
        at com.codename1.ui.Form.keyReleased(Form.java:3171)
        at com.codename1.ui.Display.handleEvent(Display.java:2309)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1244)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
````

````
[EDT] 0:11:25,875 - Exception: java.lang.ClassCastException - com.codename1.apps.guibuilder.fake.FakeTabs$FakeTabsLayout cannot be cast to com.codename1.ui.layouts.LayeredLayout
java.lang.ClassCastException: com.codename1.apps.guibuilder.fake.FakeTabs$FakeTabsLayout cannot be cast to com.codename1.ui.layouts.LayeredLayout
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.wrapConstraintChangeEvent(LayeredLayoutEditorKit.java:1246)
        at com.codename1.guibuilder.layeredlayout.LayeredLayoutEditorKit.fireConstraintChange(LayeredLayoutEditorKit.java:1327)
        at com.codename1.guibuilder.layeredlayout.Widget.fireWidgetConstraintChange(Widget.java:1204)
        at com.codename1.guibuilder.layeredlayout.Widget.keyReleased(Widget.java:275)
        at com.codename1.ui.Form.keyReleased(Form.java:3171)
        at com.codename1.ui.Display.handleEvent(Display.java:2309)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1244)
        at com.codename1.ui.Display.invokeAndBlock(Display.java:1453)
        at com.codename1.ui.Display.invokeAndBlock(Display.java:1492)
        at com.codename1.io.NetworkManager.addToQueueAndWait(NetworkManager.java:737)
        at com.codename1.io.Log.sendLogImpl(Log.java:242)
        at com.codename1.io.Log.sendLog(Log.java:198)
        at com.codename1.apps.guibuilder.GUIBuilder$1.actionPerformed(GUIBuilder.java:76)
        at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1173)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
````
