### ISSUE TITLE
Settings app crash log

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3336]
Don't know if this is a bug:

```
[Thread-1] 0:0:0,7 - Getting login
[EDT] 0:0:1,146 - Getting builds
[EDT] 0:0:54,952 - Exception: java.lang.RuntimeException - Failed to create CEF browser
java.lang.RuntimeException: Failed to create CEF browser
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:123)
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createBrowserComponent(JavaCEFSEPort.java:98)
        at com.codename1.ui.BrowserComponent$9.run(BrowserComponent.java:557)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1338)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1280)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1373)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:116)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/cef/browser/CN1CefBrowserFactory
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:129)
        at com.codename1.impl.javase.cef.JavaCEFSEPort$2.run(JavaCEFSEPort.java:119)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.cef.browser.CN1CefBrowserFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 15 more
[EDT] 0:0:54,952 - Settings Exception in version 6.81
[EDT] 0:0:54,952 - OS win
[EDT] 0:0:54,952 - Error java.lang.RuntimeException: Failed to create CEF browser
[EDT] 0:0:54,952 - Current Form null
[EDT] 0:0:54,952 - Exception: java.lang.RuntimeException - Failed to create CEF browser
java.lang.RuntimeException: Failed to create CEF browser
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:123)
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createBrowserComponent(JavaCEFSEPort.java:98)
        at com.codename1.ui.BrowserComponent$9.run(BrowserComponent.java:557)
        at com.codename1.ui.Display.processSerialCalls(Display.java:1338)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1280)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1373)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:116)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/cef/browser/CN1CefBrowserFactory
        at com.codename1.impl.javase.cef.JavaCEFSEPort.createCEFBrowserComponent(JavaCEFSEPort.java:129)
        at com.codename1.impl.javase.cef.JavaCEFSEPort$2.run(JavaCEFSEPort.java:119)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.cef.browser.CN1CefBrowserFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 15 more
```

**Comment by shannah** [comment]
I'm not sure where the settings app is trying to create a browser component, so made a change that will catch and propagate exceptions during creation of CEF browser components so if this happens again, the stack trace will show us where.

**Comment by liannacasper** [comment]
We rewrote the settings app.
