### ISSUE TITLE
iOS cannot play Android's aac and Android cannot play iOS's mp4

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3339]
When recording audio using the [media](https://www.codenameone.com/javadoc/com/codename1/media/MediaManager.html) API, all formats can be played on the same platform they were recorded, but iOS cannot play Android's `aac` and Android cannot play iOS's `mp4`

When attempting to play an `mp4` iOS originating audio on Android the, following line

`MediaManager.createMedia(fullFileName, false);`

throws the exception
```
 java.io.IOException: Prepare failed.: status=0x1. Stacktrace: java.io.IOException: Prepare failed.: status=0x1
	at android.media.MediaPlayer._prepare(Native Method)
	at android.media.MediaPlayer.prepare(MediaPlayer.java:1409)
	at com.codename1.impl.android.f.a(AndroidImplementation.java:3483)
	at com.codename1.impl.android.f.a(AndroidImplementation.java:3436)
	at com.codename1.y.t.a(Display.java:3548)
	at com.codename1.media.f.a(MediaManager.java:256)
	at com.codename1.media.f.a(MediaManager.java:211)
        at app code...
```

The same is true for when trying to play an `aac` Android originating audio on iOS 

As a workaround, I am only recording `mp4` on Android, and `aac` on iOS. That makes both platforms be able to play each other's originating audios

So **this is no big deal** as long as this approach is taken, but I am logging this here for reference/resolution

The audios were recorded on both platforms with the following options (notice how I select format depending on platform to prevent this issue)

```
String mimetype = getPlatformName().equals("and") ? "audio/mp4" : "audio/aac";
String fileName = getPlatformName().equals("and") ? "Audio.mp4" : "Audio.aac";
MediaRecorderBuilder options = new MediaRecorderBuilder()
                .mimeType(mimetype)
                .path(output)
                .bitRate(64000)
                .samplingRate(44100);
Media mic = MediaManager.createMediaRecorder(options);
```

Additional info: The following devices were used to test this:
iOS: iPad4
Android: Samsung Galaxy A6

**Comment by javieranton-zz** [comment]
same as https://github.com/codenameone/CodenameOne/issues/3341
