### ISSUE TITLE
AndroidAsyncView.java:382 crash

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3361]
On Android 11, when I try to switch the focus from a TextField to a lightweight date Picker using the next button in the VKB, I get this error:

```
[EDT] 0:4:7,666 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'void com.codename1.impl.android.a$b.a()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.a$b.a()' on a null object reference
	at com.codename1.impl.android.a.a(AndroidAsyncView.java:382)
	at com.codename1.impl.android.c.a(AndroidImplementation.java:1654)
	at com.codename1.impl.a.t(CodenameOneImplementation.java:644)
	at com.codename1.r.t.m(Display.java:1259)
	at com.codename1.r.t.l(Display.java:1162)
	at com.codename1.r.as.run(RunnableWrapper.java:120)
	at com.codename1.impl.b$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:923) 
```

**Comment by shai-almog** [comment]
@shannah I'm guessing this is similar to this https://github.com/codenameone/CodenameOne/pull/3323
