### ISSUE TITLE
Error painting generated svg image by flamingo In android side

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3373]
2-18 11:12:45.611 23770-23790/? D/ForceSOS: [EDT] 0:0:0,0 - Codename One revisions: 7dd4e7d08b3442d90959477ee52a5ae8c4361b29
2021-02-18 11:12:45.612 23770-23790/? D/ForceSOS: [EDT] 0:0:0,2 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference
2021-02-18 11:12:45.613 23770-23790/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.impl.android.f.b(AndroidImplementation.java:1988)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.z.b(Graphics.java:1160)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.geotracksolutionsint.forcesos.j.d.a(ShieldPhoneCircle.java:130)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.geotracksolutionsint.forcesos.j.d.a(ShieldPhoneCircle.java:120)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.z.a(Graphics.java:660)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o$b.a(Component.java:7205)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.t(Component.java:2691)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.m(Component.java:2649)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2263)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.y.a(Form.java:4488)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.y.b(Form.java:4498)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.d(Component.java:2195)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.c(Component.java:2492)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.o.j(Component.java:2436)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.impl.a.t(CodenameOneImplementation.java:625)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.t.m(Display.java:1259)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.t.l(Display.java:1162)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.v.ar.run(RunnableWrapper.java:120)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at com.codename1.impl.b$1.run(CodenameOneThread.java:60)
2021-02-18 11:12:45.613 23770-23790/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-02-18 11:12:45.626 23770-23790/? D/ForceSOS: [EDT] 0:0:0,16 - | 18-02-2021 11:12:45.625 AM | ForceSOS | ForceSOS |  Info | ----------------------------------------------------------------------------------------
2021-02-18 11:12:45.629 23770-23790/? D/ForceSOS: [EDT] 0:0:0,19 - | 18-02-2021 11:12:45.628 AM | ForceSOS | ForceSOS |  Info | EDT ERROR
2021-02-18 11:12:45.632 23770-23790/? D/ForceSOS: [EDT] 0:0:0,21 - | 18-02-2021 11:12:45.631 AM | ForceSOS | ForceSOS |  Info | ----------------------------------------------------------------------------------------
2021-02-18 11:12:45.634 23770-23790/? D/ForceSOS: [EDT] 0:0:0,24 - | 18-02-2021 11:12:45.633 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->Resolution: 720x1371
2021-02-18 11:12:45.637 23770-23790/? D/ForceSOS: [EDT] 0:0:0,26 - | 18-02-2021 11:12:45.636 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->OS        : and
2021-02-18 11:12:45.639 23770-23790/? D/ForceSOS: [EDT] 0:0:0,29 - | 18-02-2021 11:12:45.638 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->OSVer     : 9
2021-02-18 11:12:45.642 23770-23790/? D/ForceSOS: [EDT] 0:0:0,32 - | 18-02-2021 11:12:45.641 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->AppVer    : 4.0
2021-02-18 11:12:45.644 23770-23790/? D/ForceSOS: [EDT] 0:0:0,34 - | 18-02-2021 11:12:45.643 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->DPI       : 50
2021-02-18 11:12:45.647 23770-23790/? D/ForceSOS: [EDT] 0:0:0,36 - | 18-02-2021 11:12:45.646 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->AppArg    : 
2021-02-18 11:12:45.649 23770-23790/? D/ForceSOS: [EDT] 0:0:0,39 - | 18-02-2021 11:12:45.648 AM | ForceSOS | ForceSOS |  Info | alEdtErrorListener()->url       : https://api4.forcesos.com/forcesos_v4.0/api/sos/uploadMedia
2021-02-18 11:12:45.651 23770-23790/? D/ForceSOS: [EDT] 0:0:0,41 - | 18-02-2021 11:12:45.650 AM | ForceSOS | ForceSOS |  Info | ----------------------------------------------------------------------------------------
2021-02-18 11:12:45.654 23770-23790/? D/ForceSOS: [EDT] 0:0:0,43 - | 18-02-2021 11:12:45.652 AM | ForceSOS | ForceSOS | Error | alEdtErrorListener()->ERROR     : java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference
2021-02-18 11:12:45.654 23770-23790/? D/ForceSOS: [EDT] 0:0:0,44 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference

**Comment by DurankGts** [comment]
Please check this image generated by flamingo compiler that it's working perfectly but this error is genereted

[ShieldPhoneCircle.txt](https://github.com/codenameone/CodenameOne/files/6004502/ShieldPhoneCircle.txt)

see the log in the real device android

2021-02-18 12:43:14.042 32751-346/? D/ForceSOS: [EDT] 0:0:0,398 - Exception: java.lang.NullPointerException - Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference
2021-02-18 12:43:14.042 32751-346/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setAntiAlias(boolean)' on a null object reference
2021-02-18 12:43:14.042 32751-346/? W/System.err:     at com.codename1.impl.android.f.b(AndroidImplementation.java:1988)
2021-02-18 12:43:14.042 32751-346/? W/System.err:     at com.codename1.v.z.b(Graphics.java:1160)
2021-02-18 12:43:14.042 32751-346/? W/System.err:     at com.geotracksolutionsint.forcesos.j.d.a(ShieldPhoneCircle.java:133)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.geotracksolutionsint.forcesos.j.d.a(ShieldPhoneCircle.java:123)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.z.a(Graphics.java:660)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o$b.a(Component.java:7205)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.t(Component.java:2691)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.m(Component.java:2649)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2263)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.q.a(Container.java:1849)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.y.a(Form.java:4488)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.b(Component.java:2279)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.y.b(Form.java:4498)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2252)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.a(Component.java:2227)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.d(Component.java:2195)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.c(Component.java:2492)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.o.j(Component.java:2436)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.impl.a.t(CodenameOneImplementation.java:625)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.t.m(Display.java:1259)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.t.l(Display.java:1162)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.v.ar.run(RunnableWrapper.java:120)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at com.codename1.impl.b$1.run(CodenameOneThread.java:60)
2021-02-18 12:43:14.043 32751-346/? W/System.err:     at java.lang.Thread.run(Thread.java:764)


in the log the line 123

![image](https://user-images.githubusercontent.com/16245755/108391892-8739de00-71e8-11eb-861f-699e93d7ef51.png)

and line 133

![image](https://user-images.githubusercontent.com/16245755/108391994-a46eac80-71e8-11eb-985e-728424ac8eca.png)


in ios doesn't fail, please help to solve this issue.

**Comment by DurankGts** [comment]
The problem in the android side:

![image](https://user-images.githubusercontent.com/16245755/108393458-11367680-71ea-11eb-8b5a-025293827767.png)

if you can cheche the line 1988 of the AndroidImplementatio.java

![image](https://user-images.githubusercontent.com/16245755/108393661-3e832480-71ea-11eb-88e8-9ab57d8b4520.png)

the question is why if probably null there?

**Comment by DurankGts** [comment]
I commetted the line 134 in the ShieldPhoneCircle.java and doesn'fail again. What is the purpose of this line?
