### ISSUE TITLE
couldn't find "librestreaming.so"

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3377]
I'm using an Android library (librestreaming-release.aar) that used to work correctly. I haven't modified anything, a few months ago it worked, now it doesn't work anymore. If I manually edit build.gradle and Manifest.xml to downgrade from API 29 to API 28, the problem is not solved (also in that case the error is `couldn't find "librestreaming.so"`).

Specifically, the native log reports:
```
en.client D/Aren.app: [EDT] 0:0:39,9 - Exception: java.lang.UnsatisfiedLinkError - dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/base.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_dependencies_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_0_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_1_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_2_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_3_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_4_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_5_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_6_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_7_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_8_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/lib/arm64, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/base.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "librestreaming.so"
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/base.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_dependencies_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_0_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_1_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_2_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_3_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_4_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_5_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_6_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_7_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_8_apk.apk", zip file "/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/lib/arm64, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/base.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/app.aren.client-jDDPDcUbLrH43T9x33iXbg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "librestreaming.so"
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err:     at java.lang.System.loadLibrary(System.java:1667)
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err:     at me.lake.librestreaming.client.RESClient.<clinit>(RESClient.java:460)
2021-02-23 08:34:03.907 22161-22194/app.aren.client W/System.err:     at app.aren.client.server.RTMPBroadcastNativeImpl.<init>(RTMPBroadcastNativeImpl.java:25)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at app.aren.client.server.RTMPBroadcastNativeStub.<init>(RTMPBroadcastNativeStub.java:6)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at java.lang.Class.newInstance(Native Method)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.system.NativeLookup.create(NativeLookup.java:79)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at app.aren.client.server.RTMPBroadcast.<init>(RTMPBroadcast.java:12)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at app.aren.client.testing.TestRTMPBroadcast.lambda$completed$4(TestRTMPBroadcast.java:61)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at app.aren.client.testing.TestRTMPBroadcast$$Lambda$1.actionPerformed(Unknown Source:4)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Button.fireActionEvent(Button.java:687)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Button.released(Button.java:728)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Button.pointerReleased(Button.java:835)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.LeadUtil.pointerReleased(LeadUtil.java:153)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Form.pointerReleased(Form.java:3817)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Component.pointerReleased(Component.java:4710)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Display.handleEvent(Display.java:2359)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Display.edtLoopImpl(Display.java:1244)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
2021-02-23 08:34:03.908 22161-22194/app.aren.client W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

The file that it cannot find ("librestreaming.so") is placed in the `aar`, in the `/jni/armeabi-v7a/` folder of the `aar`.

It is not clear to me why the exact same aar in the past worked correctly and now does not. Maybe I've made changes to some build hints in the last few months, but I don't think they have anything to do with this error. However my `codenameone_settings.properties` is the following:

```
#
#Mon Feb 22 14:00:19 CET 2021
codename1.ios.appid=92PT7LUSF8.app.myapp.client
codename1.ios.release.provision=/home/francesco/MyApp/MyAppClient/iosCerts/production_provisioning_profile.mobileprovision
codename1.arg.java.version=8
codename1.arg.ios.enableGalleryMultiselect=true
codename1.arg.ios.objC=true
codename1.arg.ios.newStorageLocation=true
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.arg.ios.project_type=iphone
codename1.arg.var.APP_PACKAGE=app.myapp.client
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait\:UIInterfaceOrientationLandscapeRight
codename1.displayName=MyAppClient
codename1.arg.ios.pods.platform=,8.0,7.0
codename1.android.keystoreAlias=MyApp
codename1.arg.android.xapplication=<receiver android\:name\="com.codename1.sms.intercept.SMSListener" android\:enabled\="true" android\:permission\="android.permission.BROADCAST_SMS" android\:exported\="true"> <intent-filter android\:priority\="2147483647"><category android\:name\="android.intent.category.DEFAULT" /> <action android\:name\="android.provider.Telephony.SMS_RECEIVED" /> </intent-filter> </receiver>
codename1.ios.release.certificate=/home/francesco/MyApp/MyAppClient/iosCerts/appstore_certificate.p12
codename1.android.keystorePassword=xxx
codename1.ios.provision=
codename1.arg.android.allowBackup=false
codename1.arg.ios.multitasking=true
codename1.arg.android.multidex=true
ios.development.push.url=xxx
codename1.arg.var.APP_PROTOCOL=myapp
codename1.arg.ios.NSAppleMusicUsageDescription=Some functionality of the application requires access to your media library
codename1.arg.ios.NSMicrophoneUsageDescription=Some functionality of the application requires your microphone
codename1.cssTheme=true
codename1.arg.android.min_sdk_version=24
codename1.languageLevel=5
codename1.android.keystore=/home/francesco/Keychain.ks
codename1.arg.ios.pods=,SocketRocket,libksygpulive/KSYGPUResource,libksygpulive/libksygpulive
codename1.vendor=MyApp
codename1.arg.ios.NSPhotoLibraryUsageDescription=Some functionality of the application requires access to your photo library
codename1.arg.ios.locationUsageDescription=Some functionality of the application depends on your location
ios.production.push.password=D4Bh2mqC
codename1.ios.certificatePassword=
codename1.arg.ios.NSCameraUsageDescription=Some functionality of the application requires your camera
codename1.ios.debug.certificatePassword=password
codename1.mainName=MainClass
codename1.arg.android.enableProguard=true
codename1.arg.ios.pods.sources=,https\://github.com/CocoaPods/Specs.git
codename1.ios.release.certificatePassword=password
codename1.ios.debug.certificate=/home/francesco/MyApp/MyAppClient/iosCerts/development_certificate.p12
codename1.arg.android.proguardKeep=-dontwarn com.google.android.gms.** -keep class com.daasuu.mp4compose.** { *; } -dontwarn androidx.annotation.*
codename1.arg.android.xapplication_attr=tools\:replace\="android\:label" android\:label\="MyApp.app" android\:requestLegacyExternalStorage\="true"
codename1.arg.android.xpermissions=<uses-feature android\:name\="android.hardware.camera" /><uses-feature android\:name\="android.hardware.camera.autofocus" /><uses-permission android\:name\="android.permission.FLASHLIGHT" /><uses-permission android\:name\="android.permission.MODIFY_AUDIO_SETTINGS"/><uses-permission android\:name\="android.permission.RECEIVE_SMS" /><uses-permission android\:name\="android.permission.CAMERA" required\="true"/><uses-permission android\:name\="android.permission.RECORD_AUDIO" required\="true"/>
codename1.secondaryTitle=CodenameOne_Template
codename1.ios.debug.provision=/home/francesco/MyApp/MyAppClient/iosCerts/development_provisioning_profile.mobileprovision
codename1.arg.build.incSources=1
codename1.rim.certificatePassword=
ios.production.push.url=xxx
codename1.version=1.0
ios.development.push.password=xxx
codename1.ios.certificate=
codename1.icon=icon.png
codename1.rim.signtoolCsk=
codename1.arg.android.gradleDep=implementation 'co.infinum\:goldeneye\:1.1.2';
codename1.arg.android.xintent_filter=<intent-filter><action android\:name\="android.intent.action.VIEW" /><category android\:name\="android.intent.category.DEFAULT" /><category android\:name\="android.intent.category.BROWSABLE" /><data android\:scheme\="${var.APP_PROTOCOL}" /></intent-filter>
codename1.arg.ios.plistInject=<key>CFBundleURLTypes</key><array><dict><key>CFBundleURLName</key><string>${var.APP_PACKAGE}</string></dict><dict><key>CFBundleURLSchemes</key><array><string>${var.APP_PROTOCOL}</string></array></dict></array>
codename1.rim.signtoolDb=
codename1.arg.ios.includePush=true
codename1.packageName=app.myapp.client
```

Thank you for your support

**Comment by jsfan3** [comment]
Solved by the build hint:
```
android.xgradle_default_config=ndk { abiFilters "armeabi-v7a", "x86", "armeabi", "mips"; }
```

Reference:
https://stackoverflow.com/questions/66402178/inject-additional-attributes-into-the-defaultconfig-tag-in-the-android-build-gra
