### ISSUE TITLE
disaster recovery needed

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3387]
My logs captured this event
[2021/04/07 16:35:14] log request from bridge.MasterForm (172.118.142.116)
data=[Java cpu=102% screen=1122x742 ppi=96 deviceDPI=96 scale =1.0  Codename1 sim 15.16 9.0.1 Oracle Corporation http://java.oracle.com/ 53.0 Windows 10 amd64 10.0] (EDT 11 threads)last chance error catcher
error is : java.lang.ArrayIndexOutOfBoundsException: 1000
java.lang.ArrayIndexOutOfBoundsException: 1000
	at com.codename1.ui.Display.handleEvent(Display.java:2414)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1244)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1162)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
[2021/04/07 18:15:30] log request from lib.ConnectionManager (100.34.253.183)

I looked a the code and I see that inputEventStack has a fixed size of 1000, and the size
being used is never checked.  I'm pretty sure just making it larger won't help; something
very bad is going on elsewhere.  For the future, it would be great if some actual information
was on offer instead of a fatal crash.

**Comment by ddyer0** [comment]
This may or may not be directly related to the above, but I hit an example of overfilling inputEventStack today
while using the simulator and the desktop skin.  I was stretching the main window and hit the 1000 element
limit in a context where I got into the debugger.  It was apparently creating an unlimited number of 
size change events.

Thread [EDT] (Suspended (exception ArrayIndexOutOfBoundsException))	
	owns: Object  (id=119)	
	Display.addSizeChangeEvent(int, int, int) line: 2169	
	Display.sizeChanged(int, int) line: 2199	
	JavaCEFSEPort(CodenameOneImplementation).sizeChanged(int, int) line: 2484	
	JavaCEFSEPort(JavaSEPort).sizeChanged(int, int) line: 4708	
	JavaSEPort$C$7.run() line: 2024	
	Display.processSerialCalls() line: 1338	
	Display.edtLoopImpl() line: 1280	
	Display.mainEDTLoop() line: 1162	
	RunnableWrapper.run() line: 120	
	CodenameOneThread.run() line: 176

**Comment by shai-almog** [comment]
Closing per the issue-tracker triage (see [`NEEDS_REVIEW.md`](https://github.com/codenameone/CodenameOne/blob/master/NEEDS_REVIEW.md)).

Vague log dump with no concrete repro and one comment; CN1 sim 15.16 environment is old.
