### ISSUE TITLE
Cannot convert Ant project to Maven

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3397]
I'm sad because I urgently need to make some changes to a very complex project and submit a new build, but now Ant-based projects don't seem to work anymore. In fact, when I try to submit an Android build, I get the error:

```
java.io.IOException: Server returned HTTP response code: 401 for URL: https://cloud.codenameone.com/appsec/7.0/build/upload
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.codename1.build.client.BuildProcess.sendS3Build(BuildProcess.java:469)
	at com.codename1.build.client.BuildProcess.sendRequestToServer(BuildProcess.java:500)
	at com.codename1.build.client.CodeNameOneBuildTask.execute(CodeNameOneBuildTask.java:529)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:574)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:128)
/home/francesco/NetBeansProjects/3_ArenApp/ArenAppClient/build.xml:346: Error in server build process
BUILD FAILED (total time: 3 minutes 25 seconds)
```

So I tried to convert it to Maven using your tool (https://github.com/shannah/maven-migration-tool/releases), v. 1.0.3.

First I tried on the Linux machine where I work (there is installed Oracle Java 1.8.0_231) and with which I developed the project in question. The result is that I didn't get a completion message or anything to make me understand what was going on: there was no error in the log, but the java process started consuming 100% of the CPU for over 20 minutes, after which I stopped it.

I then tried it on macOS (since I know that you developed this tool using MacOS), after installing the latest version of Oracle Java 8 on it. Here I got a precise error message, I cannot copy you the complete log obtained from terminal because Github doesn't accept a so long message, however I copied it in the gist: https://gist.githubusercontent.com/jsfan3/d582568c7db6e9aa6f3b5bbfc7554d41/raw/99c9f687035fff3a13a287c47641468b5502fd7d/error.txt

However, if as a temporary workaround it were possible to continue using Ant, that would be a good thing.

**Comment by liannacasper** [comment]
I can't answer about the conversion issue but the 401 problem is due to an authentication regression that will probably impact maven too. 
Make sure your libraries are up to date.
For Windows: In regedit delete all entries of codenameone and codename1
For Linux do the same under `~/.java/.userPrefs`
For mac do: `rm -Rf ~/Library/Preferences/com.codename1.*`

**Comment by jsfan3** [comment]
@liannacasper Thank you, you put me in the right direction. I inspected the file `/home/francesco/.java/.userPrefs/com/codename1/ui/prefs.xml`: the account was correct, but maybe the token was changed because I suspended my account for a month a renewed it again yesterday. Maybe renewing the account changed the token: I removed that file, I forced to login again and now I can send the builds as before. Thank you very much.

**Comment by jsfan3** [comment]
Solved by switching from Oracle Java 8 to OpenJDK 11.
I also did a complete cleanup of my work environment, I upgraded to the latest version of Netbeans after completely cleaning up all the hidden folders in the user's home, folders containing settings and configuration files that have accumulated over the years.
