### ISSUE TITLE
RFE: include java debug tokens when building debug builds

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#343]
Original [issue 343](https://code.google.com/p/codenameone/issues/detail?id=343) created by codenameone on 2012-09-22T04:21:16.000Z:

<b>What steps will reproduce the problem?</b>
1. Install a debug build of an Android application to device
2. Use adb logcat to view stacktraces

<b>What is the expected output? What do you see instead?</b>

Expecting to see line numbers in stacktraces.  They are there for all the Dalvik APIs, but all Codename One APIs have &quot;Unknown Source&quot; in place of the line numbers.  Example stacktrace:

W/System.err( 6642): java.lang.OutOfMemoryError
I/System.out( 6642): Done
W/System.err( 6642):    at java.io.ByteArrayOutputStream.&lt;init&gt;(ByteArrayOutputStream.java:63)
W/System.err( 6642):    at libcore.net.http.RetryableOutputStream.&lt;init&gt;(RetryableOutputStream.java:35)
W/System.err( 6642):    at libcore.net.http.HttpEngine.initRequestBodyOut(HttpEngine.java:353)
W/System.err( 6642):    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:301)
W/System.err( 6642):    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
W/System.err( 6642):    at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
W/System.err( 6642):    at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:188)
W/System.err( 6642):    at com.codename1.impl.android.AndroidImplementation.openOutputStream(Unknown Source)
W/System.err( 6642):    at com.codename1.io.ConnectionRequest.performOperation(Unknown Source)
W/System.err( 6642):    at com.codename1.io.NetworkManager$NetworkThread.run(Unknown Source)
W/System.err( 6642):    at com.codename1.impl.CodenameOneThread.run(Unknown Source)

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
This works better now for most cases
