### ISSUE TITLE
Missing runtime methods

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3470]
This construct 
    Arrays.copyOf(colorIndex)
gets an error at runtime.  It's very upsetting that there is no compile time complaint,
so this lurks are a latent bomb in code.

In this case, colorIndex is int[], but I believe the same will be true for 
all the base types.

java.lang.NoSuchMethodError: java.util.Arrays.copyOf([I)[I
	at online.shared.SeatingViewer.prepareLaunch(SeatingViewer.java:177)

**Comment by shannah** [comment]
Is this on iOS?

**Comment by ddyer0** [comment]
This happens in the simulator - it never made it into the actual builds.
Just stick this anywhere it will be executed


                int ar[] = new int[100];
		int ar2[] = Arrays.copyOf(ar);

java.lang.NoSuchMethodError: 'int[] java.util.Arrays.copyOf(int[])'
	at online.common.SeatingViewer.prepareLaunch(SeatingViewer.java:203)
	at online.common.SeatingViewer.StopDragging(SeatingViewer.java:280)

**Comment by ddyer0** [comment]
this still fails today
java.lang.NoSuchMethodError: 'int[] java.util.Arrays.copyOf(int[])'
	at com.boardspace.dtest.Dtest.start(Dtest.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.codename1.impl.javase.Executor$4$1.run(Executor.java:341)
	at com.codename1.ui.Display.executeSerialCall(Display.java:1395)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1379)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1166)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by shai-almog** [comment]
Is this happening with Maven? We have checks in maven for that and it would fail in the build servers.

**Comment by ddyer0** [comment]
ant

**Comment by shai-almog** [comment]
Closing as this is not an issue on maven.

**Comment by ddyer0** [comment]
they are also "missing" from actual android builds.  There is no complaint from the build process, but
a runtime error occurs.   Works OK on IOS

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c84ae07e-f2d2-4fb0-a11e-696995b031c7" />

**Comment by ddyer0** [comment]
today: pass IOS fail: android

**Comment by shai-almog** [comment]
To be 100% clear: we will not reopen this since it's only in Ant. That method doesn't compile in Maven and isn't here. Just don't use it. Even in iOS it might vanish suddenly.
