### ISSUE TITLE
Android build fails to start

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3494]
I haven't built since the 25th of August. Today I tried building again, and the resulting Android build crashes upon start. Nothing is shown, not even the splash screen, and nothing can be logged

I also tried building from sources (from server) and saw the same happen

I then try to debug the sources on Android Studio and see this in the `Bug Report` when the app crashes

```
09-06 15:39:05.147 10359 10359 D AndroidRuntime: Shutting down VM
09-06 15:39:05.147 10359 10359 E AndroidRuntime: FATAL EXCEPTION: main
09-06 15:39:05.147 10359 10359 E AndroidRuntime: Process: com.groups.network, PID: 10359
09-06 15:39:05.147 10359 10359 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zza(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ld3/v; or its super classes (declaration of 'd3.v' appears in /data/app/~~yBVlOOHxZ3pdQQ2Im4wq0Q==/com.groups.network-bx0IG3WOeMBUWDW0T5HX9Q==/base.apk)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-06 15:39:05.147 10359 10359 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-06 15:39:05.159   536  3585 I am_crash: [10359,0,com.groups.network,819478340,java.lang.NoSuchMethodError,No static method zza(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ld3/v; or its super classes (declaration of 'd3.v' appears in /data/app/~~yBVlOOHxZ3pdQQ2Im4wq0Q==/com.groups.network-bx0IG3WOeMBUWDW0T5HX9Q==/base.apk),NULL,2]
09-06 15:39:05.162   536  3585 W ActivityTaskManager:   Force finishing activity com.groups.network/.GroupChartStub
09-06 15:39:05.162   536  3585 I wm_finish_activity: [0,116619679,9,com.groups.network/.GroupChartStub,force-crash]
09-06 15:39:05.162   536  3585 I wm_focused_stack: [0,0,1,9,finish-top adjustFocusToNextFocusableStack]
09-06 15:39:05.163   536  3585 I wm_task_moved: [5,1,2147483647]
09-06 15:39:05.163   536  3585 I wm_set_resumed_activity: [0,com.google.android.apps.nexuslauncher/.NexusLauncherActivity,finish-top adjustFocusToNextFocusableStack]
09-06 15:39:05.166   274  8880 D goldfish-address-space: claimShared: Ask to claim region [0x3fb851000 0x3fbd61000]
09-06 15:39:05.175   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.174   536 10377 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-06 15:39:05.180   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80d10
09-06 15:39:05.192   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.196   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80990
09-06 15:39:05.199   536  3585 I wm_pause_activity: [0,116619679,com.groups.network/.GroupChartStub,userLeaving=false]
09-06 15:39:05.207   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.212   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80d10
09-06 15:39:05.217   536  3585 I sysui_multi_action: [757,316,758,4,759,-1]
09-06 15:39:05.218 10359 10359 I Process : Sending signal. PID: 10359 SIG: 9
09-06 15:39:05.231   536   558 I sysui_multi_action: [757,1144,758,7,806,com.groups.network,871,com.groups.network.GroupChartStub]
09-06 15:39:05.234   536   558 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_CANCELLED
09-06 15:39:05.235   536   566 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-06 15:39:05.236   536   566 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-06 15:39:05.240   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.246   261   261 I Zygote  : Process 10359 exited due to signal 9 (Killed)
09-06 15:39:05.247   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80990
09-06 15:39:05.261   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.267   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80d10
09-06 15:39:05.278   149   149 W lowmemorykiller: Failed to open /proc/10359/oom_score_adj; errno=2: process 10359 might have been killed
09-06 15:39:05.290   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.296   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80990
09-06 15:39:05.324   275   275 W EmuHWC2 : validate: layer 21 CompositionType 1, fallback
09-06 15:39:05.330   275   275 W EmuHWC2 : No layers, exit, buffer 0xf2c80d10
09-06 15:39:05.335   536  1873 I ActivityManager: Process com.groups.network (pid 10359) has died: prcp TOP 
09-06 15:39:05.335   536  1873 I am_proc_died: [0,10359,com.groups.network,200,2]
09-06 15:39:05.336   536  1873 I am_uid_stopped: 10154
```

**Comment by javieranton-zz** [comment]
Just verified that the app never gets to enter `init`

**Comment by javieranton-zz** [comment]
Also, in case it is worth notingFound the issue goes away when removing build hint `android.messagingService=gcm`

I think I needed this to implement my own push and keep the CN1 app going, I will investigate further and report back

**Comment by javieranton-zz** [comment]
OK, so in case I am not the only person rolling my own push, here is what happened:

The build hint `android.messagingService=gcm` no longer adds the gradle dependency `implementation 'com.google.android.gms:play-services-gcm:12.0.1'` but it still successfully prevents `apply plugin: 'com.google.gms.google-services'` from being appended to the gradle file (which allows for programmatic firebase initialization rather than initialization via google-services.json). So add  `implementation 'com.google.android.gms:play-services-gcm:12.0.1'` to your `android.gradleDep` build hint and keep the `android.messagingService=gcm` build hint. Gcm dependency is required to be able to call below (programmatic firebase initialization)
```
FirebaseOptions.Builder builder = new FirebaseOptions.Builder()
                .setApplicationId(...)
                .setApiKey(...)
                .setDatabaseUrl(...)
                .setStorageBucket(...);
        FirebaseApp.initializeApp(context(), builder.build());
```

If the above is done, CN1 apps can still use custom push implementations the way it has been possible in the past. Something tells me I am the only person doing this, but who knows!
