### ISSUE TITLE
Error when trying to create a CN1 project in Eclipse

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#354]
Original [issue 354](https://code.google.com/p/codenameone/issues/detail?id=354) created by codenameone on 2012-10-03T04:31:51.000Z:

I created a simple CodenameOne &quot;HelloWorld&quot; project in Eclipse and got the following error:

&quot;java.lang.IllegalStateException: Expected to find an object at table index: 8219&quot;

Here is the entry from the eclipse log:

!ENTRY org.eclipse.core.resources 4 75 2012-10-02 23:48:23.886
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.core.externaltools 4 75 2012-10-02 23:48:23.886
!MESSAGE Errors running builder 'Integrated External Tool Builder' on project 'pointTrace_CN1'.
!STACK 0
java.lang.IllegalStateException: Expected to find an object at table index: 8219
    at org.eclipse.osgi.internal.resolver.StateReader.getFromObjectTable(StateReader.java:83)
    at org.eclipse.osgi.internal.resolver.StateReader.readExportPackageDesc(StateReader.java:413)
    at org.eclipse.osgi.internal.resolver.StateReader.readBundleDescriptionLazyData(StateReader.java:275)
    at org.eclipse.osgi.internal.resolver.StateReader.fullyLoad(StateReader.java:799)
    at org.eclipse.osgi.internal.resolver.StateImpl.fullyLoad(StateImpl.java:1079)
    at org.eclipse.osgi.internal.resolver.StateImpl.getExportedPackages(StateImpl.java:642)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.getExportedPackages(PackageAdminImpl.java:95)
    at org.eclipse.osgi.framework.internal.core.PackageAdminImpl.getExportedPackages(PackageAdminImpl.java:141)
    at org.eclipse.ant.core.AntCorePreferences.getDefaultAntHomeEntries(AntCorePreferences.java:439)
    at org.eclipse.ant.core.AntCorePreferences.getDefaultAntHome(AntCorePreferences.java:304)
    at org.eclipse.ant.core.AntCorePreferences.restoreAntHome(AntCorePreferences.java:292)
    at org.eclipse.ant.core.AntCorePreferences.restoreCustomObjects(AntCorePreferences.java:197)
    at org.eclipse.ant.core.AntCorePreferences.&lt;init&gt;(AntCorePreferences.java:163)
    at org.eclipse.ant.core.AntCorePlugin.getPreferences(AntCorePlugin.java:221)
    at org.eclipse.ant.internal.launching.launchConfigurations.AntHomeClasspathEntry.getAntHome(AntHomeClasspathEntry.java:206)
    at org.eclipse.ant.internal.launching.AntLaunchingUtil.getAntHome(AntLaunchingUtil.java:185)
    at org.eclipse.ant.internal.launching.launchConfigurations.AntLaunchDelegate.launch(AntLaunchDelegate.java:215)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:855)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:704)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:697)
    at org.eclipse.core.externaltools.internal.model.ExternalToolBuilder.launchBuild(ExternalToolBuilder.java:181)
    at org.eclipse.core.externaltools.internal.model.ExternalToolBuilder.doBuildBasedOnScope(ExternalToolBuilder.java:169)
    at org.eclipse.core.externaltools.internal.model.ExternalToolBuilder.build(ExternalToolBuilder.java:88)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Now the project appears to be broken.  When I try to start the emulator nothing happens.  Eclipse settings file is attached.  

I am using Eclipse Juno installed on Windows 7 x64.

**Comment by codenameone** [comment]
Closing old Google code issues which are no longer relevant by now
