### ISSUE TITLE
IOS builds do not work

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3549]
This is a completely virgin initializer project, running under eclipse on a mac.  I have Xcode
installed, and have even (occasionally) used it to build codename1 projects.

[INFO] Request Args: 
[INFO] -----------------
[INFO] hyp.beamId=5e3e0388-7018-413a-9ab6-8175bdc097e2
[INFO] java.version=8
[INFO] maven.codenameone-maven-plugin=7.0.55
[INFO] ios.newStorageLocation=true
[INFO] maven.codenameone-core.version=LATEST
[INFO] -------------------
[INFO] Executing with timeout -1
[INFO] Problem getting Xcode version: Cannot run program "xcodebuild" (in directory "/Users/davedyer/Desktop/bsmac/board/ios/target/codenameone/antProject/dist/ios-build"): error=2, No such file or directory
java.io.IOException: Cannot run program "xcodebuild" (in directory "/Users/davedyer/Desktop/bsmac/board/ios/target/codenameone/antProject/dist/ios-build"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.codename1.builders.Executor.executeProcess(Executor.java:1610)
	at com.codename1.builders.Executor.execStringWithThrow(Executor.java:1477)
	at com.codename1.builders.Executor.execString(Executor.java:1488)
	at com.codename1.builders.IPhoneBuilder.getXcodeVersion(IPhoneBuilder.java:2461)
	at com.codename1.builders.IPhoneBuilder.build(IPhoneBuilder.java:277)
	at com.codename1.maven.CN1BuildMojo.doIOSLocalBuild(CN1BuildMojo.java:994)
	at com.codename1.maven.CN1BuildMojo.createAntProject(CN1BuildMojo.java:544)
	at com.codename1.maven.CN1BuildMojo.executeImpl(CN1BuildMojo.java:114)
	at com.codename1.maven.AbstractCN1Mojo.execute(AbstractCN1Mojo.java:195)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 32 more
[DEBUG] Xcode version is 10
[INFO] Executing:

**Comment by shannah** [comment]
It looks like it can't find xcodebuild.  Make sure you have Xcode installed, and the xcode command-line tools.

**Comment by shannah** [comment]
Note: You'll also need some other things installed too.  E.g. cocoapods
https://shannah.github.io/cn1-maven-archetypes/cn1app-archetype-tutorial/getting-started.html#generate-xcode

**Comment by ddyer0** [comment]
I have all of that.  

xcodebuild -version shows xcode 10.1

**Comment by ddyer0** [comment]
I updated java to the latest (jdk 15) and the builds seem unhappy.   The XML files try to pass
a "maxpermsize" argument to java which is no longer accepted.  Later, (in an IOS build) this
"retrolambda" complaint occurs.  Note that this is in a virgin "hello world" project produced
by the initializer.

INFO] 00:00  INFO: javac hacks:      false

[INFO] 00:00 ERROR: Failed to run Retrolambda
java.lang.IllegalStateException: Cannot initialize dumper; unexpected JDK implementation. Please run Retrolambda using the Java agent (enable forking in the Maven plugin).
	at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.install(LambdaClassDumper.java:38)
	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:67)
	at net.orfjackal.retrolambda.Main.main(Main.java:28)
	Suppressed: java.lang.RuntimeException: java.lang.IllegalAccessException: class net.orfjackal.retrolambda.lambdas.LambdaClassDumper cannot access a member of class java.lang.invoke.InnerClassLambdaMetafactory (in module java.base) with modifiers "private static final"
		at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.uninstall(LambdaClassDumper.java:48)
		at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.close(LambdaClassDumper.java:55)
		at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:102)
		... 1 more
	Caused by: java.lang.IllegalAccessException: class net.orfjackal.retrolambda.lambdas.LambdaClassDumper cannot access a member of class java.lang.invoke.InnerClassLambdaMetafactory (in module java.base) with modifiers "private static final"
		at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
		at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:693)
		at java.base/java.lang.reflect.Field.checkAccess(Field.java:1096)
		at java.base/java.lang.reflect.Field.set(Field.java:791)
		at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.uninstall(LambdaClassDumper.java:46)
		... 3 more
Caused by: java.lang.RuntimeException: Failed to make a field non-final (private static final java.lang.invoke.ProxyClassesDumper java.lang.invoke.InnerClassLambdaMetafactory.dumper). This known to fail on Java 12 and newer. Prefer using Java 8 or try using the Java agent (fork=true in the Maven plugin).
	at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.makeNonFinal(LambdaClassDumper.java:65)
	at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.install(LambdaClassDumper.java:32)
	... 2 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
	at net.orfjackal.retrolambda.lambdas.LambdaClassDumper.makeNonFinal(LambdaClassDumper.java:60)
	... 3 more

**Comment by shannah** [comment]
JDK is not officially supported yet.  Use JDK 8 or JDK 11
