### ISSUE TITLE
showForm() with backCommand causes arrayIndexOutOfBounds error

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#363]
Original [issue 363](https://code.google.com/p/codenameone/issues/detail?id=363) created by codenameone on 2012-10-13T12:21:50.000Z:

<b>Please clearly state whether the issue relates to a device/the simulator or</b>
<b>the tools.</b>

Happens in real device and simulator both.

<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

Tested on iPhone 4, OS 6.0

<b>What steps will reproduce the problem?</b>
1. Add a button on the form which acts as a transition to a different form.
2. When that button is pressed, you want to have a back transition and go back to other form.
3. Press the button once and use the following code in the action event:

    protected void onTxnHistory_HomeAction(Component c, ActionEvent event) {
        // TODO Auto-generated method stub
        super.onTxnHistory_HomeAction(c, event);
        // Show home form
        showForm(&quot;MainUI&quot;, (c.getComponentForm() == null) ? null : c.getComponentForm().getBackCommand());
    }

<b>What is the expected output? What do you see instead?</b>

However when the button is pressed, once, we get the following error:

java.lang.ArrayIndexOutOfBoundsException: 1 &gt; 0
	at java.util.Vector.insertElementAt(Vector.java:551)
	at com.codename1.ui.Container.insertComponentAt(Container.java:407)
	at com.codename1.ui.Container.addComponent(Container.java:426)
	at com.codename1.ui.MenuBar.addCommand(MenuBar.java:992)
	at com.codename1.ui.Form.addCommand(Form.java:2051)
	at com.codename1.ui.util.UIBuilder.initBackForm(UIBuilder.java:1861)
	at com.codename1.ui.util.UIBuilder.showForm(UIBuilder.java:2060)
	at com.codename1.ui.util.UIBuilder.showForm(UIBuilder.java:2160)
	at com.nvsoft.s2pay.fsm.StateMachine.onTxnHistory_HomeAction(StateMachine.java:2244)
	at com.nvsoft.s2pay.fsm.generated.StateMachineBase.handleComponentAction(StateMachineBase.java:4280)
	at com.codename1.ui.util.UIBuilder$FormListener.actionPerformed(UIBuilder.java:2339)
	at com.codename1.ui.util.EventDispatcher.fireActionSync(EventDispatcher.java:366)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:311)
	at com.codename1.ui.Button.fireActionEvent(Button.java:364)
	at com.codename1.ui.Button.released(Button.java:395)
	at com.codename1.ui.Button.pointerReleased(Button.java:483)
	at com.codename1.ui.Form.pointerReleased(Form.java:1991)
	at com.codename1.ui.Component.pointerReleased(Component.java:2163)
	at com.codename1.ui.Display.handleEvent(Display.java:1641)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:906)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:853)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:119)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:171)

After this when you press the button again, it works.

<b>What version of the product are you using? On what operating system?</b>

Latest version of codename1.

<b>Please provide any additional information below.</b>

Also please note if you press the hardware back button/Esc key in simulator when on this form then it is transitioning to the previous form without error but when you press the above button on the form it causes the error.

**Comment by codenameone** [comment]
This was fixed a while back
