### ISSUE TITLE
impossible "not in edt" state

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3644]
If you assume that this snippet works as advertised, this error should be impossible.  Note that the stack shows
"callseriallyandwait" which should guarantee edt.

   	Display dis = Display.getInstance();
    	return(dis.isEdt());

[2022/10/11 00:50:42] log request from crosswords.CrosswordsViewer (47.157.88.72)
data=[Java cpu=38% screen=1920x1842 ppi=120 deviceDPI=120 scale =1.0 Codename1  16.13 java.version=0 java.vendor=The Android Project java.vendor.url=http://www.android.com/ java.class.version=50.0 os.name=Linux os.arch=armv8l os.version=4.9.113] (online.game.Game 24 threads)in paintCanvas
error is : lib.ErrorX: not edt!
lib.ErrorX: not edt!
	at lib.G.Assert(Unknown Source:6)
	at online.game.commonCanvas.redrawClientBoard(Unknown Source:41)
	at online.game.commonCanvas.drawCanvas(Unknown Source:35)
	at online.common.exCanvas.drawClientCanvas(Unknown Source:59)
	at lib.RepaintManager.redrawCanvas(Unknown Source:38)
	at lib.RepaintManager.drawCanvas(Unknown Source:78)
	at lib.RepaintManager$1.run(Unknown Source:32)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:95)
	at com.codename1.ui.Display.callSerially(Display.java:906)
	at com.codename1.ui.Display.callSeriallyAndWait(Display.java:1005)
	at bridge.Platform.runInEdt(Unknown Source:14)
	at lib.RepaintManager.redrawCanvas(Unknown Source:31)
	at lib.RepaintManager.redrawCanvas(Unknown Source:44)
	at lib.RepaintManager.repaintAndOrSleep(Unknown Source:92)
	at online.common.exCanvas.ViewerRun(Unknown Source:58)
	at online.game.commonCanvas.ViewerRun(Unknown Source:358)
	at online.common.commonPanel.runStep(Unknown Source:279)
	at online.game.Game.runStep(Unknown Source:0)
	at online.game.Game.run(Unknown Source:144)
	at java.lang.Thread.run(Thread.java:764)

I produce this reliably, when an external screen shot app has been active, so perhaps the edt
process has be preempted and/or the whole application has been paused and resumed.

**Comment by shai-almog** [comment]
You're running code before the `init()` method was invoked.

https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/Display.java#L900-L907

**Comment by ddyer0** [comment]
that may be true but it's not the problem.  The app was running for a long time before this error occurred.
This may be something related to start/stop, but the piece of code in question is just the normal display 
loop, which is not aware of such things.
