### ISSUE TITLE
App crash since manifest support of Android 12

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#3671]
**Describe the bug**
CN1 seems to use deprecated Android API which isn't supported on Android 12 anymore

**To Reproduce**
Just check the specific line of the `AndroidLocationManager` mentioned in the stacktrace 

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 12

**Additional context**
```
2022-12-25 14:56:16.217 2188-2188/org.igmg.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.igmg.android, PID: 2188
    java.lang.UnsupportedOperationException: GpsStatus APIs not supported, please use GnssStatus APIs instead
        at android.location.LocationManager.addGpsStatusListener(LocationManager.java:2344)
        at com.codename1.location.AndroidLocationManager$2.run(AndroidLocationManager.java:150)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by shai-almog** [comment]
This is a stack from an old version. Notice @shannah made that update in February. See: https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/location/AndroidLocationManager.java#L150

**Comment by kutoman** [comment]
hmm weird. Actually I was surprised that it wasn't fixed yet supposedly. I did update CN1 via the settings UI and then rebuilt the gradle build. Do I have to do anything else? It's been a while I last touched this project..

**Comment by kutoman** [comment]
> Do I have to do anything else?

yes indeed... I noticed that the gradle project was not regenerated due to:
```
[INFO] Android gradle project already exists.  Checking to see if it needs updating...
[INFO] Sources have not changed.  Skipping android gradle project generation
[INFO] Trying to open project in Android studio
```
therefore I forcefully had to make at least one modification to my code in order to force a regeneration, even though imho the recent CN1 update (prior to the "`Gradle Android Project`" command) should be sufficient at least to sync the CN1 libs when trying to regenerate the gradle project.
