### ISSUE TITLE
Rare crash in display code

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3742]
this doesn't appear to directly involve any of my code, but I would guess it involves a window
that has been removed or something like that.

[2023/10/01 01:02:23] log request from bridge.MasterForm (37.30.100.57)
data=[Java cpu=52% screen=1080x2168 ppi=300 deviceDPI=440 scale =1.875 platform =Android 7.53 Codename1  java.version=0 java.vendor=The Android Project java.vendor.url=http://www.and\
roid.com/ java.class.version=50.0 os.name=Linux os.arch=aarch64 os.version=4.14.180-perf-g460df13e1844] (EDT 39 threads)last chance error catcher
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.AndroidAsyncView$AsyncOp.prepare()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.AndroidAsyncView$AsyncOp.prepare()' on a null object reference
        at com.codename1.impl.android.AndroidAsyncView.flushGraphics(AndroidAsyncView.java:406)
        at com.codename1.impl.android.AndroidImplementation.flushGraphics(AndroidImplementation.java:1697)
        at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:644)
        at com.codename1.ui.Display.edtLoopImpl(Display.java:1300)
        at com.codename1.ui.Display.mainEDTLoop(Display.java:1203)
        at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
        at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
        at java.lang.Thread.run(Thread.java:923)

**Comment by ddyer0** [comment]
Maybe not so rare, this looks similar
[2023/10/07 17:43:05] log request from bridge.MasterForm (87.196.75.50)
data=[Java cpu=45% screen=810x1703 ppi=210 deviceDPI=420 scale =1.3125 platform =Android 7.57 Codename1  java.version=0 java.vendor=The Android Project java.vendor.url=http://www.android.com/ java.class.version=50.0 os.name=Linux os.arch=aarch64 os.version=4.14.190-25948257-abA715FXXS9DWD1] (EDT 51 threads)last chance error catcher
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.AndroidAsyncView$AsyncOp.prepare()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.impl.android.AndroidAsyncView$AsyncOp.prepare()' on a null object reference
	at com.codename1.impl.android.AndroidAsyncView.flushGraphics(AndroidAsyncView.java:406)
	at com.codename1.impl.android.AndroidImplementation.flushGraphics(AndroidImplementation.java:1697)
	at com.codename1.impl.CodenameOneImplementation.paintDirty(CodenameOneImplementation.java:644)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1300)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1203)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by ddyer0** [comment]
I'll just add these to the zoo as additional data, in case this complaint ever starts an active investigation.
[2025/11/20 01:28:24] log request from bridge.MasterForm (24.108.145.151)
data=[Java cpu=161% screen=1920x1086 diag=6.48 ppi=210 deviceDPI=340 scale =1.3125 platform =Android 8.98 Codename1  java.version=0 java.vendor=The Android Project java.vendor.url=http://www.android.com/ java.class.version=50.0 os.name=Linux os.arch=aarch64 os.version=5.4.254-qgki-28692233-abT733XXS9DYF1] (EDT 29 threads)last chance error catcher
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.ui.Container.removeAll()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.ui.Container.removeAll()' on a null object reference
	at com.codename1.ui.SideMenuBar.removeCommand(SideMenuBar.java:658)
	at com.codename1.ui.Toolbar$ToolbarSideMenu.removeCommand(Toolbar.java:2565)
	at com.codename1.ui.Form.removeCommand(Form.java:3921)
	at com.codename1.ui.TextField.removeCommands(TextField.java:1468)
	at com.codename1.ui.TextField.focusLostInternal(TextField.java:1494)
	at com.codename1.ui.Component.fireFocusLost(Component.java:2182)
	at com.codename1.ui.Component.fireFocusLost(Component.java:2121)
	at com.codename1.ui.Form.changeFocusState(Form.java:2785)
	at com.codename1.ui.Form.setFocused(Form.java:2827)
	at bridge.MasterForm.setFocused(Unknown Source:0)
	at com.codename1.ui.Form.pointerPressed(Form.java:3240)
	at bridge.MasterForm.pointerPressed(Unknown Source:0)
	at com.codename1.ui.Component.pointerPressed(Component.java:5285)
	at bridge.MasterForm.pointerPressed(Unknown Source:28)
	at com.codename1.ui.Display.handleEvent(Display.java:2273)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1195)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1101)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:131)
	at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:1119)
[history:
E 30+141.034 Log request from bridge.MasterForm
E 30+141.042 [Java cpu=161% screen=1920x1086 diag=6.48 ppi=210 deviceDPI=340 scale =1.3125 platform =Android 8.98 Codename1  java.version=0 java.vendor=The Android Project java.vendor.url=http://www.android.com/ java.class.version=50.0 os.name=Linux os.arch=aarch64 os.version=5.4.254-qgki-28692233-abT733XXS9DYF1] (EDT 28 threads)last chance error catcher
error is : java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.ui.Container.removeAll()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.codename1.ui.Container.removeAll()' on a null object reference
	at com.codename1.ui.MenuBar.removeAllCommands(MenuBar.java:1203)
	at com.codename1.ui.SideMenuBar.removeAllCommands(SideMenuBar.java:196)
	at com.codename1.ui.Form.removeAllCommands(Form.java:4308)
	at com.codename1.ui.TextField.installCommands(TextField.java:1396)
	at com.codename1.ui.TextField.keyPressed(TextField.java:1340)
	at com.codename1.ui.Form.keyPressed(Form.java:2964)
	at bridge.MasterForm.keyPressed(Unknown Source:4)
	at com.codename1.ui.Display.handleEvent(Display.java:2244)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1195)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1101)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:131)
	at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	at java.lang.Thread.run(Thread.java:1119)
