### ISSUE TITLE
Mysterious and impossible error

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3748]
This is new, but seems to be happening only for some android devices.
The "listener" is a native object created by NativeLookup.create

[2023/10/10 19:45:09] log request from com.boardspace.BoardspaceLauncher (193.57.121.234)
data=[Java cpu=26% screen=1080x1962 ppi=300 deviceDPI=480 scale =1.875 platform =Android 7.58 Codename1  java.version=0 java.vendor=The Android Project java.vendor.url=http://www.android.com/ java.class.version=50.0 os.name=Linux os.arch=aarch64 os.version=4.4.22+] (launcher 6 threads)outermost run
error is : java.lang.IncompatibleClassChangeError: The method 'void java.lang.Object.notifyAll!()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'udp.UdpRunner' appears in /data/app/com.boardspace-1/base.apk:classes2.dex)
java.lang.IncompatibleClassChangeError: The method 'void java.lang.Object.notifyAll!()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'udp.UdpRunner' appears in /data/app/com.boardspace-1/base.apk:classes2.dex)
	at udp.UdpRunner.stop(Unknown Source)
	at udp.UDPService.stop(Unknown Source)
	at util.JWSApplication.runLobby(Unknown Source)
	at com.boardspace.BoardspaceLauncher.launchLobby(Unknown Source)
	at com.boardspace.BoardspaceLauncher.doit(Unknown Source)
	at com.boardspace.BoardspaceLauncher.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
[history:

the matching source is this

	public void stop()
			{ dead = true; 
		  if(listener!=null)
			{ 
			  listener.stop();
			  synchronized(listener) { listener.notifyAll(); }
			  G.wake(this);
			  G.timedWait(this,10);
			}
		}

**Comment by ddyer0** [comment]
I'm collecting more instances of this error - it's not limited to a particular device or android version.
