### ISSUE TITLE
nullpointerexception in GC

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3753]
I was debugging under xcode, and got a nullpointer exception in the GC thread at the indicated point.

JAVA_BOOLEAN com_codename1_impl_ios_IOSNative_isSocketConnected___long(CN1_THREAD_STATE_MULTI_ARG JAVA_OBJECT instanceObject, JAVA_LONG socket) {
    POOL_BEGIN();
    SocketImpl* impl = (BRIDGE_CAST SocketImpl*)((void *)socket);
 >>>   JAVA_BOOLEAN b = [impl isConnected];
    POOL_END();
    return b;
}

stack trace
Thread 3

#0    0x00000001136091a2 in virtual_java_lang_Long_longValue___R_long at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/java_lang_Long.m:506
#1    0x00000001114307d6 in com_codename1_impl_ios_IOSImplementation_isSocketConnected___java_lang_Object_R_boolean at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_impl_ios_IOSImplementation.m:14456
#2    0x0000000110f75a02 in virtual_com_codename1_impl_CodenameOneImplementation_isSocketConnected___java_lang_Object_R_boolean at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_impl_CodenameOneImplementation.m:16156
#3    0x0000000113d554fe in com_codename1_io_Socket_SocketInputStream_close__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_io_Socket_SocketInputStream.m:116
#4    0x0000000113d578c7 in virtual_com_codename1_io_Socket_SocketInputStream_close__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_io_Socket_SocketInputStream.m:462
#5    0x0000000113d54ea3 in com_codename1_io_Socket_SocketInputStream_finalize__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_io_Socket_SocketInputStream.m:398
#6    0x0000000113d54a5d in __FINALIZER_com_codename1_io_Socket_SocketInputStream at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/com_codename1_io_Socket_SocketInputStream.m:59
#7    0x000000010f699258 in freeAndFinalize at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/cn1_globals.m:430
#8    0x000000010f699d38 in codenameOneGCSweep at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/cn1_globals.m:830
#9    0x00000001100fc817 in java_lang_System_gcMarkSweep__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/nativeMethods.m:1116
#10    0x0000000111449d67 in java_lang_System_access$200__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/java_lang_System.m:342
#11    0x000000010f794556 in java_lang_System_1_run__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/java_lang_System_1.m:120
#12    0x0000000110add2dc in virtual_java_lang_Runnable_run__ at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/java_lang_Runnable.m:60
#13    0x000000011030528d in java_lang_Thread_runImpl___long at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/java_lang_Thread.m:248
#14    0x00000001100fcde0 in threadRunner at /Users/admin/Desktop/boardspace-7.2/dist/Develop-src/nativeMethods.m:1337

All of the implementation seems to assume that "socket" has been allocated, but that is clearly
not the case.

**Comment by shai-almog** [comment]
Might be related to my work on #3726

**Comment by ddyer0** [comment]
i agree.  if the finalizer is new that would explain how it was unnoticed.

**Comment by ddyer0** [comment]
The issue I’m tracking is compatible with the hypotheses that this npe leaves the gc disabled, and subsequently any process that becomes blocked for gc is effectively dead.
