### ISSUE TITLE
BrowserComponent crash on Android 11

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3791]
This occurs in a BrowserComponent window on my newest device, which is running android 11.  The
initial url renders correctly, clicking on any link crashes.  I managed to extract this messy trace using
ADB.   

All this works fine on all my other (older) devices, both IOS and android.   As far as I can tell this
isn't interacting at all with the minimal wrapper I have around the browsercomponent.

I have a much longer logcat segment that this interface won't let me attach, but I suspect
you'll need to make your own anyway.

03-01 12:54:57.328  1783  1783 W libc    : Access denied finding property "vendor.ril.testmode"
03-01 12:54:57.330  1298  5569 I Telecom-Common: isInEmergencyCall: false: TSI.iIEC@KCg
03-01 12:54:57.331  1783  1783 W libc    : Access denied finding property "vendor.ril.testmode"
03-01 12:54:57.331  1298  1497 I Telecom-Common: isInEmergencyCall: false: TSI.iIEC@KCk
03-01 12:54:57.336   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000001,0.039544,0.000061, totalTime 0.039606 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.389   663   766 I libPerfCtl: xgfGetFPS pid:6618 fps:52
03-01 12:54:57.389   663   766 I libPowerHal: [updateFPS] pid(6618) : -1 => 60
03-01 12:54:57.389   663   780 I libPowerHal: [perfNotifyAppState] pack:ant.boardspace, act:ant.boardspace.Develop2Stub, state:5, pid:6618, uid:10211, fps:60
03-01 12:54:57.389   663   780 E UxUtility: notifyAppState error = NULL
03-01 12:54:57.390   663   780 I TouchUtility: notifyAppState error = NULL
03-01 12:54:57.485  1298  1497 E ActivityManager: Activity Manager Crash. UID:99030 PID:6693 TRANS:70
03-01 12:54:57.485  1298  1497 E ActivityManager: java.lang.NullPointerException: Attempt to get length of null array
03-01 12:54:57.485  1298  1497 E ActivityManager:       at com.android.server.am.ActivityManagerService.getMemoryInfo(ActivityManagerService.java:5892)
03-01 12:54:57.485  1298  1497 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3260)
03-01 12:54:57.485  1298  1497 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2550)
03-01 12:54:57.485  1298  1497 E ActivityManager:       at android.os.Binder.execTransactInternal(Binder.java:1179)
03-01 12:54:57.485  1298  1497 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:1143)
03-01 12:54:57.486  6693  6725 E chromium: [ERROR:jni_android.cc(319)] Crashing due to uncaught Java exception
03-01 12:54:57.511  6693  6725 E chromium: [ERROR:jni_android.cc(358)] Native stack trace:
03-01 12:54:57.511  6693  6725 E chromium: #00 pc 0x0000000003cb8ebf /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #01 pc 0x0000000002bb5e2f /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #02 pc 0x0000000002bb5517 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #03 pc 0x0000000002fe19d3 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #04 pc 0x0000000002fe1313 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #05 pc 0x0000000002dc651f /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #06 pc 0x0000000002dc61fb /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #07 pc 0x0000000002dc614f /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #08 pc 0x0000000002e99f43 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #09 pc 0x0000000002e960df /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #10 pc 0x0000000002a817e3 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #11 pc 0x0000000002a811ff /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #12 pc 0x0000000002a11fbf /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #13 pc 0x0000000002a118ef /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #14 pc 0x00000000029eb283 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #15 pc 0x00000000029ea753 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #16 pc 0x00000000029e455b /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #17 pc 0x0000000002bd1e87 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #18 pc 0x0000000002bd16af /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #19 pc 0x0000000002bd19df /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #20 pc 0x0000000002a7bc37 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #21 pc 0x0000000002a7baef /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #22 pc 0x0000000002b6c40f /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #23 pc 0x0000000002b6712f /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #24 pc 0x0000000002bdf01b /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #25 pc 0x0000000002b5d833 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #26 pc 0x0000000002b5d393 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #27 pc 0x0000000002b468bb /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #28 pc 0x0000000002ba2be7 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #29 pc 0x0000000002b60257 /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium: #30 pc 0x0000000002b5febb /data/app/~~aKEu-pTP5I9lky3e5U6BAw==/com.google.android.trichromelibrary_616717833-QRm0d5SYo6LQIMCA8okH4g==/base.apk (offset 0x8dc000)
03-01 12:54:57.511  6693  6725 E chromium:
03-01 12:54:57.512  6693  6725 E cr_JniAndroid: Handling uncaught Java exception
03-01 12:54:57.512  6693  6725 E cr_JniAndroid: java.lang.NullPointerException: Attempt to get length of null array
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Parcel.createExceptionOrNull(Parcel.java:2462)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Parcel.createException(Parcel.java:2440)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Parcel.readException(Parcel.java:2423)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Parcel.readException(Parcel.java:2365)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.app.IActivityManager$Stub$Proxy.getMemoryInfo(IActivityManager.java:7206)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.app.ActivityManager.getMemoryInfo(ActivityManager.java:2670)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at org.chromium.base.SysUtils.isCurrentlyLowMemory(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:16)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at J.N.M1Y_XVCN(Native Method)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at WV.Ac.run(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:257)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at java.lang.Thread.run(Thread.java:920)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid: Caused by: android.os.RemoteException: Remote stack trace:
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at com.android.server.am.ActivityManagerService.getMemoryInfo(ActivityManagerService.java:5892)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3260)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2550)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Binder.execTransactInternal(Binder.java:1179)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:         at android.os.Binder.execTransact(Binder.java:1143)
03-01 12:54:57.512  6693  6725 E cr_JniAndroid:
03-01 12:54:57.516  6693  6725 E chromium: [ERROR:java_exception_reporter.cc(83)] java.lang.NullPointerException: Attempt to get length of null array
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Parcel.createExceptionOrNull(Parcel.java:2462)
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Parcel.createException(Parcel.java:2440)
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Parcel.readException(Parcel.java:2423)
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Parcel.readException(Parcel.java:2365)
03-01 12:54:57.516  6693  6725 E chromium:      at android.app.IActivityManager$Stub$Proxy.getMemoryInfo(IActivityManager.java:7206)
03-01 12:54:57.516  6693  6725 E chromium:      at android.app.ActivityManager.getMemoryInfo(ActivityManager.java:2670)
03-01 12:54:57.516  6693  6725 E chromium:      at org.chromium.base.SysUtils.isCurrentlyLowMemory(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:16)
03-01 12:54:57.516  6693  6725 E chromium:      at J.N.M1Y_XVCN(Native Method)
03-01 12:54:57.516  6693  6725 E chromium:      at WV.Ac.run(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:257)
03-01 12:54:57.516  6693  6725 E chromium:      at java.lang.Thread.run(Thread.java:920)
03-01 12:54:57.516  6693  6725 E chromium: Caused by: android.os.RemoteException: Remote stack trace:
03-01 12:54:57.516  6693  6725 E chromium:      at com.android.server.am.ActivityManagerService.getMemoryInfo(ActivityManagerService.java:5892)
03-01 12:54:57.516  6693  6725 E chromium:      at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3260)
03-01 12:54:57.516  6693  6725 E chromium:      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2550)
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Binder.execTransactInternal(Binder.java:1179)
03-01 12:54:57.516  6693  6725 E chromium:      at android.os.Binder.execTransact(Binder.java:1143)
03-01 12:54:57.517  6693  6725 F chromium: [FATAL:java_exception_reporter.cc(84)] Uncaught exception
03-01 12:54:57.517   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000002,0.039868,0.000126, totalTime 0.039995 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.529  1783  1783 W m.android.phone: type=1400 audit(0.0:804205): avc: denied { read } for name="u:object_r:system_mtk_power_off_md_prop:s0" dev="tmpfs" ino=12308 scontext=u:r:radio:s0 tcontext=u:object_r:system_mtk_power_off_md_prop:s0 tclass=file permissive=0
03-01 12:54:57.531  1783  1783 W libc    : Access denied finding property "vendor.ril.testmode"
03-01 12:54:57.533  1298  1497 I Telecom-Common: isInEmergencyCall: false: TSI.iIEC@KCo
03-01 12:54:57.533  1783  1783 W m.android.phone: type=1400 audit(0.0:804206): avc: denied { read } for name="u:object_r:system_mtk_power_off_md_prop:s0" dev="tmpfs" ino=12308 scontext=u:r:radio:s0 tcontext=u:object_r:system_mtk_power_off_md_prop:s0 tclass=file permissive=0
03-01 12:54:57.535  1783  1783 W libc    : Access denied finding property "vendor.ril.testmode"
03-01 12:54:57.537  1298  1497 I Telecom-Common: isInEmergencyCall: false: TSI.iIEC@KCs
03-01 12:54:57.577   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000003,0.039521,0.000099, totalTime 0.039624 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.617   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000001,0.039640,0.000138, totalTime 0.039779 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.657   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000002,0.039286,0.000131, totalTime 0.039418 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.689  6755  6755 D AVStageFactory: createInstance(64bit): createVendorAVFactory success!
03-01 12:54:57.690  6755  6755 D AVStageUtils: createInstance(64bit): createVendorAVUtils success!
03-01 12:54:57.690  6755  6755 D AVStageFactory: createInstance(64bit): createVendorAVFactory success!
03-01 12:54:57.696   645 29746 W AudioALSACaptureDataProviderNormal: readThread, latency_in_s,0.000002,0.039280,0.000075, totalTime 0.039358 > logTimeout 0.022000 TIMEOUT!!
03-01 12:54:57.733  1783  1783 W m.android.phone: type=1400 audit(0.0:804207): avc: denied { read } for name="u:object_r:system_mtk_power_off_md_prop:s0" dev="tmpfs" ino=12308 scontext=u:r:radio:s0 tcontext=u:object_r:system_mtk_power_off_md_prop:s0 tclass=file permissive=0

**Comment by shannah** [comment]
@ddyer0 I'm unable to reproduce so far.  I created a test webpage with a link, and loaded it in a BrowserComponent and am able to follow links without a problem.  This is the test webpage I made https://weblite.ca/tmp/cn1test/

I tested on API 28 and API 33.

Can you try this webpage in your browser component, and let me know if it works.  If it works, please modify as necessary to reproduce the error.

**Comment by ddyer0** [comment]
Interesting.  I'm able to open that page by typing into my URL line, but following
the "google" link crashes.   
As previously mentioned, this behavior is only on my newest tablet, which is the first one
I have running android 11.  It's possible the flaw is not android 11, but something else
peculiar to this tablet.
You should try it on your device with my app - boardspace.net from the app store.  Open any
of the links on the "boardspace links" menu on the first screen.

**Comment by ddyer0** [comment]
unsure what happened, but this is no longer a problem.
